# -*- coding: utf-8 -*-
"""Columna de halajot (siman 512 y 511) + pie de anuncios."""

BLOQUES = []

BLOQUES.append({"t": "titulo",
  "he": "פִּנַּת הַהֲלָכָה - סִימָן תקי\"ב",
  "es": "El rincón de la halajá — Siman 512"})

HALAJOT_A = [
 ("א", "אָסוּר לְבַשֵּׁל לְצוֹרֶךְ גּוֹי בְּיוֹם טוֹב, שֶׁנֶּאֱמַר \"אַךְ אֲשֶׁר יֵיאָכֵל לְכָל נֶפֶשׁ הוּא לְבַדּוֹ יֵיעָשֶׂה לָכֶם\", לָכֶם וְלֹא לַגּוֹיִים. וְאָסוּר לְבַשֵּׁל גַּם לְצוֹרֶךְ קָרָאִים בְּיוֹם טוֹב. וְכֵן אָסוּר לְבַשֵּׁל לְצוֹרֶךְ יִשְׂרָאֵל שֶׁמְּחַלֵּל שַׁבָּת בְּפַרְהֶסְיָא. לְפִיכָךְ אָסוּר לְהַזְמִינוֹ לִסְעֹוד עִמּוֹ סְעֻודּוֹת יוֹם טוֹב, גְּזֵירָה שֶׁמָּא יְבַשֵּׁל בִּשְׁבִילוֹ ]בִּקְדֵירָה בִּפְנֵי עַצְמָהּ[. וְאִם בָּא גּוֹי אוֹ קָרָאִי אוֹ מְחַלֵּל שַׁבָּת בְּפַרְהֶסְיָא לְבַקְּרוֹ בְּיוֹם טוֹב יֵשׁ אוֹמְרִים שֶׁמֻּתָּר לַעֲשׂוֹת קָפֶה הַרְבֵּה בְּבַת אַחַת, בְּאוֹפֶן שֶׁיִּשְׁתֶּה עִמּוֹ גַּם בַּעַל הַבַּיִת. וְהַנָּכוֹן לְהַחְמִיר, אֲפִילּוּ אִם מַקְדִּים שְׁתִיָּיתָם לִשְׁתִיַּית הַגּוֹי.",
  "Está prohibido cocinar para un gentil en Yom Tov, pues está dicho «solo lo que se coma por cada persona, eso solo se hará para vosotros» —para vosotros y no para los gentiles—. Y también está prohibido cocinar para un caraíta en Yom Tov. Y asimismo está prohibido cocinar para un judío que profana el Shabat en público. Por eso está prohibido invitarlo a comer con uno las comidas de Yom Tov, por temor a que se cocine para él (en una olla aparte). Y si viene un gentil, un caraíta o un profanador del Shabat en público a visitarlo en Yom Tov, hay quienes dicen que está permitido hacer mucho café de una sola vez, de modo que también beba de él el dueño de casa. Y lo correcto es ser estricto, incluso si adelanta su bebida a la del gentil."),
 ("ב", "מִי שֶׁאָכַל בָּשָׂר, מוּתָּר לוֹ לְבַשֵּׁל מַאֲכָלֵי גְּבִינָה בְּיוֹם טוֹב גַּם בְּתוֹךְ שֵׁשׁ שָׁעוֹת מִזְּמַן אֲכִילַת הַבָּשָׂר. וְכֵן מִי שֶׁאָסוּר לוֹ לֶאֱכוֹל אֵיזֶה מַאֲכָל מֵחֲמַת חֳלִי, כְּגוֹן חוֹלֶה סֻכֶּרֶת שֶׁאָסוּר לוֹ לֶאֱכוֹל מַאֲכָל מָתוֹק, מוּתָּר לוֹ לְבַשֵּׁל בְּיוֹם טוֹב מַאֲכָל מָתוֹק לְצוֹרֶךְ אֲחֵרִים, וְכָל שֶׁכֵּן שֶׁמֻּתָּר לוֹ לְטַלְטֵל מַמְתַּקִּים וְכַדּוֹמֶה, אַף שֶׁאֵינָם רְאוּיִים בִּשְׁבִילוֹ לַאֲכִילָה.",
  "Quien comió carne, le está permitido cocinar alimentos lácteos en Yom Tov, incluso dentro de las seis horas desde el momento de comer la carne. Y asimismo, quien tiene prohibido comer algún alimento por causa de enfermedad —como un enfermo de diabetes al que le está prohibido comer algo dulce—, le está permitido cocinar en Yom Tov un alimento dulce para otros; y con mayor razón le está permitido trasladar dulces y similares, aunque no sean aptos para que él los coma."),
 ("ג", "עַכּוּ\"ם שֶׁהֵבִיא לְיִשְׂרָאֵל בְּיוֹם טוֹב דָּבָר שֶׁיֵּשׁ בְּמִינוֹ בִּמְחֻבָּר, אוֹ מְחוּסַּר צֵידָה, שֶׁיֵּשׁ לַחֲשׁוֹשׁ שֶׁמָּא תְּלָשָׁם בְּיוֹם טוֹב, וְטָעָה הַיִּשְׂרָאֵל וּבֵירַךְ עָלָיו כְּדֵי לְאוֹכְלוֹ, אַף עַל פִּי שֶׁהוּא מֻקְצֶה יֵשׁ לוֹ לִטְעֹום מְעַט מֵהַפְּרִי, כְּדֵי שֶׁלֹּא תִּהְיֶה בְּרָכָתוֹ בְּרָכָה לְבַטָּלָה. וְאִם הָיָה בְּתוֹךְ הַסְּעֻודָּה שֶׁאֵין כָּאן בְּרָכָה, וְטָעָה הַיִּשְׂרָאֵל וּנְתָנוֹ לְתוֹךְ פִּיו וּלְעָסוֹ, אָסוּר לוֹ לְבָלְעוֹ.",
  "Un gentil que trajo a un judío en Yom Tov algo cuya especie está todavía unida a la tierra, o que le falta ser cazado, de modo que haya que temer que lo haya arrancado en Yom Tov, y el judío se equivocó y bendijo sobre ello para comerlo —aunque sea <i>muktzé</i>—, debe probar un poco de la fruta, para que su bendición no sea en vano. Y si fue durante la comida, donde no hace falta bendición, y el judío se equivocó y se lo puso en la boca y lo masticó, tiene prohibido tragarlo."),
]

for letra, he, es in HALAJOT_A:
  BLOQUES.append({"t": "halaja", "letra": letra, "he": he, "es": es})

BLOQUES.append({"t": "sub",
  "he": "סִימָן תקי\"א – הֲנָאָה הַשָּׁוָוה לְכָל נֶפֶשׁ",
  "es": "Siman 511 — el goce equivalente para cualquier persona"})

HALAJOT_B = [
 ("א", "הֲנָאָה הַשָּׁוָוה לְכָל נֶפֶשׁ מוּתֶּרֶת בְּיוֹם טוֹב כְּאוֹכֶל נֶפֶשׁ עַצְמוֹ, וְלָכֵן מוּתָּר לַעֲשׂוֹת מְדוּרָה לְהִתְחַמֵּם כְּנֶגְדָּהּ, בִּזְמַן הַקֹּר, שֶׁבְּכָל מָקוֹם שֶׁנֶּאֱמַר \"יֵיאָכֵל\" )הַיּוּ\"ד בְּצֵירֵי(, נִכְלָל בָּזֶה גַּם הֲנָאָה, וְהוֹאִיל וְנֶאֱמַר: אֲשֶׁר \"יֵיאָכֵל\" לְכָל נֶפֶשׁ, הוּתְּרָה הַהֲנָאָה כְּמוֹ הָאֲכִילָה. וּמִטַּעַם זֶה מוּתָּר גַּם כֵּן לְחַמֵּם מַיִם חַמִּים לִרְחֹץ בָּהֶם פָּנָיו יָדָיו וְרַגְלָיו, שֶׁהִיא הֲנָאָה הַשָּׁוָוה \"לְכָל נֶפֶשׁ\". אֲבָל לִרְחֹץ כָּל גּוּפוֹ אָסוּר, שֶׁאֵין זוֹ הֲנָאָה הַשָּׁוָוה \"לְכָל\" נֶפֶשׁ. כָּךְ כָּתַב הַטַּעַם בַּחתם\"ס שַׁבָּת לט: דְּדָמֵי לְמוּגְמָר, שֶׁמָּא יְחַמֵּם מַיִם, כְּמוֹ בְּשַׁבָּת. וּלְהָרִי\"ף וְהָרַמְבַּ\"ם וּמָרַן עֶצֶם הַחִמּוּם לְכָל גּוּפוֹ אִיסּוּרוֹ מִדְּרַבָּנָן מִשּׁוּם גְּזֵירַת מֶרְחָץ, וְלָכֵן לֹא אָסְרוּ רְחִיצַת כָּל גּוּפוֹ, מִמַּיִם שֶׁהוּחַמּוּ מֵעֶרֶב יו\"ט.",
  "El goce equivalente para cualquier persona está permitido en Yom Tov, igual que la propia comida; por eso está permitido hacer una fogata para calentarse junto a ella en época de frío, pues en todo lugar donde está dicho «se comerá», queda incluido también el goce, y puesto que está dicho: lo que «se coma» por cada persona, se permitió el goce igual que la comida. Y por esta misma razón está permitido también calentar agua caliente para lavarse en ella la cara, las manos y los pies, que es un goce equivalente «para cualquier persona». Pero lavarse todo el cuerpo está prohibido, pues eso no es un goce equivalente «para cualquier» persona. Así escribió la razón el Jatam Sofer en Shabat 39: porque se asemeja al incienso, no sea que caliente agua, como en Shabat. Y según el Rif, el Rambam y Marán, el calentamiento mismo para todo el cuerpo es una prohibición de origen rabínico, por el decreto de los baños públicos, y por eso no prohibieron lavarse todo el cuerpo con agua que se calentó desde la víspera de Yom Tov."),
 ("ב", "מַיִם שֶׁהוּחַמּוּ בְּעֶרֶב יוֹם טוֹב מוּתָּר לִרְחֹץ בָּהֶם כָּל גּוּפוֹ כְּאֶחָד, שֶׁלֹּא גָּזְרוּ בָּזֶה אֶלָּא בְּשַׁבָּת, וְדַוְקָא חוּץ לַמֶּרְחָץ אֲבָל בְּבֵית הַמֶּרְחָץ אָסוּר. וּבְאַמְבַּטְיָה פְּרָטִית שֶׁנִּמְצֵאת בְּדִירָתוֹ יֵשׁ לְהָקֵל. וְכֵן מַיִם שֶׁהוּחַמּוּ בְּדוּד שֶׁמֶשׁ, מוּתָּר לְהִתְרַחֵץ בָּהֶם כָּל גּוּפוֹ בְּיוֹם טוֹב, כְּשֶׁהוּא בְּאַמְבַּטְיָה פְּרָטִית שֶׁנִּמְצֵאת בְּדִירָתוֹ.",
  "El agua que se calentó en víspera de Yom Tov está permitido lavarse en ella todo el cuerpo de una vez, pues eso solo lo decretaron en Shabat, y precisamente fuera de los baños públicos, pero en un baño público está prohibido. Y en una bañera privada que se encuentra en su propia vivienda hay lugar para ser indulgente. Y asimismo el agua que se calentó en un calentador solar, está permitido bañarse en ella todo el cuerpo en Yom Tov, cuando está en una bañera privada que se encuentra en su vivienda."),
 ("ג", "מוּגְמָר אָסוּר בְּיוֹם טוֹב, וְהַיְינוּ לְפַזֵּר אַבְקַת בְּשָׂמִים עַל גַּבֵּי גֶּחָלִים לְהָרִיחַ, אוֹ לְגַמֵּר כֵּלִים, וְכַיּוֹצֵא בָּזֶה. וְהַטַּעַם לְאִיסּוּר זֶה, מִפְּנֵי שֶׁבְּעֵת שֶׁמְּפַזֵּר הַבְּשָׂמִים עַל הַגֶּחָלִים הוּא מְכַבֶּה אוֹתָן וּלְבַסּוֹף מַבְעִירָן, וּמִכֵּיוָן שֶׁאֵין זוֹ הֲנָאָה הַשָּׁוָוה \"לְכָל\" נֶפֶשׁ, כִּי אִם לָעֲשִׁירִים הַמְּפֻנָּקִים בִּלְבַד אָסוּר. אֲבָל אִם עוֹשֶׂה כְּדֵי לָתֵת רֵיחַ טוֹב בְּפֵירוֹת לְמַתְּקָם לַאֲכִילָה מוּתָּר, וַאֲפִילּוּ אִם הֵם טוֹבִים וּרְאוּיִים לַאֲכִילָה בְּלִי זֶה אֶלָּא שֶׁעַל יְדֵי כָּךְ מַמְתִּיקָם יוֹתֵר מוּתָּר, שֶׁאֵין דִּין מוֹלִיד רֵיחָא בְּאוֹכָלִים. וּמִטַּעַם זֶה מוּתָּר גַּם כֵּן לָתֵת מֵי וְרָדִים בְּכוֹס מַיִם אוֹ יַיִן וּשְׁאָר מַשְׁקִים. וְכֵן מוּתָּר לִשְׁפּוֹךְ טִיפּוֹת מֵי וְרָדִים וְכַדּוֹמֶה לְתוֹךְ טַבָּק הֲרָחָה, שֶׁלְּעִנְיָן זֶה נֶחְשָׁב כְּאוֹכֶל, וְאֵין מוֹלִיד רֵיחָא בְּאוֹכָלִים. אֲבָל אָסוּר לִשְׁפּוֹךְ מֵי וְרָדִים וּשְׁאָר מִינֵי בְּשָׂמִים עַל מִטְפַּחַת כִּיס. וּמִכָּל מָקוֹם מוּתָּר לָתֵת רֵיחַ טוֹב בְּיָדַיִם וּבְפָנִים, שֶׁאֵין זֶה דָּבָר הַמִּתְקַיֵּים, שֶׁזֵּיעַת הָאָדָם מַעֲבִירָתוֹ מֵעַל בְּשָׂרוֹ.",
  "El incienso está prohibido en Yom Tov, es decir, esparcir polvo de especias sobre brasas para olerlo, o sahumar utensilios, y cosas semejantes. Y la razón de esta prohibición es que al esparcir las especias sobre las brasas las apaga y al final las enciende, y como este no es un goce equivalente «para cualquier» persona, sino solo para los ricos consentidos, está prohibido. Pero si lo hace para dar buen aroma a frutas y endulzarlas para comer, está permitido, e incluso si son buenas y aptas para comer sin ello, pero mediante esto las endulza más, está permitido, pues no rige la regla de «generar aroma» en los alimentos. Y por esta misma razón también está permitido poner agua de rosas en un vaso de agua o vino y otras bebidas. Y asimismo está permitido verter gotas de agua de rosas y similares dentro de tabaco de aspirar, pues para este propósito se considera como alimento, y no rige «generar aroma» en los alimentos. Pero está prohibido verter agua de rosas y otros tipos de especias sobre un pañuelo de bolsillo. Y de cualquier modo está permitido poner buen aroma en las manos y en el rostro, pues esto no es algo que perdura, ya que el sudor de la persona lo hace desaparecer de su piel."),
 ("ד", "מוּתָּר לְעַשֵּׁן סִיגַרְיוֹת בְּיוֹם טוֹב, וְאַף עַל פִּי שֶׁיֶּשְׁנָם אַחֲרוֹנִים שֶׁאוֹסְרִים, מִפְּנֵי שֶׁמְּדַמִּים אוֹתוֹ לְמוּגְמָר שֶׁאֵינוֹ שָׁוֶוה \"לְכָל\" נֶפֶשׁ, פָּשַׁט הַמִּנְהָג לְהַתִּיר. וּבִפְרָט בִּזְמַן הָאַחֲרוֹן שֶׁהָעִישּׁוּן נָפוֹץ מְאֹד, וְאִם לֹא יְעַשֵּׁן יִהְיֶה לוֹ צַעַר מֵהַדָּבָר. וּמִכָּל מָקוֹם אָדָם שֶׁאֵינוֹ רָגִיל כָּל כָּךְ בְּעִישּׁוּן וְאֵין לוֹ צַעַר בִּמְנִיעָתוֹ, וּמְכַבְּדִים אוֹתוֹ בְּסִיגַרְיָה בְּיוֹם טוֹב, אוֹ שֶׁרוֹצֶה לְעַשֵּׁן לְשֵׁם תַּעֲנוּג בְּעָלְמָא, נָכוֹן שֶׁיִּמָּנַע מִלְּעַשֵּׁן בְּיוֹם טוֹב. וְתָבוֹא עָלָיו בִּרְכַּת טוֹב. וְכָל זֶה מִצַּד דִּין יוֹם טוֹב, אֲבָל לְגַבֵּי עֶצֶם הָעִישּׁוּן, דַּעַת הָרוֹפְאִים בִּזְמַנֵּנוּ שֶׁהָעִישּׁוּן גּוֹרֵם לְחָלָאִים רַבִּים הַמְּסַכְּנִים אֶת בְּרִיאוּת הָאָדָם, וְשׁוֹמֵר נַפְשׁוֹ יִרְחַק מִזֶּה.",
  "Está permitido fumar cigarrillos en Yom Tov, y aunque hay <i>ajaronim</i> que lo prohíben porque lo comparan con el incienso, que no es equivalente «para cualquier» persona, se extendió la costumbre de permitirlo. Y en particular en los últimos tiempos, en que fumar está muy extendido, y si no fuma le causará aflicción. Y de cualquier modo, la persona que no está tan acostumbrada a fumar y no le causa aflicción abstenerse, y le ofrecen un cigarrillo en Yom Tov, o quiere fumar solo por placer, es correcto que se abstenga de fumar en Yom Tov, y le vendrá bendición de bien. Y todo esto por el lado de la ley de Yom Tov, pero respecto al fumar en sí, la opinión de los médicos en nuestro tiempo es que fumar causa numerosas enfermedades que ponen en peligro la salud de la persona, y quien cuida su alma se alejará de esto."),
 ("ה", "יֵשׁ לְהַתִּיר לְעַשֵּׁן סִיגַרְיוֹת בְּיוֹם טוֹב גַּם כְּשֶׁמֻּדְפָּסוֹת עֲלֵיהֶם אוֹתִיּוֹת שׁוֹנוֹת. וְאַף עַל פִּי שֶׁהוּא מוֹחֵק אֶת הָאוֹתִיּוֹת בְּעֵת שֶׁמְּעַשֵּׁן בִּמְקוֹם הָאוֹתִיּוֹת וְהָאוֹתִיּוֹת נִשְׂרָפוֹת עַל יְדֵי כָּךְ.",
  "Hay que permitir fumar cigarrillos en Yom Tov también cuando llevan impresas distintas letras. Y aunque borra las letras al fumar, en el lugar de las letras, y las letras se queman por ello."),
 ("ו", "יֵשׁ שֶׁנּוֹהֲגִים לְהַחְמִיר שֶׁלֹּא לְהָסִיר אֶת הָאֵפֶר שֶׁנִּשְׂרַף מֵהַסִּיגַרְיָה בְּיוֹם טוֹב, מֵחֲשָׁשׁ שֶׁיִּהְיוּ נִיצוֹצוֹת אֵשׁ נִיתָּזִין עִמּוֹ, וּמִכָּל מָקוֹם אֵין זֶה מֵעִיקַּר הַדִּין.",
  "Hay quienes acostumbran ser estrictos y no retirar la ceniza que se quemó del cigarrillo en Yom Tov, por temor a que salten con ella chispas de fuego, y de cualquier modo esto no procede de la ley principal."),
 ("ז", "מִי שֶׁאֵינוֹ מְעַשֵּׁן בְּיוֹם טוֹב מֵחֲמַת שֶׁסָּבוּר שֶׁהַדָּבָר אָסוּר עַל פִּי הַהֲלָכָה, אָסוּר לוֹ גַּם לְטַלְטֵל אֶת הַסִּיגַרְיוֹת כְּדֵי לִיתְּנָם לַחֲבֵירוֹ הַמְּעַשֵּׁן. אוּלָם אִם אֵינוֹ מְעַשֵּׁן בִּגְלַל חֻמְרָא, וְיוֹדֵעַ שֶׁמֵּעִיקַּר הַדִּין מוּתָּר לְעַשֵּׁן בְּיוֹם טוֹב, מוּתָּר לוֹ גַּם לְטַלְטֵל אֶת הַסִּיגַרְיוֹת לִיתְּנָם לַחֲבֵירוֹ.",
  "Quien no fuma en Yom Tov porque cree que está prohibido según la halajá, tiene prohibido también trasladar los cigarrillos para dárselos a su compañero que sí fuma. Pero si no fuma por una estrictez personal, y sabe que según la ley principal está permitido fumar en Yom Tov, le está permitido también trasladar los cigarrillos para dárselos a su compañero."),
 ("ח", "מוּתָּר לְהַדְלִיק נֵר בְּיוֹם טוֹב כְּדֵי שֶׁיִּהְיֶה מוּכָן לְהִשְׁתַּמֵּשׁ מִמֶּנּוּ בְּיוֹם טוֹב לְבִישּׁוּל וּלְעִישּׁוּן סִיגַרְיָה וְכַדּוֹמֶה.",
  "Está permitido encender una vela en Yom Tov para que esté lista para usarla en Yom Tov para cocinar y fumar un cigarrillo y similares."),
]

for letra, he, es in HALAJOT_B:
  BLOQUES.append({"t": "halaja", "letra": letra, "he": he, "es": es})

# ============================================================ PIE DE PÁGINA — anuncios (mismo pie que el 263)
BLOQUES.append({"t": "pie",
  "he": "לְעִלּוּי נִשְׁמַת: חנניה בר איז'ה, מרים בת שמחה-סוליקה בת עליה. לְעִלּוּי נִשְׁמַת: משה בן רג'ינה ז\"ל, בן בתיה כהן שאמו זצוק\"ל. יוסף בן רחל. לְזִיוּוּג הָגוּן: שרה שירה בת אילנה חיה, יעל בת זוהרה/רוזט, אשרת בת יונה, פנחס בן יונה. לְהַצְלָחַת: אסף ומשה נחשון בן שמחה, אלעד יאיר בן שמחה, רן בן הרה\"ג דוד צדוק שליט\"א.",
  "es": "En memoria de: Jananiá bar Izja, Miriam bat Simjá - Sulika bat Aliyá. En memoria de: Moshé ben Reyina, z”l, ben Bitiá Cohen —que su madre en paz descanse—. Yosef ben Rajel. Para un buen enlace: Sara Shira bat Ilana Jaya, Yael bat Zohara/Rozet, Osheret bat Yoná, Pinjás ben Yoná. Para el éxito de: Asaf y Moshé Najshón ben Simjá, Elad Yaír ben Simjá, Ran ben el Rab Gaón David Tzadok, shlitá."})

BLOQUES.append({"t": "pie",
  "he": "כְּמוֹ כֵן נִפְתַּחַת מַגְמָה לְתוֹשָׁבֵי הַמֶּרְכָּז וְהַצָּפוֹן לְלִמּוּדֵי שְׁחִיטָה, סת\"ם, נִקּוּר וּמִילָה, עִיּוּנִי וּמַעֲשִׂי, בְּשִׁתּוּף וְהַדְרָכָה שֶׁל \"מכון ברית אליהו\" בְּרֹאשׁוּת הרה\"ג נתנאל ספטי שליט\"א. לַבּוֹגְרִים תִּינָּתֵן תְּעוּדַת הַסְמָכָה מֻכֶּרֶת עַל יְדֵי הָרַבָּנוּת הָרָאשִׁית. הָרִשּׁוּם בְּוָצְאָפּ 054-6455-403 אוֹ בְּמַייל. וְלַמְפֻורְסָמוֹת אֵין צָרִיךְ רְאָיָה...",
  "es": "Asimismo se abre, con la ayuda de Dios, una especialidad para los residentes del centro y del norte para estudios de <i>shejitá</i> [matanza ritual], STaM [escritura sagrada], <i>nikur</i> [desvenado] y <i>milá</i> [circuncisión], teórica y práctica, en colaboración y con la guía del «Instituto Brit Eliyahu», presidido por el Rab Gaón Netanel Sapeti, shlitá. Los graduados recibirán un título de acreditación reconocido por el Gran Rabinato. La inscripción por WhatsApp al 054-6455-403 o por correo. Y lo notorio no necesita prueba..."})
