# -*- coding: utf-8 -*-
"""El relato largo: Shminí Atzéret y Simjat Torá 5738 — el infarto del Rebe.
Primera parte: introducción hasta el kidush en la sucá."""

BLOQUES = []

BLOQUES.append({"t": "titulo",
  "he": "שְׁמִינִי עֲצֶרֶת וְשִׂמְחַת תּוֹרָה תשל\"ח",
  "es": "Shminí Atzéret y Simjat Torá de 5738"})

BLOQUES.append({"t": "par",
  "he": "שְׁמִינִי עֲצֶרֶת וְשִׂמְחַת תּוֹרָה תשל\"ח, הָיוּ הֶחָגִים הַמְּתוּחִים בְּיוֹתֵר בְּקֶרֶב עֲדַת הַחֲסִידִים בְּבֵית חַיֵּינוּ, לְאַחַר שֶׁבַּעֲיצוּמָן שֶׁל הַהַקָּפוֹת בְּלֵיל שְׁמִינִי עֲצֶרֶת, עָבַר הָרַבִּי הֶתְקֵף לֵב קָשֶׁה. רוֹפְאִים הוּזְעֲקוּ לְחַדְרוֹ שֶׁל הָרַבִּי, אוּלָם הָרַבִּי סֵירֵב לִנְסוֹעַ לְבֵית הָרְפוּאָה, וְנִשְׁאַר בְּחַדְרוֹ. בֵּין לְבֵין, עוֹדֵד הָרַבִּי אֶת הַחֲסִידִים וְדָרַשׁ לְהוֹסִיף עוֹד וָעוֹד בַּשִּׂמְחָה. בְּמְלֹאת אַרְבָּעִים שָׁנָה לְאֵירוּעֵי הַיָּמִים, מֵבִיא 'בֵּית מָשִׁיחַ' שְׂבִיבִים מֵאוֹתָן 48 שָׁעוֹת שֶׁל מֶתַח וַחֲרָדָה.",
  "es": "Shminí Atzéret y Simjat Torá de 5738 fueron las fiestas más tensas entre la comunidad jasídica de <i>Beit Jayenu</i> [«770»], después de que, en pleno apogeo de las <i>hakafot</i> en la noche de Shminí Atzéret, el Rebe sufriera un grave ataque al corazón. Se llamó urgentemente a médicos a la habitación del Rebe, pero el Rebe se negó a ir al hospital y se quedó en su habitación. Mientras tanto, el Rebe animaba a los jasidim y pedía añadir más y más alegría. Al cumplirse cuarenta años de los sucesos de esos días, la publicación <i>Beit Mashíaj</i> trae fragmentos de aquellas 48 horas de tensión y angustia."})

BLOQUES.append({"t": "sub", "he": "תְּפִלָּה וְ'אַתָּה הַרְאֵתָ' - כְּרָגִיל", "es": "El rezo y «Atá Horeta» — como siempre"})

BLOQUES.append({"t": "par",
  "he": "בְּלֵיל שְׁמִינִי עֲצֶרֶת תשל\"ח, הַכֹּל הִתְנַהֵל תְּחִילָּה כְּרָגִיל. תְּפִלַּת עַרְבִית הֵחֵלָּה בִּזְמַנָּהּ, וּבְשָׁעָה 9:00 נִכְנַס הָרַבִּי לְהַקָּפוֹת. הָיוּ הַרְבֵּה יוֹתֵר אוֹרְחִים מֵאֲשֶׁר בְּשָׁנִים קוֹדְמוֹת, וְהַקָּהָל נֶאֱמַד בְּכַמָּה אַלְפֵי אִישׁ. כַּאֲשֶׁר הָרַבִּי נִכְנַס רָקְדוּ וְשָׁרוּ. בְּכָל הַדֶּרֶךְ לַבִּימָה הוֹרָה בְּיָדוֹ לְהַגְבִּיר אֶת הַשִּׁירָה וּכְשֶׁעָלָה לַבִּימָה פָּנָה לְעֵבֶר הַקָּהָל הָרָחָב וּמָחָא כַּפַּיִם בְּחֹזֶק בְּמֶשֶׁךְ כַּמָּה דַּקּוֹת. אַחַר-כָּךְ הִתְחִילוּ בַּאֲמִירַת פְּסוּקֵי \"אַתָּה הַרְאֵתָ\" וְכַמָּה וְכַמָּה פְּעָמִים מָחָא כַּפַּיִם בְּחֹזֶק רַב לְעוֹדֵד אֶת הַשִּׁירָה.",
  "es": "En la noche de Shminí Atzéret de 5738, todo transcurrió al principio con normalidad. La <i>tefilat arvit</i> comenzó a su hora, y a las 9:00 entró el Rebe a las <i>hakafot</i>. Había muchos más invitados que en años anteriores, y el público se estimaba en varios miles de personas. Cuando entró el Rebe, bailaron y cantaron. Durante todo el camino a la tarima indicó con la mano que aumentaran el canto, y cuando subió a la tarima se volvió hacia el amplio público y aplaudió con fuerza durante varios minutos. Después empezaron a decir los versículos de «Atá Horeta», y varias veces aplaudió con fuerza para animar el canto."})

BLOQUES.append({"t": "sub", "he": "הַקָּפָה רִאשׁוֹנָה עִם הרש\"ג - עֲדַיִין כְּרָגִיל", "es": "Primera hakafá con el Rashag — todavía como siempre"})

BLOQUES.append({"t": "par",
  "he": "אד\"ש נִתְכַּבֵּד בְּסֵפֶר-תּוֹרָה הָרִאשׁוֹן (הַקָּטָן) בְּהַקָּפָה הָרִאשׁוֹנָה, וְיָצָא לְהַקָּפָה כְּשֶׁהוּא הוֹלֵךְ לְאַט וְאַחֲרָיו גִּיסוֹ הרש\"ג וְזִקְנֵי אנ\"ש. רַבִּים עָמְדוּ קָרוֹב לַשְּׁבִיל בּוֹ עָבַר אד\"ש וְנִישְּׁקוּ אֶת הַסֵּפֶר-תּוֹרָה שֶׁבְּיָדוֹ כְּשֶׁהֵם מְאַחֲלִים \"דֶּערְלֶעבְּט אִיבֶּער אַ יָאר\", וְאד\"ש עוֹנֶה: \"גַּם אַתֶּם\".",
  "es": "El Rebe fue honrado con el primer rollo de la Torá (el pequeño) en la primera <i>hakafá</i>, y salió a la <i>hakafá</i> caminando despacio, y tras él su cuñado el Rashag y los ancianos de los <i>anash</i> [jasidim de Jabad]. Muchos se pararon cerca del camino por donde pasaba el Rebe y besaron el rollo de la Torá que tenía en la mano, deseándole en ídish «que lo vivas un año más», y el Rebe respondía: «también ustedes»."})

BLOQUES.append({"t": "par",
  "he": "כְּשֶׁהִגִּיעַ הרש\"ג, נֶעֱמַד אד\"ש בָּאֶמְצַע וְהִמְתִּין עַד שֶׁיַּגִּיעַ סֵפֶר-תּוֹרָה שֶׁל מָשִׁיחַ. כְּשֶׁהִגִּיעַ וְנֶעֱמַד לְיַד הַשֻּׁלְחָן הִנִּיחַ אד\"ש יָדוֹ הַיְמָנִית עַל כְּתֵפוֹ שֶׁל הרש\"ג, שֶׁהִנִּיחַ אַף הוּא יָדוֹ עַל כֶּתֶף אד\"ש, בְּיָד הַשְּׁנִיָּה הַסֵּפֶר-תּוֹרָה, וְהִתְחִילוּ לִרְקוֹד כְּשֶׁכָּל הַקָּהָל שָׁר אֶת נִיגּוּן הַהַקָּפוֹת. רָקְדוּ מֶשֶׁךְ זְמַן, וְאד\"ש הָיָה בְּהִתְלַהֲבוּת יוֹתֵר מֵהָרָגִיל, עַד שֶׁהרש\"ג נֶאֱלַץ לְהַפְסִיק וְאד\"ש תָּמַךְ בּוֹ.",
  "es": "Cuando llegó el Rashag, el Rebe se puso en medio y esperó a que llegara el rollo de la Torá de <i>Mashíaj</i>. Cuando llegó y se puso junto a la mesa, el Rebe puso su mano derecha sobre el hombro del Rashag, que también puso su mano sobre el hombro del Rebe, con el rollo de la Torá en la otra mano, y empezaron a bailar mientras todo el público cantaba el <i>nigún</i> de las <i>hakafot</i>. Bailaron un buen rato, y el Rebe estaba más entusiasmado de lo habitual, hasta que el Rashag se vio obligado a detenerse y el Rebe lo sostuvo."})

BLOQUES.append({"t": "sub", "he": "הַקָּפָה רְבִיעִית: הָרַבִּי מְבַקֵּשׁ אֶת הַכִּסֵּא", "es": "Cuarta hakafá: el Rebe pide la silla"})

BLOQUES.append({"t": "par",
  "he": "גַּם הַהַקָּפָה הַשְּׁנִיָּה וְהַשְּׁלִישִׁית הָיוּ עֲדַיִין כְּרָגִיל. רַק בְּהַקָּפָה הָרְבִיעִית, אד\"ש הִסְתּוֹבֵב לְעֵבֶר הַקָּהָל וּמָחָא כַּפַּיִם לֹא בְּחֹזֶק - כַּפּוֹת הַיָּדַיִם בְּקוֹשִׁי נוֹגְעוֹת זוֹ בָּזוֹ - כְּשֶׁיָּדוֹ הַשְּׂמָאלִית נִשְׁעֶנֶת עַל הַסְּטֶנְדֶּר, לְמֶשֶׁךְ זְמַן קָצָר לְפִי עֵרֶךְ. פָּנָיו שֶׁל אד\"ש נִשְׁתַּנּוּ לְחִיוְורִים כְּסִיד וּפָנָה אֶל הַמַּזְכִּיר הרב גרונר וְאָמַר: \"גִיב מִיר מַיין בֵּיינְקְל\" [הָבֵא לִי אֶת הַכִּסֵּא]. אד\"ש הִתְיַישֵּׁב וְקֵירֵב אֵלָיו אֶת הַסִּידּוּר. כְּשֶׁיָּשַׁב נִשְׁעַן עַל הַמִּשְׁעֶנֶת וְעָצַם עֵינָיו וְנִרְאָה הָיָה שֶׁסּוֹבֵל כְּאֵבִים.",
  "es": "También la segunda y la tercera <i>hakafá</i> transcurrieron todavía con normalidad. Solo en la cuarta <i>hakafá</i>, el Rebe se volvió hacia el público y aplaudió sin fuerza —las palmas apenas se tocaban entre sí—, con la mano izquierda apoyada en el atril, durante un tiempo relativamente corto. El rostro del Rebe se volvió pálido como la cal, y se dirigió al secretario, el Rab Groner, y dijo: «dame mi silla». El Rebe se sentó y acercó hacia sí el <i>sidur</i>. Al sentarse se apoyó en el respaldo y cerró los ojos, y parecía que sufría dolores."})

BLOQUES.append({"t": "sub", "he": "מַיִם, מַיִם!", "es": "¡Agua, agua!"})

BLOQUES.append({"t": "par",
  "he": "הרב גרונר הִזְעִיק אֶת אֶחָד הָרוֹפְאִים שֶׁעָמַד לְיַד הַבִּימָה וְהַד\"ר אָמַר שֶׁיָּבִיאוּ מַיִם. צָעֲקוּ שֶׁיָּבִיאוּ מַיִם. הַמַּזְכִּיר הרב בנימין קליין הוֹשִׁיט לְאד\"ש סֵפֶל מַיִם אַךְ אד\"ש לֹא רָצָה לִשְׁתּוֹת, וּבִכְלָל לֹא רָצָה שֶׁהָרוֹפֵא יִבְדּוֹק אֶת הַדּוֹפֶק. הַקָּהָל הָיָה בְּמֶתַח הִיסְטֵרִי. צָעֲקוּ לְהִתְרַחֵק מֵהַבִּימָה וְלָצֵאת מִבֵּיהַכְנֶ\"ס כְּדֵי שֶׁיִּהְיֶה אֲוִויר יוֹתֵר מְרֻוָּוח. תּוֹךְ דַּקּוֹת אֲחָדוֹת הִתְרוֹקֵן כִּמְעַט כָּל בֵּיהַכְנֶ\"ס. נִשְׁאֲרוּ פָּחוֹת מִמֵּאָה אִישׁ. גַּם עֶזְרַת נָשִׁים הִתְרוֹקְנָה וְנִפְרְצוּ הַחַלּוֹנוֹת שָׁם בִּכְדֵי שֶׁיִּכָּנֵס דַּרְכָּם אֲוִויר צַח וְקָרִיר.",
  "es": "El Rab Groner llamó a uno de los médicos que estaba junto a la tarima, y el doctor dijo que trajeran agua. Gritaron que trajeran agua. El secretario Rab Binyamín Klein le acercó al Rebe un vaso de agua, pero el Rebe no quiso beber, y en general no quiso que el médico le tomara el pulso. El público estaba en tensión histérica. Gritaron que se alejaran de la tarima y salieran de la sinagoga para que hubiera más aire. En pocos minutos se vació casi toda la sinagoga. Quedaron menos de cien personas. También se vació la sección de mujeres, y rompieron allí las ventanas para que entrara por ellas aire fresco y fresco."})

BLOQUES.append({"t": "sub", "he": "הַקָּפָה חֲמִישִׁית וְשִׁישִּׁית - מְהִירוּת", "es": "Quinta y sexta hakafá — rapidez"})

BLOQUES.append({"t": "par",
  "he": "לְהַקָּפָה הַחֲמִישִׁית קָם אד\"ש מִכִּסְאוֹ וּמָחָא כַּפַּיִם מֶשֶׁךְ זְמַן קָצָר (לְפִי נוּסְחָא אַחַת, נֶעֶרְכָה גַּם הַהַקָּפָה הַזּוֹ - כְּמוֹ הַשִּׁישִּׁית - בִּמְהִירוּת, לְלֹא שִׁירָה וְרִיקּוּד) וְאַחֲרֶיהָ הִתְיַישֵּׁב. אֶת הַהַקָּפָה הַשִּׁישִּׁית עָרְכוּ בְּשֶׁקֶט, בְּלִי שִׁירָה וְרִיקּוּד, כְּדֵי שֶׁאד\"ש לֹא יִצְטָרֵךְ לָקוּם.",
  "es": "Para la quinta <i>hakafá</i> se levantó el Rebe de su silla y aplaudió un rato breve (según una versión, esta <i>hakafá</i> también, como la sexta, se hizo con rapidez, sin canto ni baile) y después se sentó. La sexta <i>hakafá</i> la hicieron en silencio, sin canto ni baile, para que el Rebe no tuviera que levantarse."})

BLOQUES.append({"t": "sub", "he": "הַקָּפָה הַשְּׁבִיעִית - עִם הרש\"ג", "es": "Séptima hakafá — con el Rashag"})

BLOQUES.append({"t": "par",
  "he": "לְהַקָּפָה הַשְּׁבִיעִית קָם אד\"ש מִכִּסְאוֹ. הִצִּיעוּ שֶׁיַּעַרְכוּ אֶת הַהַקָּפָה לְיַד הַבִּימָה שֶׁלּוֹ אַךְ אד\"ש מֵיאֵן, קִיבֵּל אֶת הַסֵּפֶר-תּוֹרָה הַקָּטָן מִיָּדֵי הרב בנימין אלטהויז וְהָלַךְ עִמּוֹ, בְּאִיטִּיּוּת וּבְפָנִים חִיוְורוֹת, לִמְקוֹם הַהַקָּפוֹת בְּמֶרְכַּז בֵּיהַכְנֶ\"ס. הָיוּ כָּאֵלּוּ שֶׁרָצוּ לְנַשֵּׁק אֶת הַסֵּפֶר-תּוֹרָה אַךְ הַמַּזְכִּיר הרב גרונר, שֶׁצָּעַד לִפְנֵי אד\"ש, מָנַע זֹאת מֵהֶם כְּדֵי שֶׁיִּסְתַּיֵּים מַהֵר. אַחֲרֵי אד\"ש הָלַךְ הרש\"ג לְבִימַת הַהַקָּפוֹת. אד\"ש הֵחֵל לִרְקוֹד עִמּוֹ מְעַט אַךְ הרש\"ג הִפְסִיק מִיָּד. כְּשֶׁהִפְסִיק חִיֵּיךְ אד\"ש וְעָשָׂה תְּנוּעָה שֶׁל תְּמִיהָה. הַהַקָּפָה הַזּוֹ נִמְשְׁכָה בְּעֵרֶךְ דַּקָּה. הָיָה נִרְאֶה כְּאִילּוּ אד\"ש צָרִיךְ שֶׁיֹּאחֲזוּ בּוֹ וְהרב גרונר נִיסָּה לַעֲשׂוֹת זֹאת, אֲבָל אד\"ש לֹא הִסְכִּים.",
  "es": "Para la séptima <i>hakafá</i> se levantó el Rebe de su silla. Propusieron hacer la <i>hakafá</i> junto a su tarima, pero el Rebe se negó; recibió el rollo de la Torá pequeño de manos del Rab Binyamín Altheus y caminó con él, despacio y con el rostro pálido, hasta el lugar de las <i>hakafot</i>, en el centro de la sinagoga. Hubo quienes quisieron besar el rollo de la Torá, pero el secretario Rab Groner, que caminaba delante del Rebe, se lo impidió para que terminara rápido. Detrás del Rebe caminó el Rashag hasta la tarima de las <i>hakafot</i>. El Rebe empezó a bailar un poco con él, pero el Rashag se detuvo enseguida. Al detenerse, el Rebe sonrió e hizo un gesto de extrañeza. Esta <i>hakafá</i> duró aproximadamente un minuto. Parecía que el Rebe necesitaba que lo sostuvieran, y el Rab Groner intentó hacerlo, pero el Rebe no aceptó."})

BLOQUES.append({"t": "sub", "he": "הָרַבִּי עוֹלֶה לְחַדְרוֹ", "es": "El Rebe sube a su habitación"})

BLOQUES.append({"t": "par",
  "he": "אַחֲרֵי הַתְּפִילָּה אָמַר ג' פְּעָמִים \"גוּט יוֹם טוֹב\" (בְּקוֹל דַּי חַלָּשׁ) כְּשֶׁהוּא מֵנִיף שְׁתֵּי יָדָיו וּמֵנִיעַ כָּל גּוּפוֹ. אַחַר-כָּךְ הִתְחִיל לָשִׁיר \"וְשָׂמַחְתָּ\" וּבְדַרְכּוֹ לָצֵאת מִבֵּיהַכְנֶ\"ס רָמַז בְּיָדוֹ לְהַגְבִּיר אֶת הַשִּׁירָה. כְּשֶׁהִגִּיעַ לַמַּדְרֵגוֹת רָצוּ לַעֲזוֹר לוֹ אַךְ דָּחָה אֶת הָעֶזְרָה. כְּשֶׁנִּכְנַס אד\"ש לְחַדְרוֹ נִשְׁעַן פִּתְאוֹם עַל הַקִּיר. הרב חודקוב שֶׁהָיָה עִמּוֹ פָּחַד מִזֶּה וְאָמַר לוֹ אד\"ש שֶׁיֵּלֵךְ לְ\"מֶרְכָּז\" (חֶדֶר הַמַּזְכִּירוּת) וְלֹא יִשָּׁאֵר בְּחַדְרוֹ.",
  "es": "Después de la <i>tefilá</i> dijo tres veces «<i>gut yom tov</i>» (con voz bastante débil) mientras alzaba las dos manos y movía todo el cuerpo. Después empezó a cantar «<i>Vesamajtá</i>», y de camino a salir de la sinagoga hizo un gesto con la mano para aumentar el canto. Al llegar a las escaleras quisieron ayudarlo, pero rechazó la ayuda. Cuando el Rebe entró en su habitación, de pronto se apoyó en la pared. El Rab Jodakov, que estaba con él, se asustó de esto, y el Rebe le dijo que fuera al «centro» (la oficina de la secretaría) y no se quedara en su habitación."})

BLOQUES.append({"t": "sub", "he": "הָרַבִּי פּוֹתֵחַ וּמַרְגִּיעַ", "es": "El Rebe abre y tranquiliza"})

BLOQUES.append({"t": "par",
  "he": "אַחֲרֵי זְמַן יָרְדָה מִקּוֹמָה שְׁלִישִׁית גִּיסָתוֹ, אֵשֶׁת הרש\"ג, וְדָפְקָה עַל הַדֶּלֶת, וּכְשֶׁלֹּא נִפְתְּחָה מִיָּד דָּפְקָה חָזָק וְצָעֲקָה אֶת שֵׁם אד\"ש (הַשֵּׁנִי) פַּעֲמַיִים \"... עֶפֶען אוֹיף\" [תִּפְתַּח]. אד\"ש פָּתַח וְהִיא שָׁאֲלָה \"מָה נִשְׁמָע?\". אד\"ש אָמַר לָהּ שֶׁהַשָּׁבוּעַ לֹא יָשַׁן וְכָל הַיּוֹם עָמַד וְחִילֵּק לֶעקָאח, \"אִיךְ הָאבּ נִיט געגעסען אַ גַאנְצֶן טָאג און נִיט געשלָאפֶן\" [לֹא אָכַלְתִּי כָּל הַיּוֹם, וְלֹא יָשַׁנְתִּי], אֲבָל הַלַּיְלָה יָנוּחַ וּבְעֶזְרַת הַשֵּׁם מָחָר יִהְיֶה סֵדֶר רָגִיל.",
  "es": "Al cabo de un rato bajó del tercer piso su cuñada, la esposa del Rashag, y llamó a la puerta, y cuando no se abrió enseguida llamó fuerte y gritó el segundo nombre del Rebe dos veces: «...ábrelo». El Rebe abrió, y ella preguntó: «¿qué se oye?». El Rebe le dijo que esa semana no había dormido y todo el día había estado de pie repartiendo <i>lekaj</i> [pastel de miel], «no comí en todo el día, y no dormí», pero que esa noche descansaría y, con la ayuda de Dios, al día siguiente sería un orden normal."})

BLOQUES.append({"t": "sub", "he": "קִידּוּשׁ בַּסוּכָּה", "es": "Kidush en la sucá"})

BLOQUES.append({"t": "par",
  "he": "הָרוֹפְאִים בִּיקְּשׁוּ שֶׁיֹּאכַל וְיִשְׁתֶּה בְּחַדְרוֹ אַךְ אד\"ש שָׁלַל זֹאת בְּאוֹמְרוֹ שֶׁלֹּא יֹאכַל לִפְנֵי קִידּוּשׁ וּמִחוּץ לַסוּכָּה. כְּשֶׁאֶחָד הָרוֹפְאִים אָמַר שֶׁהַהֲלִיכָה לַסוּכָּה תַּקְשֶׁה עָלָיו, אָמַר אד\"ש: אֵיךְ יָכוֹל אֲנִי לְהַשְׁאִיר אֶת הָרַבָּנִית לְבַדָּהּ כָּל הַלַּיְלָה, אִם לֹא אֶעֱשֶׂה קִידּוּשׁ עֲבוּרָהּ הִיא לֹא תֹּאכַל. בְּחַדְרוֹ שָׁהָה אד\"ש כְּעֶשֶׂר דַּקּוֹת וְאַחַר-כָּךְ יָצָא מִשָּׁם, לָבוּשׁ מְעִיל, בִּכְדֵי לְהִכָּנֵס לַסוּכָּה. הַקָּהָל עָמַד מֵרָחוֹק, מֵעֵבֶר לְ\"סֶרְוִויס-לַיין\", וּכְשֶׁנִּרְאָה אד\"ש יוֹצֵא הִתְחִילוּ לָשִׁיר. אַחַר-כָּךְ נִכְנְסָה לַסוּכָּה הָרַבָּנִית (הִיא הָיְתָה בַּבַּיִת שֶׁבִּרְחוֹב פְּרֶזִידֶנְט וּבְמַהֲלַךְ הַהַקָּפוֹת רָצוּ לְהוֹדִיעַ לָהּ. לְ-770 הִגִּיעָה דֶּרֶךְ רְחוֹב יוּנְיוֹן).",
  "es": "Los médicos pidieron que comiera y bebiera en su habitación, pero el Rebe lo rechazó diciendo que no comería antes del <i>kidush</i> y fuera de la <i>sucá</i>. Cuando uno de los médicos dijo que caminar hasta la <i>sucá</i> le sería difícil, el Rebe dijo: ¿cómo puedo dejar sola toda la noche a la Rebetzin? Si no hago <i>kidush</i> para ella, ella no comerá. En su habitación estuvo el Rebe unos diez minutos, y después salió de allí, vestido con abrigo, para entrar en la <i>sucá</i>. El público estaba parado a lo lejos, más allá de la línea de servicio, y cuando vieron salir al Rebe empezaron a cantar. Después entró en la <i>sucá</i> la Rebetzin (ella estaba en la casa de la calle President, y durante las <i>hakafot</i> quisieron avisarle; llegó a «770» por la calle Union)."})

BLOQUES.append({"t": "sub", "he": "קִידּוּשׁ עַל יַיִן דַּווְקָא", "es": "Kidush precisamente sobre vino"})

BLOQUES.append({"t": "par",
  "he": "לַסוּכָּה נִכְנְסוּ גַּם הָרוֹפְאִים וְאֶחָד הַמַּזְכִּירִים. כְּשֶׁנִּכְנַס אד\"ש לַסוּכָּה יָשַׁב וְהִשְׁעִין רֹאשׁוֹ עַל יָדוֹ. הִכְנִיסוּ לְשָׁם אֹכֶל וּמִיץ-עֲנָבִים אַךְ אד\"ש אָמַר: \"קִידּוּשׁ מַאכְט מֶען אוֹיף וַויין, נִיט אוֹיף גְרֵייפּ-דְשׁוּס!\". אד\"ש קִידֵּשׁ עַל יַיִן וְאַחֲרֵי זֶה אָכַל לֶעקָאח. אַחַר-כָּךְ נָטַל יָדָיו וְאָכַל חַלָּה אוֹתָהּ טָבַל בְּמֶלַח שֶׁהָיָה נָתוּן בְּכַף עַל הַשֻּׁלְחָן. אָכַל סְעוּדָּה קְטַנָּה וּבֵירַךְ בִּרְכַּת הַמָּזוֹן. בִּיצִיאָתוֹ, עוֹדֵד בְּיָדוֹ אֶת שִׁירַת הַקָּהָל.",
  "es": "En la <i>sucá</i> entraron también los médicos y uno de los secretarios. Cuando el Rebe entró en la <i>sucá</i>, se sentó y apoyó la cabeza en la mano. Le llevaron comida y jugo de uvas, pero el Rebe dijo: «el <i>kidush</i> se hace sobre vino, no sobre jugo de uva». El Rebe hizo <i>kidush</i> sobre vino, y después comió <i>lekaj</i>. Después se lavó las manos y comió <i>jalá</i>, que mojó en sal que había puesta en una cuchara sobre la mesa. Comió una comida pequeña y bendijo el <i>birkat hamazón</i>. Al salir, animó con la mano el canto del público."})
