# -*- coding: utf-8 -*-
"""Tercera parte del relato: el Dr. Weiss, la Hitvaadut, y el segundo día."""

BLOQUES = []

BLOQUES.append({"t": "sub", "he": "הַדּוֹקְטוֹר וַוייס מַגִּיעַ", "es": "Llega el doctor Weiss"})

BLOQUES.append({"t": "par",
  "he": "בְּמַהֲלַךְ הַתְּפִילָּה הִגִּיעַ הַד\"ר וַוייס מִשִּׁיקָגוֹ, שֶׁאַף הֵבִיא עִמּוֹ כַּמָּה מַכְשִׁירִים מִבֵּית-הָרְפוּאָה שֶׁלּוֹ, שֶׁבְּאֶמְצָעוּתָם יוּכְלוּ שָׁם לִבְדֹּק אֶת תּוֹצְאוֹת הַבְּדִיקוֹת שֶׁיַּעֲשֶׂה כָּאן. מְסַפְּרִים שֶׁכַּאֲשֶׁר הִגִּיעַ לְ-770 פָּרַץ בִּבְכִי וְאָמַר: תָּמִיד יָדַעְנוּ שֶׁאד\"ש מְחוֹלֵל נִסִּים וְנִפְלָאוֹת לַחוֹלִים וְכוּ', וַאֲנִי בְּעַצְמִי נוֹכַחְתִּי בְּכָךְ כְּשֶׁטִּיפַּלְתִּי בְּכַמָּה רוֹפְאִים שֶׁאד\"ש שָׁלַח אֵלַי לְהִתְרַפְּאוּת, אַךְ כָּעֵת עָלַי לָבוֹא וּלְרַפְּאוֹת אֶת אד\"ש. כְּשֶׁנִּכְנַס לַחֶדֶר אָמַר לוֹ אד\"ש שֶׁרוֹצֶה שֶׁיְּטַפֵּל בּוֹ כְּמוֹ בְּכָל פַּצְיֶנְט רָגִיל.",
  "es": "Durante la <i>tefilá</i> llegó el Dr. Weiss de Chicago, que trajo consigo varios aparatos de su hospital, con los cuales podrían allí examinar los resultados de los análisis que haría aquí. Cuentan que cuando llegó a 770 rompió a llorar y dijo: siempre supimos que el Rebe obra milagros y maravillas para los enfermos, etc., y yo mismo lo presencié cuando traté a varios médicos que el Rebe me envió para curarse, pero ahora tengo que venir yo a curar al Rebe. Al entrar en la habitación, el Rebe le dijo que quería que lo tratara como a cualquier paciente normal."})

BLOQUES.append({"t": "par",
  "he": "מְסַפְּרִים שֶׁעֶצֶם הַגָּעָתוֹ שֶׁל הַד\"ר וַוייס גָּרְמָה לְאד\"ש לִהְיוֹת בְּמַצַּב-רוּחַ מְרוֹמָם. הַד\"ר וַוייס אָמַר שֶׁאָמְנָם קָשֶׁה לְטַפֵּל בְּחוֹלֶה כְּשֶׁאֵינוֹ בְּבֵית-הָרְפוּאָה, אֲבָל זֶה אֶפְשָׁרִי. עַל עַצְמוֹ אָמַר שֶׁאֵינוֹ רוֹפֵא גָּדוֹל, אֲבָל יוֹדֵעַ מַהוּ \"רַבִּי\" וְלָכֵן מְקַוֶּוה שֶׁיּוּכַל לָתֵת אֶת הַטִּפּוּל הַטּוֹב בְּיוֹתֵר. הוּא אָמַר שֶׁיִּישָּׁאֵר לְיַד אד\"ש עַד אֲשֶׁר יַבְרִיא. הוּא אַף אָמַר שֶׁיֵּשׁ לִשְׁמוֹעַ לְדַעַת אד\"ש וּלְאַפְשֵׁר לוֹ לְהִשָּׁאֵר בְּחַדְרוֹ, וּמָנָה כַּמָּה מַעֲלוֹת בְּכָךְ: כָּאן יִהְיֶה הַטִּפּוּל עִם רוֹפֵא צָמוּד, אד\"ש יוּכַל לְהַבִּיעַ דַּעְתּוֹ עַל הַטִּפּוּל וְגַם לֹא יִצְטַעֵר מֵהָרִיחוּק מֵהַחֲסִידִים.",
  "es": "Cuentan que la sola llegada del Dr. Weiss hizo que el Rebe tuviera un ánimo elevado. El Dr. Weiss dijo que si bien es difícil tratar a un enfermo cuando no está en el hospital, es posible. Sobre sí mismo dijo que no es un gran médico, pero sabe qué es un «Rebe» y por eso espera poder dar el mejor tratamiento. Dijo que se quedaría junto al Rebe hasta que se curara. También dijo que había que escuchar la opinión del Rebe y permitirle quedarse en su habitación, y enumeró varias ventajas en ello: aquí el tratamiento sería con un médico permanente, el Rebe podría expresar su opinión sobre el tratamiento, y tampoco sufriría por el alejamiento de los jasidim."})

BLOQUES.append({"t": "sub", "he": "נְסִיעָה לְקְראוּן הַייטְס, עִם סְגַן הַמְּפַכ\"ל", "es": "Viaje a Crown Heights, con el subcomisario de policía"})

BLOQUES.append({"t": "par",
  "he": "לְיָמִים סִיפֵּר הַד\"ר וַוייס, שֶׁכְּשֶׁנָּחַת בִּשְׂדֵה הַתְּעוּפָה בְּנְיוּ יוֹרְק, לֹא הָיָה לוֹ מוּשָּׂג הֵיכָן שְׁכוּנַת קְראוּן הַייטְס. הוּא שׁוֹטֵט בִּנְמַל הַתְּעוּפָה, וּלְפֶתַע נִיגַּשׁ אֵלָיו שׁוֹטֵר מִמִּשְׁטְרַת נְיוּ יוֹרְק וְשׁוֹאֵל הַאִם הוּא ד\"ר אַיִירָה וַוייס מִשִּׁיקָאגוֹ? לְאַחַר שֶׁהֵשִׁיב בְּחִיּוּב, וְאָמַר שֶׁהוּא זָקוּק לְעֶזְרָה, הֵגִיב הַשּׁוֹטֵר וְאָמַר שֶׁהַשּׁוֹטְרִים הִתְבַּקְּשׁוּ לִמְצֹא אוֹתוֹ, וְהֵם מְקַבְּלִים אֶת פְּנֵי הַנּוֹסְעִים בְּכָל מָטוֹס הַמַּגִּיעַ מִשִּׁיקָאגוֹ, כְּשֶׁהֵם מְחַפְּשִׂים אָדָם שֶׁיָּכוֹל לִהְיוֹת ד\"ר וַוייס. סְגַן מְפַכ\"ל הַמִּשְׁטָרָה הִסִּיעַ אוֹתוֹ בְּשַׁיָּירָה לְקְראוּן הַייטְס, וְכָךְ הִגִּיעַ לְ-770 בִּמְהִירוּת שִׂיא.",
  "es": "Más tarde el Dr. Weiss contó que, al aterrizar en el aeropuerto de Nueva York, no tenía idea de dónde quedaba el barrio de Crown Heights. Anduvo dando vueltas por el aeropuerto, y de pronto se le acercó un agente de la policía de Nueva York y le preguntó si era el Dr. Ira Weiss de Chicago. Tras responder afirmativamente, y decir que necesitaba ayuda, el agente respondió que la policía había recibido la orden de encontrarlo, y que recibían a los pasajeros de cada vuelo procedente de Chicago, buscando a una persona que pudiera ser el Dr. Weiss. El subcomisario de policía lo trasladó en caravana hasta Crown Heights, y así llegó a 770 a máxima velocidad."})

BLOQUES.append({"t": "sub", "he": "הָרַבָּנִית מַרְגִּיעָה: \"אַל דְּאָגָה, ד\"ר וַוייס\"", "es": "La Rebetzin tranquiliza: «no te preocupes, Dr. Weiss»"})

BLOQUES.append({"t": "par",
  "he": "עַל פְּגִישָׁתוֹ עִם הָרַבָּנִית, סִיפֵּר הַד\"ר וַוייס: חָצִיתִי אֶת יָם הָאֲנָשִׁים, וְנִכְנַסְתִּי פְּנִימָה. אֲבָל אָז, נֶעֱצַרְתִּי עַל יְדֵי הָרַבָּנִית שְׁנֵיאוּרְסֹאהְן, אִשָּׁה עֲדִינָה וְאָדִיבָה בְּיוֹתֵר. אִשָּׁה פָּשׁוּט מַדְהִימָה. לֹא רָצִיתִי לִהְיוֹת בִּלְתִּי מְנוּמָּס, אֲבָל אָמַרְתִּי לָהּ: רֶעבֶּצִין, הָיִיתִי שָׂמֵחַ לְהַכִּירֵךְ, אוּלָם אֲנִי הָרֶגַע הִגַּעְתִּי מִשִּׁיקָגוֹ וּבִרְצוֹנִי לָרוּץ לְהִכָּנֵס )לָרַבִּי( מִיָּד. \"אַל דְּאָגָה, ד\"ר וַוייס\", אָמְרָה הָרַבָּנִית חַיָּה מוּשְׁקָא, \"יְדִידְךָ, ד\"ר טִישְׁהוֹלְץ הִגִּיעַ לְכָאן מִיָּד, וְהוּא סִידֵּר אֶת הָעִנְיָינִים\". \"בַּעֲלִי )'מַיין מַאן'( מְדַבֵּר, לַחַץ דָּמוֹ הִתְיַצֵּב, וְנִרְאֶה שֶׁהוּא נִמְצָא בְּמַצָּב חָדָשׁ\".",
  "es": "Sobre su encuentro con la Rebetzin, el Dr. Weiss contó: crucé el mar de gente y entré. Pero entonces, me detuvo la Rebetzin Schneerson, una mujer sumamente delicada y amable. Una mujer sencillamente asombrosa. No quería ser descortés, pero le dije: Rebetzin, me alegraría conocerla, pero acabo de llegar de Chicago y quiero correr a entrar (donde el Rebe) de inmediato. «No te preocupes, Dr. Weiss», dijo la Rebetzin Jaia Mushka, «tu amigo el Dr. Tishholtz llegó aquí enseguida, y él arregló los asuntos». «Mi esposo ('main man') habla, su presión sanguínea se estabilizó, y parece que está en un estado nuevo»."})

BLOQUES.append({"t": "sub", "he": "סוֹכְנוּת הַחֶלֶל מִתְגַּיֶּיסֶת לְמַעַן הָרַבִּי", "es": "La agencia espacial se moviliza por el Rebe"})

BLOQUES.append({"t": "par",
  "he": "ד\"ר טִישְׁהוֹלְץ, שֶׁהָיוּ לוֹ קְשָׁרִים רַבִּים בְּנְיוּ יוֹרְק, בֵּינֵיהֶם עִם נאס\"א )סוֹכְנוּת הַחֶלֶל הָאֲמֵרִיקָאִי(, הִצְלִיחַ לְהָבִיא לְ-770 עֲבוּר הָרַבִּי מַכְשִׁיר נִיטוּר לֵב אַלְחוּטִי. בַּיָּמִים הָהֵם, מִי שֶׁנִּזְקַק לְנִיטוּר לֵב הָיָה מְרוּתָק לְמִיטָּה וּמְחֻבָּר לְמַכְשִׁיר מְסֻרְבָּל עִם חוּטֵי חַשְׁמַל רַבִּים, אַךְ הוּא הִצְלִיחַ לְהַשִּׂיג אֶת הַמַּכְשִׁיר הָאַלְחוּטִי מִבָּסִיס נאס\"א.",
  "es": "El Dr. Tishholtz, que tenía numerosos contactos en Nueva York, entre ellos con la NASA (la agencia espacial estadounidense), logró traer a 770, para el Rebe, un monitor cardíaco inalámbrico. En aquellos días, quien necesitaba monitoreo cardíaco quedaba confinado a la cama y conectado a un aparato engorroso con numerosos cables eléctricos, pero él logró conseguir el aparato inalámbrico desde una base de la NASA."})

BLOQUES.append({"t": "sub", "he": "מַחְלֶקֶת הַמְּדִינָה בְּאַרה\"ב מְסַיַּיעַת", "es": "El Departamento de Estado de EE. UU. colabora"})

BLOQUES.append({"t": "par",
  "he": "אֶחָד הָרוֹפְאִים הָיָה ד\"ר בֶּרְנַרְד לֵאוֹן. לְיָמִים סִיפֵּר הַד\"ר וַוייס, כִּי לֵאוֹן עָסַק בְּאוֹתָהּ עֵת בְּפְרוֹיֶקְט מֶמְשַׁלְתִּי עִם מְדִינַת סִין, וּמַחְלֶקֶת הַמְּדִינָה שֶׁל אַרה\"ב הֵבִיאָה אוֹתוֹ בְּמְיוּחָד כְּדֵי לְטַפֵּל בָּרַבִּי. פְּקִידִים בְּמַחְלֶקֶת הַמְּדִינָה הִכִּירוּ בָּרַבִּי כְּמֻמְחֶה בְּבִיטָּחוֹן מְדִינִי, וְנָהֲגוּ לְהִתְיָיעֵץ אִתּוֹ. הָיָה חָשׁוּב לָהֶם שֶׁהָרַבִּי יִהְיֶה בָּרִיא.",
  "es": "Uno de los médicos era el Dr. Bernard León. Más tarde el Dr. Weiss contó que León estaba entonces trabajando en un proyecto gubernamental con el Estado de China, y el Departamento de Estado de EE. UU. lo trajo especialmente para atender al Rebe. Funcionarios del Departamento de Estado reconocían al Rebe como experto en seguridad política, y solían consultarlo. Para ellos era importante que el Rebe estuviera sano."})

BLOQUES.append({"t": "sub", "he": "הָרַבִּי: \"לָלֶכֶת לְשַׂמֵּחַ יְהוּדִים!\"", "es": "El Rebe: «¡ir a alegrar judíos!»"})

BLOQUES.append({"t": "par",
  "he": "אַחַר הַצָּהֳרַיִם הִתְקַבְּלָה הוֹרָאָה מֵאד\"ש שֶׁכּוּלָּם יֵלְכוּ לְבָתֵּי-כְּנֵסִיּוֹת וִישַׂמְּחוּ יְהוּדִים \"מִיט אַ שְׁטוֹרֶעם\". אד\"ש אָמַר שֶׁאֵלּוּ שֶׁרוֹצִים לַעֲשׂוֹת לְטוֹבַת בְּרִיאוּתוֹ שֶׁיֵּלְכוּ לְשַׂמֵּחַ יְהוּדִים. אַחַר הַצָּהֳרַיִם נִכְנַס לְחַדְרוֹ הָרַב שְׁלֹמֹה אַהֲרֹן קָזַרְנוֹבְסְקִי )יַחַד עִם הָרַב גְּרוֹנֶר(. כְּשֶׁנִּכְנַס אִיחֵל לְאד\"ש רְפוּאָה שְׁלֵמָה וּפָרַץ בִּבְכִי וְאד\"ש אָמַר לוֹ: הֲרֵי זוֹ סְתִירָה לְ'וְשָׂמַחְתָּ בְּחַגֶּיךָ', אִם רוֹצִים לְהוֹסִיף בִּבְרִיאוּתִי, הֲרֵי זֶה דַּווְקָא עַל יְדֵי שֶׁיַּרְבּוּ בְּשִׂמְחָה, בְּכִיּוֹת הֵן נֶגֶד רְצוֹנִי. וְנָתַן לוֹ שְׁנֵי בַּקְבּוּקֵי מַשְׁקֶה )שֶׁהִכְנִיסוּ אֵלָיו עוֹד בָּעֶרֶב הֶחָג( וְהוֹרָה שֶׁבַּלַּיְלָה תִּתְקַיֵּים הִתְווַעֲדוּת כָּרָגִיל, שֶׁבְּוַדַּאי לֹא יֶחְסְרוּ בָּהּ דִּבְרֵי תּוֹרָה, הִתְעוֹרְרוּת וְשִׂמְחָה, וְשֶׁאַחֲרֵי יַעַרְכוּ אֶת הַהַקָּפוֹת וְשֶׁיִּהְיוּ בְּשִׂמְחָה וְשֶׁלֹּא יִגָּרַע מִשִּׂמְחַת הֶחָג.",
  "es": "Por la tarde se recibió instrucción del Rebe de que todos fueran a las sinagogas y alegraran a los judíos «con estruendo» [<i>mit a shturem</i>]. El Rebe dijo que quienes quisieran hacer algo en favor de su salud fueran a alegrar judíos. Por la tarde entró en su habitación el Rab Shlomó Aharón Kazarnovsky (junto con el Rab Groner). Al entrar deseó al Rebe una curación completa y rompió a llorar, y el Rebe le dijo: esto contradice «Vesamajtá bejaguecha» [«te alegrarás en tu festividad»]; si quieren contribuir a mi salud, es precisamente aumentando la alegría, el llanto va contra mi voluntad. Y le dio dos botellas de licor (que le habían traído esa misma noche de la festividad) y ordenó que esa noche se celebrara la <i>hitvaadut</i> como de costumbre, que sin duda no faltaran en ella palabras de Torá, inspiración y alegría, y que después de ella hicieran las <i>hakafot</i> con alegría, sin que disminuyera la alegría de la festividad."})

BLOQUES.append({"t": "sub", "he": "הָרַבִּי מְדַבֵּר עִם הָרוֹפֵא עַל פְּעוּלַּת הַמַּזְרֵק", "es": "El Rebe habla con el médico sobre la acción de la jeringa"})

BLOQUES.append({"t": "par",
  "he": "כְּשֶׁאֶחָד הָרוֹפְאִים בָּא לָקַחַת בְּדִיקַת הַדָּם שָׁאַל אוֹתוֹ אד\"ש מָה גּוֹרֵם לִיצִיאַת הַדָּם, אִם דְּקִירַת הַמַּחַט אוֹ הָרֵיקָנוּת שֶׁנּוֹצֶרֶת בַּמַּזְרֵק. כְּשֶׁעָנָה הָרוֹפֵא שֶׁהָרֵיקָנוּת גּוֹרֶמֶת סִיפֵּר לוֹ אד\"ש שֶׁפַּעַם הִגִּיעַ אֵלָיו אֶחָד שֶׁטָּעַן עַל עַצְמוֹ שֶׁהוּא רֵיק וְאֵינוֹ שַׁיָּיךְ לְכְלוּם וְאד\"ש אָמַר לוֹ שֶׁאַדְּרַבָּה, הָרֵיקָנוּת מוֹשֶׁכֶת לְתוֹכָהּ בְּכוֹחַ חָזָק יוֹתֵר וּבְמֵילָא הֲרֵי הוּא כְּלִי לְכָל עִנְיָינֵי טוֹב וּקְדוּשָּׁה. וְסִיֵּים אד\"ש: בִּשְׁמִינִי-עֲצֶרֶת נוֹהֲגִים הָרַבָּנִים לוֹמַר \"סֶערְמַאנְס\" )נְאוּמִים( וּמִכֵּיוָן שֶׁאֵינֶנִּי מוּרְשֶׁה כָּעֵת לְדַבֵּר לַקָּהָל לָכֵן אָמַרְתִּי לְךָ מַה שֶּׁאָמַרְתִּי וְתִמְסוֹר זֹאת לִשְׁאָר.",
  "es": "Cuando uno de los médicos vino a tomarle una muestra de sangre, el Rebe le preguntó qué provoca la salida de la sangre: si el pinchazo de la aguja o el vacío que se crea en la jeringa. Cuando el médico respondió que era el vacío, el Rebe le contó que una vez llegó ante él alguien que se quejaba de que era vacío y no pertenecía a nada, y el Rebe le dijo que, al contrario, el vacío atrae hacia sí con más fuerza, y por lo tanto es un instrumento para todo asunto de bien y santidad. Y el Rebe concluyó: en Shminí Atzéret los rabinos acostumbran decir «sermones», y como ahora no tengo permiso para hablar al público, por eso te dije lo que te dije, y transmítelo a los demás."})

BLOQUES.append({"t": "par",
  "he": "אד\"ש הוֹרָה לרש\"ג – דֶּרֶךְ הַמַּזְכִּיר הָרַב גְּרוֹנֶר – שֶׁאֶת הַפְּסוּקִים מ\"אַתָּה הֶרְאֵתָ\" יִמְכְּרוּ הָעֶרֶב לְטוֹבַת יְשִׁיבַת תּוֹמְכֵי תְּמִימִים, כָּרָגִיל מִדֵּי שָׁנָה, בְּלִי שִׁינּוּיִים, וְאֶת הִשְׁתַּתְּפוּתוֹ יִתֵּן אד\"ש בְּדוֹלָרִים בּוֹדְדִים וְאֵלּוּ שֶׁיִּקְנוּ פָּסוּק יְקַבְּלוּ דּוֹלָר אֶחָד.",
  "es": "El Rebe ordenó al Rashag —a través del secretario Rab Groner— que los versículos de «Atá Hereitá» se vendieran esa noche a favor de la Ieshivá Tomjé Temimím, como cada año, sin cambios, y que su propia participación la daría el Rebe en dólares sueltos, y quienes compraran un versículo recibirían un dólar."})

BLOQUES.append({"t": "sub", "he": "הִתְווַעֲדוּת בְּהוֹרָאַת הָרַבִּי", "es": "Hitvaadut por orden del Rebe"})

BLOQUES.append({"t": "par",
  "he": "בְּשָׁעָה 9:00 הִתְקַיְּימָה הִתְווַעֲדוּת חֲסִידִית בְּהִשְׁתַּתְּפוּת זְקֵנֵי וּמַשְׁפִּיעֵי אַנ\"שׁ. הָרַב מָרְדֳּכַי מֶענְטְלִיק חָזַר עַל שִׂיחַת אד\"ש מִי\"ג תִּשְׁרֵי וְהָרַב יוֹאֵל כֹּהֵן לִימֵּד שִׂיחָה מִשׂמח\"ת. בְּהִתְווַעֲדוּת זוֹ חִילְּקוּ אֶת הַמַּשְׁקֶה שֶׁנָּתַן אד\"ש לָרַב קָזַרְנוֹבְסְקִי. הַכִּסֵּא שֶׁל אד\"ש נִיצָּב בִּמְקוֹמוֹ לְיַד שֻׁלְחַן הַהִתְווַעֲדוּת. בְּאֶמְצַע יָרַד הַד\"ר וַוייס שֶׁרָצָה לְהַגִּיד כַּמָּה מִילִּים בְּאִידִישׁ דַּווְקָא. הוּא בֵּירֵךְ אֶת אד\"ש וְאָמַר לַקָּהָל שֶׁהַמַּצָּב כְּבָר יוֹתֵר טוֹב.",
  "es": "A las 9:00 se celebró una <i>hitvaadut</i> jasídica con la participación de los ancianos e influyentes de <i>anash</i>. El Rab Mordejái Mentlik repitió la charla del Rebe del 13 de Tishrei y el Rab Ioel Cohen enseñó una charla de Simjat Torá. En esta <i>hitvaadut</i> repartieron la bebida que el Rebe había dado al Rab Kazarnovsky. La silla del Rebe estaba en su lugar junto a la mesa de la <i>hitvaadut</i>. A mitad de la reunión bajó el Dr. Weiss, que quiso decir unas palabras precisamente en ídish. Bendijo al Rebe y dijo al público que el estado ya era mejor."})

BLOQUES.append({"t": "par",
  "he": "בַּזְּמַן הַזֶּה שָׁאַל אד\"ש אֶת הַמַּזְכִּיר הָרַב גְּרוֹנֶר הַאִם הָלְכוּ לְשַׂמֵּחַ בְּבָתֵּי-כְּנֵסִיּוֹת וְעָנָה הַלָּה שֶׁכֵּן. אד\"ש הִמְשִׁיךְ לִשְׁאוֹל \"וָואס טוּט זִיךְ אוּנְטֶן? )בְּבֵית-הַכְּנֶסֶת(\" וְעָנָה שֶׁמִּתְוַעֲדִים הָחֵל מֵהַשָּׁעָה 9:00. שָׁאַל אד\"ש: \"מִיט אַ שְׁטוֹרֶעם?\" וְהוֹסִיף שֶׁיִּמְסוֹר שֶׁאָמַר שֶׁיִּתְווַעֲדוּ \"מִיט אַ גְּרוֹיסְן שְׁטוֹרֶעם\".",
  "es": "En ese momento el Rebe preguntó al secretario Rab Groner si habían ido a alegrar a las sinagogas, y este respondió que sí. El Rebe siguió preguntando: «¿qué pasa abajo (en la sinagoga)?», y le respondió que estaban en <i>hitvaadut</i> desde las 9:00. El Rebe preguntó: «¿con estruendo?», y añadió que transmitiera que había dicho que se congregaran «con gran estruendo»."})

BLOQUES.append({"t": "par",
  "he": "אַחֲרֵי הַהִתְווַעֲדוּת הִתְחִילוּ בִּמְכִירַת וַאֲמִירַת פְּסוּקֵי \"אַתָּה הֶרְאֵתָ\". בְּדֶרֶךְ כְּלָל נָהוּג שֶׁבַּלַּיְלָה זֶה מִתְכַּבֵּד אד\"ש לוֹמַר אֶת כָּל פְּסוּקֵי \"אַתָּה הֶרְאֵתָ\" בַּפַּעַם הָרִאשׁוֹנָה, וּבִשְׁנֵי הָאֲחֵרִים בְּפָסוּק רִאשׁוֹן וְאַחֲרוֹן. גַּם הַפַּעַם נָהֲגוּ כָּךְ וְכָל הַקָּהָל אָמַר פְּסוּקִים אֵלּוּ. אֶת הַפָּסוּק \"וּפָרַצְתָּ\" קָנוּ הַתְּמִימִים בְּסַךְ שֶׁל 770 דּוֹלָר.",
  "es": "Después de la <i>hitvaadut</i> comenzaron a vender y decir los versículos de «Atá Hereitá». Por lo general se acostumbra que esa noche el Rebe tenga el honor de decir todos los versículos de «Atá Hereitá» la primera vez, y en las otras dos, el primer y el último versículo. Esta vez también hicieron así, y todo el público dijo estos versículos. El versículo «Ufaratzta» lo compraron los <i>temimim</i> por la suma de 770 dólares."})

BLOQUES.append({"t": "sub", "he": "הַחֲסִידִים שָׁרִים: הָרַבִּי בָּרִיא!", "es": "Los jasidim cantan: ¡el Rebe está sano!"})

BLOQUES.append({"t": "par",
  "he": "אַחֲרֵי כָּל פַּעַם שֶׁסִּיְּימוּ אֶת \"אַתָּה הֶרְאֵתָ\" שָׁרוּ וְרָקְדוּ \"לְשֵׁם שִׂמְחַת יו\"ט\", לְאוֹר הוֹרָאַת אד\"ש שֶׁהַכֹּל יִתְנַהֵל כָּרָגִיל בְּלִי שִׁינּוּיִים. שָׁרוּ אֶת הַנִּיגּוּן \"זָאל שׁוֹין זַיין דִּי גְּאוּלָּה\" וְהֶחְלִיפוּ מִילִּים אֵלּוּ בְּמִילִּים \"דֶער רַבִּי זָאל געזוּנְט זַיין\" וְאַחַר-כָּךְ הֶחְלִיפוּ לַמְּלִים \"דֶער רַבִּי אִיז געזוּנְט\", וְכָךְ שָׁרוּ בְּמִילִּים אֵלּוּ בְּמֶשֶׁךְ שָׁעָה שְׁלֵמָה בְּרִיקּוּדִים. עֵינֵי כּוּלָּם אֲדוּמּוֹת מִבֶּכִי; לֹא הָיָה אִישׁ שֶׁלֹּא רָצָה לְהַנִּיחַ אֶת רֹאשׁוֹ עַל הַשֻּׁלְחָן וּלְמָרֵר בִּבְכִי; אֶלָּא שֶׁהָרַבִּי צִיווָּה לִרְקוֹד, וְכוּלָּם רָקְדוּ וּבָכוּ. רָקְדוּ וּבָכוּ. הָיוּ שֶׁהֶחְזִיקוּ בַּשֻּׁלְחָן וְהִקְפִּיצוּ עַצְמָם בְּכוֹחַ, הָעִיקָּר לִרְקוֹד...",
  "es": "Cada vez que terminaban «Atá Hereitá» cantaban y bailaban «lesheim simjat Yom Tov», siguiendo la instrucción del Rebe de que todo transcurriera como de costumbre, sin cambios. Cantaron la melodía «Zol shoin zain di Gueulá» y cambiaron esas palabras por «Der Rebe zol gezunt zain», y después las cambiaron por «Der Rebe iz gezunt», y así cantaron con estas palabras durante una hora entera bailando. Los ojos de todos estaban rojos de llanto; no hubo nadie que no quisiera apoyar la cabeza sobre la mesa y llorar amargamente; sino que el Rebe ordenó bailar, y todos bailaron y lloraron. Bailaron y lloraron. Había quienes se sujetaban de la mesa y se impulsaban con fuerza, lo principal era bailar..."})

BLOQUES.append({"t": "sub", "he": "הָרַבִּי עָמַד עַל רַגְלָיו, כְּדֵי לְשַׂמֵּחַ אֶת הַחֲסִידִים", "es": "El Rebe se puso de pie, para alegrar a los jasidim"})

BLOQUES.append({"t": "par",
  "he": "בְּאוֹתוֹ זְמַן קָם אד\"ש מִמִּיטָּתוֹ וְעָמַד עַל רַגְלָיו, וְאָמַר שֶׁעוֹשֶׂה זֹאת בִּכְדֵי שֶׁהָרַב גְּרוֹנֶר יוּכַל לִמְסוֹר לַקָּהָל שֶׁהוּא מַרְגִּישׁ טוֹב \"בְּאוֹפֶן גָּלוּי\". אֶחָד הָרוֹפְאִים אָמַר שֶׁאִם יָדְעוּ הַקָּהָל כַּמָּה נַחַת רוּחַ גָּרַם נִיגּוּן זֶה לְאד\"ש הָיוּ מְנַגְּנִים אוֹתוֹ כָּל הַזְּמַן. כְּשֶׁשָּׁמַע אֶת הַנִּיגּוּן הַנ\"ל אָמַר אד\"ש לָרוֹפֵא: \"דָאס אִיז חֲסִידִים\". כְּשֶׁשָּׁאֲלוּ אֶת אד\"ש הַאִם הָרַעַשׁ מֵהַשִּׁירָה אֵינוֹ מַפְרִיעַ לוֹ, וְעָנָה: \"עֶס אִיז אַ געשמַאקע מוּזִיק\" ]זוֹ מוּזִיקָה נְעִימָה[. בְּבֵית-הַכְּנֶסֶת נִמְשְׁכוּ הַהַקָּפוֹת עַד אוֹר הַבֹּקֶר. נוֹדַע שֶׁאד\"ש הִתְפַּלֵּל עַרְבִית, קִידֵּשׁ וְאָכַל מַשֶּׁהוּ.",
  "es": "En ese momento el Rebe se levantó de su cama y se puso de pie, y dijo que lo hacía para que el Rab Groner pudiera comunicar al público que se sentía bien «de manera visible». Uno de los médicos dijo que si el público supiera cuánta satisfacción le causó esta melodía al Rebe, la tocarían todo el tiempo. Al oír dicha melodía, el Rebe dijo al médico: «esto son los jasidim». Cuando le preguntaron al Rebe si el ruido del canto no le molestaba, respondió: «es una música agradable». En la sinagoga las <i>hakafot</i> continuaron hasta la luz de la mañana. Se supo que el Rebe rezó <i>Arvit</i>, hizo <i>Kidush</i> y comió algo."})

BLOQUES.append({"t": "sub", "he": "הָרַבִּי מוֹסֵר לָרַב גְּרוֹנֶר תֹּכֶן שִׂיחָה", "es": "El Rebe transmite al Rab Groner el contenido de una charla"})

BLOQUES.append({"t": "par",
  "he": "לְעֵרֶךְ בְּשָׁעָה 1–2 אַחֲרֵי חֲצוֹת הַלַּיְלָה אָמַר אד\"ש שִׂיחָה קְצָרָה לִפְנֵי הַמַּזְכִּיר הָרַב גְּרוֹנֶר וּבִיקְּשׁוֹ שֶׁיִּמְסוֹר אוֹתָהּ בְּהִתְווַעֲדוּת שֶׁל מָחָר )הַתֹּכֶן הוּא דְּבָרָיו הַנ\"ל לָרוֹפֵא בְּעִנְיַין הָרֵיקָנוּת, שֶׁכַּאֲשֶׁר יֵשׁ חִסָּרוֹן בְּעִנְיָין הֲרֵי זֶה יָכוֹל לְהִתְבַּטֵּא בִּשְׁנֵי אֳפָנִים: א. שֶׁכָּל הַדָּבָר )הָעִנְיָין( חָסֵר. ב. שֶׁחָסֵר בְּהָעִנְיָין )כְּלוֹמַר לֹא שֶׁהַדָּבָר חָסֵר אֶלָּא שֶׁיֶּשְׁנוֹ חִסָּרוֹן בַּדָּבָר )בְּהָעִנְיָין(( וְאָז זֶה מַכְרִיחַ תּוֹסֶפֶת וְתִגְבּוֹרֶת. וּבְדֻגְמַת שְׁאִיבַת הַדָּם וְהַהוֹרָאָה שֶׁאָמַר בָּזֶה לְאֶחָד בְּיֶחִידוּת שֶׁאִם מִישֶׁהוּ הוּא כְּלִי רֵיק הוּא שׁוֹאֵב יוֹתֵר כּוֹחוֹת מִנִּשְׁמָתוֹ וּבִיכוֹלְתּוֹ לְקַבֵּל. וּכְמוֹ-כֵן בְּעִנְיַין הַצִּמְצוּם שֶׁלְּצוֹרֶךְ הִתְהַוּוּת הָעוֹלָמוֹת הֲרֵי הַצִּמְצוּם הִכְרִיחַ אֶת עִנְיַין הַקָּו, וְהוֹסִיף, כֵּיוָון שֶׁיֶּשְׁנוֹ עִנְיַין דְּ\"יִפָּקֵד מוֹשָׁבְךָ\" )הַכַּוָּונָה, שֶׁאד\"ש לֹא יְהֵא נוֹכֵחַ בְּהִתְווַעֲדוּת(, לֹא צָרִיךְ לְהִגָּרֵם עַל יְדֵי זֶה גֵּרָעוֹן, כִּי-אִם אַדְּרַבָּה. אד\"ש אָמַר לָרַב גְּרוֹנֶר שֶׁיְּדַבֵּר עַל זֶה )\"דוּרְכְרֶעדְן\"( עִם הָרַב יוֹאֵל כֹּהֵן וְכֵן שֶׁיּוֹסִיף בָּזֶה מַרְאֵי-מְקוֹמוֹת וְכוּ'.",
  "es": "A eso de la 1–2 de la madrugada, el Rebe dijo una breve charla ante el secretario Rab Groner y le pidió que la transmitiera en la <i>hitvaadut</i> del día siguiente (el contenido es lo que había dicho antes al médico sobre el vacío: que cuando falta algo en un asunto, esto puede expresarse de dos maneras: a. que toda la cosa (el asunto) falta; b. que falta EN el asunto (es decir, no que la cosa falte, sino que hay una carencia en la cosa, en el asunto), y entonces esto obliga a un añadido y un refuerzo. Y a modo de ejemplo, la extracción de sangre, y la indicación que dio sobre esto a alguien en privado, de que si uno es un recipiente vacío, extrae más fuerzas de su alma y tiene mayor capacidad de recibir. Y asimismo en el tema del <i>tzimtzum</i> [contracción], que para la formación de los mundos el <i>tzimtzum</i> obligó el concepto del <i>kav</i> [la línea]. Y añadió que, dado que existe el concepto de «será echado en falta tu asiento» (es decir, que el Rebe no estaría presente en la <i>hitvaadut</i>), esto no debía causar una merma, sino todo lo contrario. El Rebe dijo al Rab Groner que hablara de esto con el Rab Ioel Cohen, y que añadiera referencias, etc."})

BLOQUES.append({"t": "sub", "he": "הָרַבִּי: \"אֲנִי נִמְצָא עִם הַקָּהָל לְמַטָּה\"", "es": "El Rebe: «yo estoy con el público, abajo»"})

BLOQUES.append({"t": "par",
  "he": "בְּיוֹם שׂמח\"ת הִתְקַיְּימָה תְּפִילַּת שַׁחֲרִית בְּמִנְיָין מְצוּמְצָם בְּגַן-עֵדֶן הַתַּחְתּוֹן. אד\"ש סָגַר אֶת דֶּלֶת חַדְרוֹ וְאָמַר: \"אִיךְ געפִין זִיךְ אוּנְטֶן\" )עִם הַמִּנְיָין שֶׁל כָּל הַקָּהָל(. לְ\"אַתָּה הֶרְאֵתָ\" נִכְנְסוּ אֲחָדִים לְחַדְרוֹ וְאד\"ש אָמַר פָּסוּק רִאשׁוֹן וְאַחֲרוֹן בִּשְׁלֹשֶׁת הַפְּעָמִים שֶׁל \"אַתָּה הֶרְאֵתָ\". בְּעֵת הַהַקָּפוֹת יָשַׁב עַל מִיטָּתוֹ וְאָחַז סֵפֶר-תּוֹרָה בְּיָדוֹ וּבִשְׁעַת הַהַקָּפוֹת בְּפוֹעַל הִקִּיף בְּיָדוֹ עִם הַסֵּפֶר-תּוֹרָה אֶת סִידּוּרוֹ שֶׁהָיָה מוּנָּח לְפָנָיו עַל הַשֻּׁלְחָן. בִּשְׁנֵי הַסִּפְרֵי-תּוֹרָה הָאֲחֵרִים הִקִּיפוּ אֶת הַסְּטֶנְדֶּר. בְּהַקָּפוֹת לֹא שָׁרוּ. בִּקְרִיאַת-הַתּוֹרָה עָלָה לְחָתָן בְּרֵאשִׁית. בְּעֵת אֲמִירַת קַדִּישׁ נִכְנַס הַד\"ר וַוייס וְהִצִּיעַ לְאד\"ש שֶׁיִּתְיַישֵּׁב. אד\"ש עָנָה לוֹ בְּחִיּוּךְ: אַחֲרֵי הַגְּבָּהָה. וְנִשְׁאַר עוֹמֵד עַד לְאַחֲרֵי הַגְבָּהַת הַסֵּפֶר-תּוֹרָה.",
  "es": "En el día de Simjat Torá se celebró <i>Shajarit</i> en un <i>minián</i> reducido en el Gan Edén inferior. El Rebe cerró la puerta de su habitación y dijo: «yo me encuentro abajo» (con el <i>minián</i> de todo el público). Para «Atá Hereitá» entraron algunos a su habitación, y el Rebe dijo el primer y el último versículo en las tres veces de «Atá Hereitá». Durante las <i>hakafot</i> se sentó en su cama y sostuvo un <i>Sefer Torá</i> en la mano, y en el momento efectivo de las <i>hakafot</i> rodeó con su mano, con el <i>Sefer Torá</i>, su <i>sidur</i> que estaba colocado ante él sobre la mesa. Con los otros dos <i>sifrei Torá</i> rodearon el atril. En las <i>hakafot</i> no cantaron. En la lectura de la Torá subió como novio de Bereshit. Durante el <i>kadish</i> entró el Dr. Weiss y propuso al Rebe que se sentara. El Rebe le respondió con una sonrisa: después de la <i>haghbá</i> [elevación del rollo]. Y permaneció de pie hasta después de la <i>haghbá</i> del <i>Sefer Torá</i>."})

BLOQUES.append({"t": "par",
  "he": "לְעֵרֶךְ בְּשָׁעָה 5:00 שָׁאַל אד\"ש אֶת הַמַּזְכִּיר הָרַב גְּרוֹנֶר מָה נַעֲשָׂה לְמַטָּה )בְּבֵית-הַכְּנֶסֶת( וְעָנָה הַלָּה שֶׁהַקָּהָל בְּשִׂמְחָה רַבָּה. אָמַר לוֹ אד\"ש: \"זָאג דֶעם עוֹלָם אַז אוֹיף ווַייטֶער זָאל זַיין מִיט נָאכְמֶער שְׁטוֹרֶעם\" ]תֹּאמַר לַקָּהָל, שֶׁלְּהַבָּא יִהְיֶה בְּיוֹתֵר 'שְׁטוֹרֶעם'[.",
  "es": "A eso de las 5:00, el Rebe preguntó al secretario Rab Groner qué se hacía abajo (en la sinagoga), y este respondió que el público estaba con gran alegría. El Rebe le dijo: «diles a la gente que de aquí en adelante sea con más estruendo»."})

BLOQUES.append({"t": "sub", "he": "הָרַבִּי שׁוֹלֵחַ אֶת גְּבִיעוֹ עִם בַּקְבּוּק יַיִן", "es": "El Rebe envía su copa con una botella de vino"})

BLOQUES.append({"t": "par",
  "he": "בְּהִתְווַעֲדוּת נָכְחוּ רֹב אַנ\"שׁ וְזִקְנֵי אַנ\"שׁ, נָשִׁים וִילָדִים וְכוּ'. הִתְוַועֲדוּ קוֹדֶם הַשְּׁקִיעָה וְהָרַב גְּרוֹנֶר מָסַר אֶת דִּבְרֵי אד\"ש. בְּסִיּוּם הַהִתְווַעֲדוּת, בְּשָׁעָה 11, בָּא הָרַב גְּרוֹנֶר עִם גְּבִיעוֹ שֶׁל אד\"ש )שֶׁבְּתוֹכוֹ קְצָת יַיִן( וּבַקְבּוּק יַיִן וְאָמַר שֶׁאד\"ש הוֹרָה לִמְסוֹר זֹאת לָרַב חוֹדָקוֹב לְחַלֵּק לְמִשְׁתַּתְּפֵי הַהִתְווַעֲדוּת. עוֹד אָמַר שֶׁאד\"ש אָמַר לוֹ לְהַכְרִיז הַכְרָזָה, אֲבָל אָמַר לוֹ \"דָאס זָאלְסְטוּ זַיי זָאגְן נָאךְ זַייעֶר מַעֲרִיב פָאר הַבְדָּלָה\" ]אֶת זֶה תֹּאמַר לָהֶם אַחֲרֵי שֶׁיִּתְפַּלְּלוּ עַרְבִית, לִפְנֵי הַבְדָּלָה[.",
  "es": "En la <i>hitvaadut</i> estuvieron presentes la mayoría de <i>anash</i> y los ancianos de <i>anash</i>, mujeres y niños, etc. Se congregaron antes de la puesta del sol, y el Rab Groner transmitió las palabras del Rebe. Al terminar la <i>hitvaadut</i>, a las 11, vino el Rab Groner con la copa del Rebe (que tenía un poco de vino) y una botella de vino, y dijo que el Rebe había ordenado entregarlo al Rab Jodakov para repartir entre los participantes de la <i>hitvaadut</i>. Dijo además que el Rebe le había dicho que hiciera un anuncio, pero le dijo: «esto se lo dirás después de que recen <i>Arvit</i>, antes de <i>Havdalá</i>»."})

BLOQUES.append({"t": "sub", "he": "שִׂיחָה רִאשׁוֹנָה אַחֲרֵי הָאִירוּעַ", "es": "Primera charla tras el evento"})

BLOQUES.append({"t": "par",
  "he": "אַחֲרֵי תְּפִילַּת עַרְבִית הוֹדִיעַ הָרַב גְּרוֹנֶר שֶׁאד\"ש יֹאמַר הָעֶרֶב שִׂיחָה בְּחַדְרוֹ הַקָּ', בְּאֶמְצָעוּת הָרַמְקוֹל, וְהַקָּהָל יוּכְלוּ לִשְׁמוֹעַ זֹאת בְּבֵית-הַכְּנֶסֶת לְמַטָּה. הָרוֹפְאִים נָתְנוּ לְאד\"ש רְשׁוּת לְדַבֵּר בְּמֶשֶׁךְ חָמֵשׁ דַּקּוֹת, אַךְ לְפוֹעַל הַשִּׂיחָה הִתְחִילָה בְּשָׁעָה 12:00 וְנִמְשְׁכָה 22 דַּקּוֹת )שִׂיחָה וּמַאֲמָר )כְּעֵין שִׂיחָה( ד\"ה \"לְהָבִין עִנְיַן שׂמח\"ת\"(. לִקְרַאת סִיּוּמָהּ, כְּשֶׁאָמַר אֶת הַבְּרָכוֹת, בָּכָה. כְּשֶׁשְּׁאָלוּהוּ הָרוֹפְאִים )שֶׁאֵינָם מְבִינִים אִידִישׁ( מָה דִּיבֵּר בְּעֵת שֶׁבָּכָה, עָנָה אד\"ש שֶׁבֵּירֵךְ אֶת הַחֲסִידִים וְדִיבֵּר בְּעִנְיַין מָשִׁיחַ. גַּם אַחֲרֵי הַשִּׂיחָה בָּכָה אד\"ש. הָרוֹפְאִים אָמְרוּ שֶׁמַּצַּב הַלֵּב לֹא הִשְׁתַּנָּה כְּתוֹצָאָה מֵהַדִּיבּוּר.",
  "es": "Después de <i>Arvit</i>, el Rab Groner avisó que el Rebe diría esa noche una charla en su santa habitación, mediante un altavoz, y el público podría oírla en la sinagoga de abajo. Los médicos dieron permiso al Rebe para hablar durante cinco minutos, pero en la práctica la charla empezó a las 12:00 y duró 22 minutos (una charla y un discurso, a modo de charla, sobre «Para entender el tema de Simjat Torá»). Hacia su final, cuando dijo las bendiciones, lloró. Cuando los médicos (que no entienden ídish) le preguntaron qué había dicho mientras lloraba, el Rebe respondió que había bendecido a los jasidim y había hablado sobre el Mashíaj. También después de la charla el Rebe lloró. Los médicos dijeron que el estado del corazón no había cambiado como resultado de hablar."})

BLOQUES.append({"t": "par",
  "he": "הָרוֹפְאִים גַּם שְׁאָלוּהוּ אִם הִסְפִּיק לְדַבֵּר כָּל מָה שֶׁרָצָה וְעָנָה שֶׁאִם הָיָה תָּלוּי בְּמָה שֶׁרוֹצֶה לְדַבֵּר – הֲרֵי אֵין שִׁיעוּר לִזְמַן הַדִּיבּוּר. כֵּן אָמַר אד\"ש שֶׁבִּזְכוּת שֶׁדִּיבֵּר הוּטַב לוֹ וְהוֹדָה לָרוֹפְאִים שֶׁלֹּא עֲצָרוּהוּ בְּאֶמְצַע. הַשִּׂיחָה הוּעֲבְרָה עַל יְדֵי הַטֶּלֶפוֹן )שִׁדּוּר( לִמְקוֹמוֹת רַבִּים בְּכָל קַצְוֵי תֵּבֵל.",
  "es": "Los médicos también le preguntaron si había alcanzado a decir todo lo que quería, y respondió que si hubiera dependido de lo que quiere decir, no habría límite para el tiempo de hablar. También dijo el Rebe que gracias a que había hablado se sintió mejor, y agradeció a los médicos que no lo hubieran detenido a mitad de camino. La charla se transmitió por teléfono a numerosos lugares en todos los confines del mundo."})
