# -*- coding: utf-8 -*-
"""Recopilación de historias (página 2 izquierda, final → página 3)."""

BLOQUES = []

BLOQUES.append({"t": "titulo",
  "he": "לֶקֶט סִפּוּרִים...",
  "es": "Selección de historias..."})

BLOQUES.append({"t": "sub",
  "he": "בַּמֶּה מְשַׂמְּחָם? אֲנָשִׁים בְּיַיִן וְנָשִׁים בְּבָגָדִים",
  "es": "¿Con qué se alegra a cada uno? A los hombres con vino y a las mujeres con vestidos"})

BLOQUES.append({"t": "par",
  "he": "בִּשְׁלֹושֶׁת הָרְגָלִים יֵשׁ לְשַׂמֵּוחַ אֶת הַנָּשִׁים בְּתַכְשִׁיטִים וּבְבָגָדִים נָאִים, וְסִיפֵּר הרב דניאל אוחיון שליט\"א מַעֲשֶׂה שֶׁאֵירַע עִם אֶחָד מִבֵּית מִדְרָשׁוֹ:",
  "es": "En las tres fiestas de peregrinación hay que alegrar a las mujeres con joyas y vestidos elegantes, y contó el Rab Daniel Ojión, shlitá, un hecho que ocurrió con uno de su casa de estudio:"})

BLOQUES.append({"t": "caja", "clase": "cuento",
  "titulo_he": "— מעשה שהיה —", "titulo_es": "— Un caso real —",
  "he": "\"יוֹמַיִם לִפְנֵי חַג הַפֶּסַח פָּגַשׁ אוֹתִי יְהוּדִי וְנָתַן לִי סְכוּם שֶׁל אַרְבַּע מֵאוֹת שְׁקָלִים וּבִיקְּשַׁנִי לִמְסֹור זֹאת לְמִשְׁפָּחָה נִזְקֶקֶת כִּרְאוֹת עֵינַי, וְעוֹד בִּיקֵּשׁ שֶׁלֹּא אֲחַלֵּק אֶת הַסְּכוּם בֵּין כַּמָּה מִשְׁפָּחוֹת אֶלָּא שֶׁאֶתֵּן אֶת כּוּלּוֹ לְמִשְׁפָּחָה אַחַת. לְמָחֳרָת פָּגַשְׁתִּי יְהוּדִי שֶׁאֲנִי יוֹדֵעַ שֶׁמַּצָּבוֹ דָּחוּק, וְנָתַתִּי לוֹ מָאתַיִים שְׁקָלִים מִתּוֹךְ הַתְּרוּמָה שֶׁקִּיבַּלְתִּי, וְאֶת הַיֶּתֶר תִּכְנַּנְתִּי לָתֵת לְמִשְׁפָּחָה אַחֶרֶת נִזְקֶקֶת (בְּאוֹתוֹ רֶגַע לֹא זָכַרְתִּי אֶת בַּקָּשָׁתוֹ הַמְּפֹורֶשֶׁת שֶׁל הַתּוֹרֵם, כִּי אַחֶרֶת לֹא הָיִיתִי עוֹשֶׂה שִׁינּוּי בְּמַה שֶּׁהוּא הִתְנָה). אַחַר כְּשָׁעָה נִזְכַּרְתִּי בִּתְנַאי הַתּוֹרֵם וּמִיָּד הִתְקַשַּׁרְתִּי לַיְּהוּדִי שֶׁקִּיבֵּל מִמֶּנִּי מָאתַיִים שְׁקָלִים וְהוֹדַעְתִּיו שֶׁיֵּשׁ לִי עוֹד מָאתַיִים שְׁקָלִים לִמְסֹור לוֹ. תְּשׁוּבָתוֹ הִפְתִּיעָה אוֹתִי מְאֹוד: 'יָדַעְתִּי שֶׁתָּבִיא לִי עוֹד מָאתַיִים שְׁקָלִים! חִיכִּיתִי לְזֶה'. 'כֵּיצַד יָדַעְתָּ?!' - תָּמַהְתִּי - 'וְכִי אַתָּה יוֹדֵעַ מִי נָתַן לִי אֶת הַסְּכוּם וְכַמָּה הוּא נָתַן?' 'לֹא, אַךְ בּוֹא אֲסַפֵּר לְךָ: אֶתְמוֹל נָסַעְתִּי עִם אִשְׁתִּי וְגִיסָתִי לִבְנֵי בְרַק לִקְנוֹת מִצְרָכִים בְּסִיסִיִּים לֶחָג, יַיִן, סֻכָּר, שֶׁמֶן וְכַיּוֹצֵא בָּזֶה דְּבָרִים בְּסִיסִיִּים הַנִּצְרָכִים לְכָל מִשְׁפָּחָה.",
  "es": "«Dos días antes de la fiesta de Pésaj me encontró un judío y me dio una suma de cuatrocientos shekels, y me pidió que se la entregara a una familia necesitada según mi propio criterio, y además pidió que no repartiera la suma entre varias familias, sino que se la diera entera a una sola familia. Al día siguiente me encontré con un judío cuya situación sé que es apretada, y le di doscientos shekels de la donación que había recibido, y el resto pensaba dárselo a otra familia necesitada (en ese momento no recordé el pedido explícito del donante, porque de otro modo no habría hecho ningún cambio en lo que él había condicionado). Al cabo de una hora recordé la condición del donante e inmediatamente llamé al judío que había recibido de mí doscientos shekels y le avisé de que tenía otros doscientos shekels para entregarle. Su respuesta me sorprendió mucho: 'Sabía que me traerías otros doscientos shekels. Los estaba esperando'. '¿Cómo lo sabías?', me extrañé, '¿acaso sabes quién me dio la suma y cuánto dio?'. 'No, pero deja que te cuente: ayer viajé con mi esposa y mi cuñada a Bnei Brak a comprar productos básicos para la fiesta —vino, azúcar, aceite y cosas básicas parecidas que necesita toda familia—.»"})

BLOQUES.append({"t": "par",
  "he": "\"בַּדֶּרֶךְ לַחֲנוּת הַמָּזוֹן אִשְׁתִּי עָצְרָה לְיַד חֲנוּת בְּגָדִים וְהִתְבּוֹנְנָה בַּבְּגָדִים הַמֻּצָּגִים בְּחַלּוֹן הָרַאֲוָה. הִבְהַרְתִּי לָהּ שֶׁאִם הִיא תִּקְנֶה בֶּגֶד, מִיָּד נַעֲלֶה לַמְּכוֹנִית חֲזָרָה כִּי לֹא נוּכַל לִקְנוֹת כְּלָל מִצְרְכֵי מָזוֹן. אִשְׁתִּי אָמְרָה לִי שֶׁהִיא רַק מִסְתַּכֶּלֶת לְלֹא כַּוָּנָה לִרְכּוֹשׁ בְּגָדִים כָּעֵת, כִּי יוֹדַעַת הִיא אֶת מַצָּבֵנוּ הַכַּלְכָּלִי. אַךְ הָעַיִן רוֹאָה וְהַלֵּב חוֹמֵד... בְּאַחַת הַחֲנוּיוֹת הִיא רָאֲתָה שִׂמְלָה מְיֻוחֶדֶת, וְהִיא נִכְנְסָה לִשְׁאֹל מַה מְּחִירָהּ. 'חֲמֵשׁ מֵאוֹת שֶׁקֶל', עָנְתָה לָהּ הַמּוֹכֶרֶת, 'אַךְ, גְּבֶרֶת, תְּמַדְּדִי קֹודֶם וְאַחַר כָּךְ נְדַבֵּר עַל הַמְּחִיר'... אִשְׁתִּי וְגִיסָתִי הֵחֵלּוּ לְהַפְעִיל עָלַי לַחַץ 'מָתוּן' לִרְכּוֹשׁ אֶת הַשִּׂמְלָה לִכְבוֹד הֶחָג. 'כַּמָּה זֶה עוֹלֶה?' אֲנִי שׁוֹאֵל אֶת הַמּוֹכֶרֶת. 'חֲמֵשׁ מֵאוֹת שֶׁקֶל', עָנְתָה לִי. 'תִּרְאִי, יֵשׁ לִי רַק אַרְבַּע מֵאוֹת שֶׁקֶל'. 'בְּסֵדֶר, אֲדוֹנִי', אָמְרָה הַמּוֹכֶרֶת, 'שֶׁיִּהְיֶה לָכֶם חַג שָׂמֵחַ, אֶעֱשֶׂה לָכֶם הַנָּחָה'. חָשַׁבְתִּי שֶׁאֲנִי מִתְעַלֵּף. הֲרֵי אַתָּה יוֹדֵעַ אֶת מַצָּבִי, אֵין לִי עַכְשָׁו מִצְרְכֵי מָזוֹן בְּסִיסִיִּים לֶחָג וּבַכֶּסֶף שֶׁיֵּשׁ אָנוּ קוֹנִים שִׂמְלָה...",
  "es": "«De camino a la tienda de comestibles, mi esposa se detuvo junto a una tienda de ropa y se quedó mirando los vestidos expuestos en el escaparate. Le dejé claro que si compraba una prenda subiríamos enseguida al coche de vuelta, porque no podríamos comprar en absoluto los productos de alimentación. Mi esposa me dijo que solo estaba mirando, sin intención de comprar ropa ahora, porque conoce nuestra situación económica. Pero el ojo ve y el corazón desea... En una de las tiendas vio un vestido especial, y entró a preguntar cuánto costaba. 'Quinientos shekels', le contestó la vendedora, 'pero, señora, mídaselo primero y después hablamos del precio'... Mi esposa y mi cuñada empezaron a ejercer sobre mí una presión 'moderada' para comprar el vestido en honor de la fiesta. '¿Cuánto cuesta?', le pregunto a la vendedora. 'Quinientos shekels', me contestó. 'Mire, solo tengo cuatrocientos shekels'. 'Está bien, señor', dijo la vendedora, 'que tengan una fiesta feliz, les haré un descuento'. Pensé que me desmayaba. Usted sabe mi situación, ahora no tengo productos básicos de comida para la fiesta, ¡y con el dinero que tenemos compramos un vestido!...»"})

BLOQUES.append({"t": "par",
  "he": "\"כָּאן הֵחֵל הַלַּחַץ שֶׁל גִּיסָתִי. 'מָה יֵשׁ, תִּקְנֶה פַּעַם אַחַת שִׂמְלָה לְאִשְׁתְּךָ'. 'כֵּן, אֲנִי רוֹצֶה', הֵשַׁבְתִּי, 'אֲבָל מָה עִם כֶּסֶף לְמִצְרָכִים?' גִּיסָתִי הִיא אִישָּׁה שֶׁאֵינָהּ שׁוֹמֶרֶת לְעֵת עַתָּה עַל תּוֹרָה וּמִצְוֹות, וְהִיא עוֹנָה לִי כָּךְ: 'הקב\"ה לֹא יָכוֹל לִדְאֹוג לְךָ לְמִצְרָכִים לֶחָג? הֲרֵי אַתָּה יְהוּדִי מַאֲמִין'. אָכֵן הוּא יָכוֹל לִדְאֹוג לִי, אֲבָל בְּעוֹד יוֹם יִהְיֶה חָג... וְשׁוּב גִּיסָתִי לוֹחֶצֶת: 'נוּ, מָה קָשֶׁה לוֹ לְהִתְאַרְגֵּן? גַּם בְּיוֹם אֶחָד הוּא יָכוֹל לִדְאֹוג לְךָ לְאַרְבַּע מֵאוֹת שְׁקָלִים'. וְאָכֵן קָנִיתִי אֶת הַשִּׂמְלָה וְחָזַרְנוּ לְבֵיתֵנוּ לְלֹא מִצְרָכִים. וְהִנֵּה בַּבֹּקֶר אַתָּה מַצִּיעַ לִי מָאתַיִים שְׁקָלִים. אָמַרְתִּי לְעַצְמִי: 'רַק רֶגַע, הַשִּׂמְלָה עָלְתָה אַרְבַּע מֵאוֹת שְׁקָלִים, לָמָּה הקב\"ה שָׁלַח רַק מָאתַיִים שְׁקָלִים?!' וְחִיכִּיתִי לִרְאוֹת מֵהֵיכָן יַגִּיעוּ מָאתַיִים הַשְּׁקָלִים הַנּוֹסָפִים... וְהִנֵּה אַתָּה מְטַלְפֵן וְהִשְׁלַמְתָּ לִי אֶת הַפָּאזֶל...\" אָכֵן, יֵשׁ בַּשָּׁמַיִים מַחְלָקָה מְיֻוחֶדֶת הַמְחַשֶּׁבֶת אֶת הַהוֹצָאוֹת שֶׁאַתָּה מוֹצִיא עֲבוּר הֶחָג, וּבִמְיֻוחָד עֲבוּר רַעְיָיךְ, וְהקב\"ה רוֹאֶה שֶׁזֶּה אֶצְלְךָ \"הַכֶּסֶף הָאַחֲרוֹן\" שֶׁנּוֹתַר לְךָ. אַךְ אַל דְּאָגָה, שִׂימַּחְתָּ אֶת אִשְׁתְּךָ - הקב\"ה יְשַׂמַּח אוֹתְךָ בַּחֲזָרָה.",
  "es": "«Aquí empezó la presión de mi cuñada. '¿Qué pasa, cómprale una vez un vestido a tu esposa'. 'Sí, quiero', respondí, 'pero ¿qué hay del dinero para los productos?'. Mi cuñada es una mujer que por ahora no guarda Torá y mitzvot, y me responde así: '¿El Santo, bendito sea, no puede ocuparse de conseguirte productos para la fiesta? Al fin y al cabo eres un judío creyente'. Ciertamente puede ocuparse de mí, pero en un día será la fiesta... Y de nuevo mi cuñada presiona: 'Bueno, ¿qué le cuesta organizarse? También en un solo día puede ocuparse de conseguirte cuatrocientos shekels'. Y en efecto, compré el vestido y volvimos a casa sin productos. Y he aquí que por la mañana usted me propone doscientos shekels. Me dije a mí mismo: 'Un momento, el vestido costó cuatrocientos shekels, ¿por qué el Santo, bendito sea, envió solo doscientos shekels?', y esperé a ver de dónde llegarían los doscientos shekels que faltaban... Y he aquí que usted llama y me completa el rompecabezas...». Ciertamente hay en el Cielo un departamento especial que calcula los gastos que uno hace por la fiesta, y en especial por su esposa, y el Santo, bendito sea, ve que ese es, para ti, «el último dinero» que te queda. Pero no temas: hiciste feliz a tu esposa, el Santo, bendito sea, te hará feliz a ti de vuelta."})

BLOQUES.append({"t": "par",
  "he": "בְּעֵינֵינוּ הָרְגִילוֹת אֵין אָנוּ רוֹאִים אֶת הַתְּמוּרָה לְכָל הַמַּאֲמַצִּים וְהַהַשְׁקָעָה שֶׁאָנוּ עוֹשִׂים לִכְבוֹד ה' - הקב\"ה. הֲרֵי כַּאֲשֶׁר שִׂימַּחְתָּ אֶת רַעְיָיתְךָ, מִיָּד בַּשָּׁמַיִים \"נִדְלְקוּ אוֹרוֹת\" שֶׁהֵאִירוּ אֶת מִצְוָותְיךָ בְּאוֹר מְיֻוחָד שֶׁנַּעֲשָׂה בִּמְסִירוּת נֶפֶשׁ. אֲבָל מִן הָרָאוּי לַעֲשׂוֹת זֹאת גַּם בְּלֵב שָׁלֵם, בְּלֵב שָׂמֵחַ. לָתֵת הַרְגָּשָׁה טוֹבָה, לְהַעֲנִיק בִּמְיֻוחָד לִקְרַאת הֶחָג שֶׁבּוֹ הִיא כָּל כָּךְ טוֹרַחַת וְעֲמֵלָה.",
  "es": "Con nuestros ojos habituales no vemos la recompensa de todos los esfuerzos y la inversión que hacemos en honor de Dios, el Santo, bendito sea. Al fin y al cabo, cuando hiciste feliz a tu esposa, enseguida en el Cielo «se encendieron luces» que iluminaron tu mitzvá con una luz especial hecha con entrega. Pero conviene hacerlo también de todo corazón, con corazón alegre: dar una buena sensación, regalar especialmente de cara a la fiesta, en la que ella se afana y se esfuerza tanto."})

BLOQUES.append({"t": "par",
  "he": "אֶחָד מִגְּדוֹלֵי תַּלְמִידֵי הַחֲכָמִים שֶׁבִּבְנֵי בְרַק פָּגַשׁ בְּדַרְכּוֹ בְּאַבְרֵךְ צָעִיר בְּעֶרֶב סֻוכּוֹת, בַּשָּׁנָה שֶׁיּוֹם טוֹב הָרִאשׁוֹן שֶׁל הֶחָג חָל לִהְיוֹת בְּשַׁבָּת, וְאֵין בּוֹ נְטִילַת לוּלָב, וְאָמַר לוֹ: \"שְׁמַע, כֻּולָּם טְרוּדִים הַיּוֹם בְּחִיפּוּשׂ אַחֲרֵי אֶתְרוֹג מְהֻודָּר כְּדֵי לְקַיֵּים מִצְוָוה דְּרַבָּנָן (מִצְוַות ד' מִינִים בְּחֹול הַמּוֹעֵד אֵינָהּ אֶלָּא מִדְּרַבָּנָן), וַאֲנִי הוֹלֵךְ לְקַיֵּים מִצְוָוה דְּאוֹרַיְיתָא, דְּהַיְינוּ לִקְנוֹת בִּגְדֵי חָג לְאִשְׁתִּי!\"",
  "es": "Uno de los grandes de entre los <i>talmidé jajamim</i> de Bnei Brak se encontró en su camino, en la víspera de Sucot, con un joven <i>avrej</i>, en el año en que el primer día de la fiesta caía en Shabat y no había ese día toma de lulav, y le dijo: «Escucha, todos están hoy ocupados buscando un etrog hermoso para cumplir una mitzvá de origen rabínico —la mitzvá de las cuatro especies en <i>Jol HaMoed</i> es solo de origen rabínico—, y yo voy a cumplir una mitzvá de la Torá, es decir, a comprarle ropa de fiesta a mi esposa»."})

BLOQUES.append({"t": "par",
  "he": "אָכֵן, אֵין סָפֵק, לְנָשִׁים יֵשׁ חֵלֶק בְּכָל הַהֲכָנוֹת לֶחָגִים. כַּיָּדוּעַ, אִישָּׁה שֶׁזּוֹכָה לְקַבֵּל מִבַּעְלָהּ תַּכְשִׁיטִים אוֹ בְּגָדִים, וַדַּאי זֶה מְשַׂמֵּחַ אוֹתָהּ וְהִיא חָשָׁה שֶׁבַּעְלָהּ מְייַקֵּר אֶת מַאֲמַצֶּיהָ. רַבִּי חַיִּים וִיטָאל כּוֹתֵב כִּי מִדּוֹתָיו שֶׁל אָדָם נִמְדֶּדֶת אַךְ וְרַק כְּפִי יַחֲסוֹ אֶל אִשְׁתּוֹ. אָדָם הָעוֹסֵק בִּגְמִילוּת חֲסָדִים עִם הָמוֹן אֲנָשִׁים, מַלְוֶוה וְנוֹתֵן, מְבַקֵּר חוֹלִים, מְנַחֵם אֲבֵלִים, מְשַׂמֵּחַ חָתָן וְכַלָּה - בְּווַדַּאי יִשְׂחַק לְיוֹם אַחֲרוֹן בְּבוֹא עֵת פְּקֻדָּתוֹ וְיֵחָשֵׁב לוֹ זְכֻויּוֹת רַבּוֹת בְּמַעֲשֵׂי הַחֶסֶד. אַךְ יֵדַע נֶאֱמָנָה, כִּי בַּשָּׁמַיִים בּוֹדְקִים אֵיךְ הִתְנַהֵג עִם אִשְׁתּוֹ! אִם גַּם עִימָּהּ גָּמַל חֶסֶד כָּל יָמָיו - אַשְׁרָיו וְטוֹב לוֹ. אַךְ אִם אוֹתָהּ הִקְנִיט וְהִזְנִיחַ, בְּבֵיתוֹ כָּעַס וְהִקְפִּיד לְלֹא רַחֵם, לְלֹא חֶסֶד וּנְשִׂיאוּת בָּעֹול, הַנְהָגָה זוֹ תַּכְרִיעַ אֶת דִּינוֹ וְלֹא יִזָּכְרוּ לוֹ מְאוּמָה מִכָּל חֲסָדָיו שֶׁעָשָׂה עִם אֲחֵרִים.",
  "es": "Ciertamente, no hay duda de que las mujeres tienen parte en todos los preparativos de las fiestas. Como es sabido, una mujer que tiene el mérito de recibir de su marido joyas o ropa, sin duda eso la alegra, y ella siente que su marido valora sus esfuerzos. Rabí Jaím Vital escribe que las cualidades de una persona se miden única y exclusivamente por su trato hacia su esposa. Una persona que se dedica a la beneficencia con muchísima gente —presta y da, visita enfermos, consuela a los que están de duelo, alegra a novios—, sin duda reirá el último día, cuando llegue el momento de su partida, y se le contarán muchos méritos por sus obras de bondad. Pero que sepa con certeza que en el Cielo comprueban cómo se comportó con su esposa. Si también con ella hizo bondad todos sus días, dichoso él y bien por él. Pero si la molestó y la descuidó, si en su casa se enojaba y era exigente sin compasión, sin bondad ni disposición a cargar con el yugo [de la convivencia], esa conducta decidirá su juicio, y no se le recordará nada de todas las bondades que hizo con otros."})
