# -*- coding: utf-8 -*-
"""Chol HaMoed: la historia del Rav Matzliaj Mazuz (página 3, final derecha e izquierda)."""

BLOQUES = []

BLOQUES.append({"t": "titulo",
  "he": "חוֹבַת הַשְּׁבִיתָה מִמְּלָאכָה בְּחֹול הַמּוֹעֵד",
  "es": "La obligación de cesar del trabajo en Jol HaMoed"})

BLOQUES.append({"t": "par",
  "he": "הָיָה זֶה בְּחֹול הַמּוֹעֵד סֻוכּוֹת תשל\"א. הַגָּאוֹן רבי מצליח מאזוז זצ\"ל עָבַר בִּרְחוֹבוֹת עִיר תּוּנִיס וְרָאָה יְהוּדִי עוֹבֵד בַּחֲנוּתוֹ, בִּמְלֶאכֶת הַצּוֹרְפוּת. אָמַר לוֹ: \"שֶׁמָּא שָׁכַחְתָּ שֶׁאָסוּר לַעֲבֹוד בְּחֹול הַמּוֹעֵד?\" אָמַר: \"יוֹדֵעַ אֲנִי, אֲבָל עֲבוֹדָה דְּחוּפָה לִי לַעֲשׂוֹתָהּ\". אָמַר לוֹ הָרַב: \"אֵין זֶה 'דָּבָר הָאָבֵד', וְאָסוּר לַעֲשׂוֹתוֹ בַּמּוֹעֵד\". לֹא צִיֵּת הָאִישׁ, וְהִמְשִׁיךְ בִּמְלַאכְתּוֹ.",
  "es": "Fue en <i>Jol HaMoed</i> de Sucot del 5731. El gaón Rab Matzliaj Mazuz, z”l, pasaba por las calles de la ciudad de Túnez y vio a un judío trabajando en su tienda, en el oficio de orfebrería. Le dijo: «¿Acaso olvidaste que está prohibido trabajar en <i>Jol HaMoed</i>?». Dijo: «Lo sé, pero tengo un trabajo urgente que hacer». Le dijo el rabino: «Esto no es 'cosa que se pierde' [<i>davar haavéd</i>], y está prohibido hacerlo en la festividad». El hombre no obedeció y siguió con su trabajo."})

BLOQUES.append({"t": "par",
  "he": "כַּעֲבֹר שְׁלֹשָׁה שָׁבוּעוֹת, בְּיוֹם שִׁישִׁי, הִגִּיעָה לְבֵית הָרַב נַעֲרָה בּוֹכִיָּה: אָבִיהָ הַצּוֹרֵף נֶעְצַר בַּעֲלִילָה שֶׁקָּנָה תַּכְשִׁיטִים גְּנוּבִים. מִיָּד קָם הָרַב וְהָלַךְ לְתַחֲנַת הַמִּשְׁטָרָה, בִּיקֵּשׁ שֶׁיְּשַׁחְרְרוּ אֶת הֶעָצוּר לְשַׁבָּת וְחָתַם עֲרֵבוּת לְשׁוּבוֹ לַכֶּלֶא בְּיוֹם רִאשׁוֹן. בַּדֶּרֶךְ סִפֵּר הֶעָצוּר כִּי מֵחֲמַת הָעִינּוּיִים הוֹדָה בִּנְכוֹנוּת הָעֲלִילָה, לַמְרוֹת שֶׁהָאֱמֶת הִיא שֶׁלֹּא סָחַר בְּתַכְשִׁיטִים גְּנוּבִים; אַדְּרַבָּה, מִמֶּנּוּ נִגְנְבוּ תַּכְשִׁיטִים יְקָרִים.",
  "es": "Al cabo de tres semanas, un viernes, llegó a casa del rabino una jovencita llorando: su padre, el orfebre, había sido arrestado bajo la acusación de haber comprado joyas robadas. Enseguida se levantó el rabino y fue a la comisaría, pidió que liberaran al detenido para Shabat y firmó una garantía de que volvería a la cárcel el domingo. Por el camino, el detenido contó que, a causa de los interrogatorios, había admitido la veracidad de la acusación, aunque la verdad era que no traficaba con joyas robadas; al contrario, a él le habían robado joyas caras."})

BLOQUES.append({"t": "par",
  "he": "אָמַר לוֹ הָרַב: \"אֲסַפֵּר לְךָ סִפּוּר מִן הַגְּמָרָא. מַעֲשֶׂה בְּאָדָם שֶׁהֶחְמִיצוּ לוֹ אַרְבַּע מֵאוֹת חָבִיּוֹת יַיִן. עָרַךְ חֶשְׁבּוֹן נֶפֶשׁ, וְהֵבִין שֶׁקִּפֵּחַ אֶת הָאָרִיס שֶׁעָבַד בְּכַרְמוֹ, וְעַל כֵּן אֵרַע לוֹ הֶפְסֵד זֶה. פִּצָּה אֶת הָאָרִיס, וְהִנֵּה הִתְיַקֵּר הַחֹמֶץ וְנִמְכַּר בִּמְחִיר יַיִן וְכִסָּה אֶת הֶפְסֵדוֹ... כְּדַאי גַּם לְךָ לַעֲרֹךְ חֶשְׁבּוֹן נֶפֶשׁ: עָבַדְתָּ בְּחֹול הַמּוֹעֵד כְּדֵי לְהַרְוִיחַ עוֹד מְעַט מָמוֹן, וּלְבַסּוֹף רְאֵה מַה הִרְוַחְתָּ...\" אָמַר: \"טָעִיתִי, רַבִּי, לֹא אוֹסִיף עוֹד לְחַלֵּל אֶת קְדֻושַּׁת חֹל הַמּוֹעֵד\".",
  "es": "Le dijo el rabino: «Te contaré una historia de la Guemará: sucedió con un hombre al que se le agriaron cuatrocientos toneles de vino. Hizo examen de conciencia y entendió que había perjudicado al aparcero que trabajaba en su viña, y que por eso le había ocurrido esta pérdida. Compensó al aparcero, y he aquí que subió el precio del vinagre y se vendió al precio del vino, y cubrió su pérdida... También a ti te conviene hacer examen de conciencia: trabajaste en <i>Jol HaMoed</i> para ganar un poco más de dinero, y al final mira lo que has ganado...». Dijo: «Me equivoqué, rabino, no volveré a profanar la santidad de <i>Jol HaMoed</i>»."})

BLOQUES.append({"t": "par",
  "he": "בְּיוֹם רִאשׁוֹן שָׁב הָאִישׁ לַכֶּלֶא. אָמַר לוֹ הַחוֹקֵר: \"כְּשֶׁרָאִיתִי שֶׁהָרַב מָאזוּז עָרֵב לְיָשְׁרְךָ וּמִשְׁתַּדֵּל לְמַעַנְךָ, הֵבַנְתִּי שֶׁאַתָּה אָדָם יָשָׁר. פָּתַחְתִּי בַּחֲקִירָה נִמְרֶצֶת וְגִלִּיתִי שֶׁהַפּוֹעֵל הָעַרְבִי שֶׁלְּךָ הוּא שֶׁרָכַשׁ אֶת הַסְּחוֹרָה הַגְּנוּבָה, וְלֹא עוֹד אֶלָּא שֶׁהוֹדָה בִּגְנֵבוֹת שֶׁגָּנַב אֶצְלְךָ, וְהֶחְזִירָן!\"",
  "es": "El domingo el hombre volvió a la cárcel. Le dijo el investigador: «Cuando vi que el Rab Mazuz garantizaba tu rectitud y se esforzaba por ti, entendí que eras una persona honesta. Abrí una investigación intensa y descubrí que fue tu empleado árabe quien compró la mercancía robada, y no solo eso, sino que confesó los robos que había cometido en tu propia casa, ¡y los devolvió!»."})

# ============================================================ ARTÍCULO — «ולקחתם לכם ביוהכ הראשון»
BLOQUES.append({"t": "titulo",
  "he": "\"וּלְקַחְתֶּם לָכֶם בַּיּוֹם הָרִאשׁוֹן\" (ויקרא כג, מ)",
  "es": "«Y tomaréis para vosotros el primer día» (Vaikrá 23:40)"})

BLOQUES.append({"t": "par",
  "he": "אִיתָא בַּמִּדְרָשׁ: \"בַּיּוֹם הָרִאשׁוֹן - רִאשׁוֹן לְחֶשְׁבּוֹן עֲווֹנוֹת\". וּכְבָר דָּנוּ הַמְּפָרְשִׁים הֵיאַךְ הוּא רִאשׁוֹן לַעֲווֹנוֹת, וְאָמְרוּ שֶׁכֵּיוָן שֶׁבְּאַרְבָּעָה יָמִים מִיּוֹם כִּפּוּרִים עַד סֻוכּוֹת עֲסוּקִים הָעָם בְּמִצְווֹת, לָכֵן לֹא הָיָה לָהֶם פְּנַאי לַחֲטֹא. אוּלָם גַּם זֶה דָּחוּק, כִּי אֵיךְ אֶפְשָׁר לוֹמַר שֶׁכֻּולָּם לֹא חוֹטְאִים כְּלָל בְּמֶשֶׁךְ אַרְבָּעָה יָמִים, מַה גַּם שֶׁאָמְרוּ חֲזַ\"ל \"אֵין צַדִּיק בָּאָרֶץ אֲשֶׁר יַעֲשֶׂה טּוֹב וְלֹא יֶחֱטָא\", אִם כֵּן גַּם הָעוֹסְקִים וְעוֹשִׂים טוֹב עֲדַיִן חוֹטְאִים.",
  "es": "Se encuentra en el midrash: «'El primer día' —primer día para la cuenta de los pecados—». Y ya discutieron los comentaristas cómo es que es el primero para los pecados, y dijeron que, dado que en los cuatro días desde Yom Kipur hasta Sucot el pueblo está ocupado en mitzvot, por eso no tenían tiempo libre para pecar. Pero también esto es forzado, porque ¿cómo se puede decir que todos no pecan en absoluto durante cuatro días? Más aún cuando dijeron nuestros sabios: «no hay justo en la tierra que haga el bien y no peque»; si es así, también los que se ocupan y hacen el bien siguen pecando."})

BLOQUES.append({"t": "par",
  "he": "אֶלָּא מְסַבִּיר הַגָּאוֹן מִוִּילְנָה זַע\"ה בְּאֹפֶן נִפְלָא, לְפִי יְסוֹדוֹ וְהֶסְבֵּרוֹ הַמְּפֻרְסָם בְּבֵאוּר הַהֶבְדֵּל שֶׁבֵּין 'דִּין' וְ'חֶשְׁבּוֹן'. דְּהָרֵי הַמִּשְׁנָה (אבות ג, א) אוֹמֶרֶת: \"הִסְתַּכֵּל בִּשְׁלוֹשָׁה דְבָרִים וְכוּ', וְלִפְנֵי מִי אַתָּה עָתִיד לִיתֵּן דִּין וְחֶשְׁבּוֹן\", וּמַהוּ לִכְאוֹרָה כְּפִילוּת הַלָּשׁוֹן - 'דִּין' וְ'חֶשְׁבּוֹן'? וּמְסַבִּיר הַגְּרָ\"א: כִּי בְּ'דִין' מַעֲנִישִׁים הָאָדָם עַל הָעֲבֵירָה שֶׁעָשָׂה, וּבְ'חֶשְׁבּוֹן' מְחַשְּׁבִים אִתּוֹ עַל אוֹתוֹ זְמַן שֶׁחָטָא, שֶׁהָיָה יָכוֹל לַעֲשׂוֹת מִצְוָה בִּמְקוֹמָהּ. אָמְנָם זֶה הַכֹּל אִם חָטָא בְּמַחֲשָׁבָה תְּחִילָּה, שֶׁאָז נֶעֱנָשׁ עַל מַה שֶּׁלֹּא עָשָׂה מִצְוָה בִּמְקוֹם זֶה.",
  "es": "Sino que explica el Gaón de Vilna, que su memoria sea bendita, de manera maravillosa, según su fundamento y su explicación célebre para aclarar la diferencia entre 'juicio' (<i>din</i>) y 'cuenta' (<i>jeshbón</i>). Pues la Mishná (Avot 3:1) dice: «Observa tres cosas, etc., y ante Quién estás destinado a dar cuenta y juicio (<i>din veJeshbón</i>)», y ¿qué es, aparentemente, esta duplicación del lenguaje —'juicio' y 'cuenta'—? Y explica el Gaón: porque en el 'juicio' se castiga a la persona por la transgresión que hizo, y en la 'cuenta' se le calcula por aquel tiempo en que pecó, en el que podría haber hecho una mitzvá en su lugar. Aunque esto es todo si pecó con premeditación, pues entonces es castigado también por no haber hecho una mitzvá en ese lugar."})

BLOQUES.append({"t": "par",
  "he": "אֲבָל בְּאַרְבָּעָה יָמִים שֶׁל עֶרֶב סֻוכּוֹת, אָמְנָם אֶפְשָׁר שֶׁאֲנָשִׁים חוֹטְאִים, אֲבָל מֵרֹוב עִסּוּקָם בְּמִצְווֹת אִי אֶפְשָׁר שֶׁיֶּחֶטְאוּ בְּמַחֲשָׁבָה תְּחִילָּה. לָכֵן עַל זֶה בִּלְבַד אֵין דָּנִים עַד יוֹם רִאשׁוֹן שֶׁל סֻוכּוֹת. לְפִי זֶה מְדֻקְדָּק הַלָּשׁוֹן \"רִאשׁוֹן 'לְחֶשְׁבּוֹן' עֲווֹנוֹת\", דְּהַיְינוּ, לֹא רִאשׁוֹן לְדִין עַל עֲווֹנוֹת בִּכְלָל, רַק לְ'חֶשְׁבּוֹן' הָעֲווֹנוֹת, מַה יָּכוֹל לַעֲשׂוֹת בִּזְמַן הַחֵטְא...",
  "es": "Pero en los cuatro días de víspera de Sucot, ciertamente es posible que la gente peque, pero, por lo ocupados que están en mitzvot, no es posible que pequen con premeditación. Por eso, solo sobre esto no se juzga hasta el primer día de Sucot. Según esto se precisa el lenguaje «primero para la 'cuenta' de los pecados», es decir: no primero para el juicio sobre los pecados en general, sino solo para la 'cuenta' de los pecados —qué podría haber hecho en el momento del pecado—..."})

BLOQUES.append({"t": "par",
  "he": "וְאִילּוּ הרה\"ק רבי יחזקאל מקוזמיר זי\"ע הִסְבִּיר, עַל פִּי מָשָׁל, אֶת דִּבְרֵי הַמִּדְרָשׁ \"וּלְקַחְתֶּם לָכֶם בַּיּוֹם הָרִאשׁוֹן - רִאשׁוֹן לְחֶשְׁבּוֹן עֲווֹנוֹת\": מָשָׁל לְסוֹחֵר שֶׁהָיָה מְקַבֵּל סְחוֹרָה בְּהַקָּפָה, מוֹכֵר בְּרֶוַח וּמְשַׁלֵּם. לְיָמִים אִיתְרַע מַזָּלוֹ וְנִקְלַע לְחוֹבוֹת, הָלַךְ לְמוֹכֵר בַּעַל חוֹבוֹ וּבִקֵּשׁ לְהַאֲרִיךְ אֶת זְמַן הַפֵּרָעוֹן, וְנֵעֲתַר לוֹ. עָבַר זְמַן וְלֹא הִצְלִיחַ לְשַׁלֵּם חוֹבוֹ, הָלַךְ שׁוּב לְבַעַל חוֹבוֹ וְהִפְצִיר בּוֹ שֶׁיְּרַחֵם עָלָיו, הִסְכִּים לְוַתֵּר לוֹ עַל חֵלֶק מִן הַחוֹב, וְהַשְּׁאָר יְשַׁלֵּם לִזְמַן מְאֻחָר יוֹתֵר. וְשׁוּב, עָבַר הַזְּמַן וְלֹא מָצָא מֵהֵיכָן לְשַׁלֵּם, הִתְחַנֵּן לְפָנָיו וּמָחַל לוֹ עַל חֵלֶק נוֹסָף מֵחוֹבוֹתָיו, מִשֶּׁלֹּא הִצְלִיחַ גַּם לַעֲמֹד בָּזֶה, בָּא פַּעַם נוֹסֶפֶת בְּבֹשֶׁת פָּנִים עַד שֶׁלְּבַסּוֹף הִסְכִּים לִמְחוֹל לוֹ עַל הַכֹּל.",
  "es": "En cambio, el <i>rabí hakadosh</i> Rabí Yejezkel de Kuzmir, que su mérito nos proteja, explicó, mediante una parábola, las palabras del midrash «'y tomaréis para vosotros el primer día' —primero para la cuenta de los pecados—»: parábola de un comerciante que recibía mercancía a crédito, la vendía con ganancia y pagaba. Con el tiempo su suerte empeoró y se vio envuelto en deudas; fue al vendedor, su acreedor, y le pidió alargar el plazo de pago, y este accedió. Pasó el tiempo y no logró pagar su deuda; fue de nuevo a su acreedor y le suplicó que se apiadara de él; accedió a perdonarle parte de la deuda, y el resto lo pagaría en un plazo más tardío. Y de nuevo pasó el tiempo y no encontró de dónde pagar; le imploró y le perdonó otra parte más de sus deudas; al no lograr cumplir tampoco con eso, vino una vez más avergonzado, hasta que finalmente aceptó perdonarle todo."})

BLOQUES.append({"t": "par",
  "he": "חִכֵּךְ הַסּוֹחֵר בְּדַעְתּוֹ: אָכֵן נִפְטַרְתִּי מִכָּל חוֹבוֹתַי, אוּלָם מִי יַסְכִּים לִמְכֹּר לִי מֵחָדָשׁ סְחוֹרָה בְּהַקָּפָה, אַחֲרֵי שֶׁרָאוּ שֶׁאֵינִי מְשַׁלֵּם, הֲלֹא אֶת כָּל הָאֵמוּן בִּי הִפְסַדְתִּי. קָרָא לְכָל קְרוֹבָיו וּמַכָּרָיו וְשָׁטַח לִפְנֵיהֶם אֶת צָרָתוֹ, שֶׁנִּשְׁאַר לְלֹא סְחוֹרָה וּלְלֹא מְקוֹר פַּרְנָסָה, הִתְנַדְּבוּ הַקְּרוֹבִים לָתֵת לוֹ כָּל אֶחָד כְּפִי יְכָלְתּוֹ, עַד שֶׁאָסַף כְּדֵי כָּל חוֹבוֹ, וּפָרַע לַסּוֹחֵר אֶת כָּל חוֹבוֹתָיו, וְהֵחֵל לִסְחֹור מֵחָדָשׁ וּלְהִשְׁתַּקֵּם.",
  "es": "El comerciante dudó en su mente: en verdad me libré de todas mis deudas, pero ¿quién aceptará venderme de nuevo mercancía a crédito, después de haber visto que no pago? He perdido toda la confianza que tenían en mí. Llamó a todos sus parientes y conocidos y les expuso su aprieto, que se había quedado sin mercancía y sin fuente de sustento. Los parientes se ofrecieron a darle, cada uno según su capacidad, hasta que reunió lo suficiente para toda su deuda, y pagó al comerciante todas sus deudas, y empezó a comerciar de nuevo y a rehabilitarse."})

BLOQUES.append({"t": "par",
  "he": "כֵּן הוּא אֶצְלֵנוּ: כַּמּוּבָא בְּמִדְרָשׁ תַּנְחוּמָא, הוּבָא בַּטּוּר או\"ח (תקפ\"א), וְזֶה לְשׁוֹנוֹ: \"וּלְקַחְתֶּם לָכֶם בַּיּוֹם הָרִאשׁוֹן, וְכִי רִאשׁוֹן הוּא וַהֲלֹא ט\"ו הוּא? אֶלָּא רִאשׁוֹן לְחֶשְׁבּוֹן עֲווֹנוֹת. מָשָׁל לִמְדִינָה שֶׁחַיֶּיבֶת מַס לַמֶּלֶךְ וְלֹא נָתְנוּ לוֹ, בָּא אֵלֶיהָ בְּחַיִל לְגָבְותּוֹ, כְּשֶׁנִּתְקָרֵב אֵלֶיהָ בַּעֲשָׂרָה פַּרְסָאוֹת יָצְאוּ גְּדוֹלֵי הַמְּדִינָה לִקְרָאתוֹ וְאָמְרוּ לוֹ אֵין לָנוּ מַה לִּיתֵּן לָךְ, וִיתֵּר לָהֶם שְׁלִישׁ. כֵּיוָן שֶׁנִּתְקָרֵב יוֹתֵר, יָצְאוּ בֵּינוֹנֵי הָעִיר לִקְרָאתוֹ, וְוִיתֵּר לָהֶם שְׁלִישׁ הַשֵּׁנִי. כְּשֶׁנִּתְקָרֵב יוֹתֵר, יָצְאוּ כָּל בְּנֵי הָעִיר לִקְרָאתוֹ וְהִנִּיחַ לָהֶם הַכֹּל.",
  "es": "Así es con nosotros: como se trae en el midrash Tanjuma, citado en el Tur Óraj Jaím (581), y estas son sus palabras: «'Y tomaréis para vosotros el primer día' —¿acaso es el primer día, si no es el quince?— sino que es primero para la cuenta de los pecados. Parábola de una provincia que debía impuestos al rey y no se los pagó: vino contra ella con su ejército para cobrárselo. Cuando se acercó a ella a diez <i>parsaot</i> de distancia, salieron a su encuentro los grandes de la provincia y le dijeron: no tenemos qué darte; y les perdonó un tercio. Al acercarse más, salieron a su encuentro los de clase media de la ciudad, y les perdonó el segundo tercio. Al acercarse aún más, salió a su encuentro todo el pueblo de la ciudad, y les dejó todo.»"})

BLOQUES.append({"t": "par",
  "he": "כָּךְ הַמֶּלֶךְ, זֶה מֶלֶךְ מַלְכֵי הַמְּלָכִים - הקב\"ה. בְּנֵי הַמְּדִינָה, אֵלּוּ יִשְׂרָאֵל שֶׁעוֹשִׂים עֲווֹנוֹת כָּל הַשָּׁנָה. וּבְעֶרֶב רֹאשׁ הַשָּׁנָה הַגְּדוֹלִים מִתְעַנִּים וּמְווַתֵּר לָהֶם שְׁלִישׁ עֲווֹנוֹתֵיהֶם, בַּעֲשֶׂרֶת יְמֵי תְּשׁוּבָה בֵּינוֹנִיִּים מִתְעַנִּים, וּמְווַתֵּר לָהֶם שְׁנֵי שְׁלִישׁ, אֲבָל בְּיוֹם כִּפּוּר הַכֹּל מִתְעַנִּים וּמְווַתֵּר לָהֶם הַכֹּל. בְּמוֹצָאֵי יוֹם הַכִּיפּוּרִים עוֹסְקִים בְּמִצְוַות סוּכָּה וְלוּלָב וְאֵין עוֹשִׂין עֲווֹנוֹת, לְכָךְ קוֹרֵא יוֹם טוֹב רִאשׁוֹן - רִאשׁוֹן לְחֶשְׁבּוֹן עֲווֹנוֹת.",
  "es": "Así es el rey, este es el Rey de reyes de los reyes, el Santo, bendito sea. Los habitantes de la provincia son Israel, que hacen pecados todo el año. Y en la víspera de Rosh HaShaná ayunan los grandes, y se les perdona un tercio de sus pecados; en los Diez Días de <i>Teshuvá</i> ayunan los de clase media, y se les perdonan dos tercios; pero en Yom Kipur todos ayunan y se les perdona todo. En la salida de Yom Kipur se ocupan de la mitzvá de la <i>sucá</i> y el <i>lulav</i> y no hacen pecados; por eso llama al primer día de fiesta 'primero para la cuenta de los pecados'."})

BLOQUES.append({"t": "par",
  "he": "אַךְ לִכְאוֹרָה קָשֶׁה, הָיָה לוֹ לוֹמַר רִאשׁוֹן לְחֶשְׁבּוֹן הַמִּצְווֹת? אֶלָּא הָעִנְיָן כִּי אַף שֶׁוִּתֵּר לָנוּ הקב\"ה כָּל הָעֲבֵירוֹת, וּבְיוֹם הַכִּיפּוּרִים הקב\"ה הִסְכִּים לִמְחוֹל לָנוּ עַד הַפְּרוּטָה הָאַחֲרוֹנָה, אוּלָם אֵין לָנוּ בִּטָּחוֹן בַּמָּה לְהַתְחִיל וְלָשֵׂאת עִמּוֹ, כְּדֵי לְקַבֵּל סְחוֹרָה חֲדָשָׁה שֶׁיַּשְׁפִּיעַ לָנוּ מֵחָדָשׁ מֵהֶאָרוֹתָיו, וְנוּכַל לְהַתְחִיל לִסְחֹור מֵחָדָשׁ. עַל כֵּן מַזְמִינִים אָנוּ בִּימֵי חַג הַסֻּוכּוֹת אֲבוֹת הַמִּשְׁפָּחָה וְהַקְּרוֹבִים, הֵם הָאֻושְׁפִּיזִין הַקְּדוֹשִׁים, וּמְבַקְּשִׁים מֵהֶם שֶׁיִּתְּנוּ לָנוּ סִיּוּעַ שֶׁנּוּכַל לִסְחֹור מֵחָדָשׁ: אַבְרָהָם נוֹתֵן לָנוּ בַּיּוֹם הָרִאשׁוֹן מִמִּידַּת הַחֶסֶד, יִצְחָק אָבִינוּ נוֹתֵן לָנוּ מִמִּידַּת הַגְּבוּרָה שֶׁלּוֹ, הִתְגַּבְּרוּת עַל הַיֵּצֶר, יַעֲקֹב נוֹתֵן לָנוּ תּוֹרָה וְכֵן הָלְאָה... וְלָכֵן בְּיוֹם טוֹב רִאשׁוֹן הוּא \"רִאשׁוֹן לְחֶשְׁבּוֹן עֲווֹנוֹת\", שֶׁאָז יִשְׂרָאֵל מַתְחִילִים לִפְרֹועַ אֶת חֶשְׁבּוֹן עֲווֹנוֹת, כַּאֲשֶׁר בְּמֶשֶׁךְ יְמֵי הֶחָג מַגִּיעִים כָּל הָאֻושְׁפִּיזִין, נִתְקַבֵּץ לָנוּ מִזְּכֻויּוֹתֵיהֶם וּמִידּוֹתֵיהֶם הַטּוֹבוֹת סְכוּם הָגוּן דַּי וְהוֹתֵר לִפְרֹועַ כָּל חוֹבַת עֲווֹנוֹתֵינוּ, וְאָז אָנוּ עוֹשִׂים מֵרֹוב שִׂמְחָה: שִׂמְחַת תּוֹרָה!...",
  "es": "Pero, en apariencia, esto es difícil: ¿no debería haber dicho 'primero para la cuenta de las mitzvot'? Sino que el asunto es que, aunque el Santo, bendito sea, nos perdonó todas las transgresiones, y en Yom Kipur el Santo, bendito sea, aceptó perdonarnos hasta la última moneda, sin embargo no tenemos garantía de con qué empezar y con qué presentarnos ante Él, para poder recibir mercancía nueva que Él nos haga llegar de nuevo de Sus luces, y podamos empezar a comerciar de nuevo. Por eso invitamos en los días de la fiesta de Sucot a los patriarcas de la familia y a los parientes —son los santos <i>Ushpizín</i> [huéspedes]—, y les pedimos que nos den ayuda para que podamos comerciar de nuevo: Avraham nos da el primer día de la cualidad de la bondad; Itzjak, nuestro padre, nos da de su cualidad del rigor, la victoria sobre el <i>iétzer</i> [la inclinación al mal]; Yaakov nos da Torá, y así sucesivamente... Y por eso el primer día de fiesta es «primero para la cuenta de los pecados», pues entonces Israel empieza a saldar la cuenta de los pecados, cuando durante los días de la fiesta llegan todos los <i>Ushpizín</i>, se nos reúne de sus méritos y de sus buenas cualidades una suma respetable, más que suficiente para saldar toda la deuda de nuestros pecados, y entonces hacemos, de tanta alegría, ¡Simjat Torá!..."})
