# -*- coding: utf-8 -*-
"""Artículos 2, 3 y 4 (página 1 izquierda → página 2 derecha)."""

BLOQUES = []

# ============================================================ ARTÍCULO 2 — enseñanza breve
BLOQUES.append({"t": "titulo",
  "he": "לְכָל יוֹם שֶׁל יְשִׁיבָה בַּסֻּוכָּה יֵשׁ אֶת הַיְּכוֹלוֹת לְתַקֵּן אֶחָד מִימוֹת הַשָּׁבוּעַ",
  "es": "Cada día de estancia en la sucá tiene la capacidad de reparar uno de los días de la semana"})

BLOQUES.append({"t": "par",
  "he": "יֵשׁ חִיּוּב מִן הַתּוֹרָה בַּלַּיְלָה הָרִאשׁוֹן לֶאֱכֹול פַּת בַּסֻּוכָּה, כָּךְ אָנוּ מְתַקְּנִים אֶת הַיּוֹם הָרִאשׁוֹן בַּשָּׁבוּעַ, וְכֵן הָלְאָה.",
  "es": "Hay una obligación de la Torá de comer pan en la sucá la primera noche; así reparamos el primer día de la semana, y así sucesivamente."})

# ============================================================ ARTÍCULO 3 — los tres dones y las tres fiestas
BLOQUES.append({"t": "titulo",
  "he": "שְׁלוֹשֶׁת הַמַּתָּנוֹת וּשְׁלוֹשֶׁת הָרְגָלִים",
  "es": "Los tres dones y las tres fiestas de peregrinación"})

BLOQUES.append({"t": "par",
  "he": "הַגְּמָרָא בְּתַעֲנִית ט. \"רַבִּי יוֹסֵי בְּרַבִּי יְהוּדָה אוֹמֵר: שְׁלֹשָׁה פַּרְנָסִים טוֹבִים עָמְדוּ לְיִשְׂרָאֵל, אֵלּוּ הֵן: מֹשֶׁה, וְאַהֲרֹן, וּמִרְיָם. וְשָׁלֹשׁ מַתָּנוֹת טוֹבוֹת נִתְּנוּ עַל יָדָם, וְאֵלּוּ הֵן: בְּאֵר, וְעָנָן, וּמָן. בְּאֵר בִּזְכוּת מִרְיָם, עַמּוּד עָנָן בִּזְכוּת אַהֲרֹן, מָן בִּזְכוּת מֹשֶׁה. מֵתָה מִרְיָם נִסְתַּלֵּק הַבְּאֵר, שֶׁנֶּאֱמַר (במדבר כ) וַתָּמָת שָׁם מִרְיָם, וּכְתִיב בַּתְרֵיהּ וְלֹא הָיָה מַיִם לָעֵדָה, וְחָזְרָה בִּזְכוּת שְׁנֵיהֶן. מֵת אַהֲרֹן נִסְתַּלְּקוּ עַנְנֵי כָבוֹד, שֶׁנֶּאֱמַר (במדבר כ\"א) וַיִּשְׁמַע הַכְּנַעֲנִי מֶלֶךְ עֲרָד, מָה שְׁמוּעָה שָׁמַע? שָׁמַע שֶׁמֵּת אַהֲרֹן וְנִסְתַּלְּקוּ עַנְנֵי כָבוֹד, וְכַסָּבוּר נִתְּנָה לוֹ רְשׁוּת לְהִלָּחֵם בְּיִשְׂרָאֵל. וְהַיְנוּ דִּכְתִיב (במדבר כ) וַיִּרְאוּ כָּל הָעֵדָה כִּי גָוַע אַהֲרֹן, אָמַר רַבִּי אַבָּהוּ: אַל תִּקְרֵי וַיִּרְאוּ אֶלָּא וַיִּרָאוּ, כִּדְדָרֵישׁ רֵישׁ לָקִישׁ, דְּאָמַר רֵישׁ לָקִישׁ: כִּי מְשַׁמֵּשׁ בְּאַרְבַּע לְשׁוֹנוֹת: אִי, דִּלְמָא, אֶלָּא, דְּהָא. חָזְרוּ שְׁנֵיהֶם בִּזְכוּת מֹשֶׁה, מֵת מֹשֶׁה נִסְתַּלְּקוּ כּוּלָּן, שֶׁנֶּאֱמַר (זכריה י\"א) וָאַכְחִד אֶת שְׁלוֹשֶׁת הָרֹעִים בְּיֶרַח אֶחָד. וְכִי בְּיֶרַח אֶחָד מֵתוּ? וְהֲלֹא מִרְיָם מֵתָה בְּנִיסָן, וְאַהֲרֹן בְּאָב, וּמֹשֶׁה בַּאֲדָר! אֶלָּא: מְלַמֵּד שֶׁנִּתְבַּטְּלוּ שָׁלֹשׁ מַתָּנוֹת טוֹבוֹת שֶׁנִּתְּנוּ עַל יָדָן, וְנִסְתַּלְּקוּ כּוּלָּן בְּיֶרַח אֶחָד\".",
  "es": "La Guemará en Taanit 9a: «Rabí Yosí, hijo de Rabí Yehudá, dice: tres buenos proveedores se alzaron para Israel, y estos son: Moshé, Aharón y Miriam; y tres buenos dones se dieron por su mano, y estos son: el pozo, la nube y el maná. El pozo, por mérito de Miriam; la columna de nube, por mérito de Aharón; el maná, por mérito de Moshé. Murió Miriam, desapareció el pozo, como está dicho (Bemidbar 20): «y murió allí Miriam», y está escrito a continuación «y no había agua para la congregación», y volvió por mérito de los otros dos. Murió Aharón, desaparecieron las Nubes de Gloria, como está dicho (Bemidbar 21): «y oyó el cananeo, rey de Arad»; ¿qué noticia oyó? Oyó que había muerto Aharón y habían desaparecido las Nubes de Gloria, y supuso que se le había dado permiso para luchar contra Israel. Y esto es lo que está escrito (Bemidbar 20): «y vio toda la congregación que había expirado Aharón» —dijo Rabí Abahu: no leas <i>vaireú</i> [«vieron»] sino <i>vairaú</i> [«temieron»], según lo que expone Resh Lakish, que dijo Resh Lakish: [la partícula] <i>ki</i> sirve para cuatro sentidos: si, quizás, sino, pues—. Volvieron ambos [pozo y nube] por mérito de Moshé; murió Moshé, desaparecieron todos, como está dicho (Zejaryá 11): «y exterminé a los tres pastores en un solo mes». ¿Acaso murieron en un solo mes? ¿No murió Miriam en Nisán, y Aharón en Av, y Moshé en Adar? Sino que enseña que se anularon los tres buenos dones que se dieron por su mano, y desaparecieron todos en un solo mes»."})

BLOQUES.append({"t": "par",
  "he": "שְׁלוֹשֶׁת הַמַּתָּנוֹת הַלָּלוּ הֵם כְּנֶגֶד שְׁלוֹשֶׁת הָרְגָלִים: מָן - פֶּסַח, שֶׁבּוֹ אוֹכְלִים מַצּוֹות כְּנֶגֶד לֶחֶם עֹנִי וּבִזְכוּת מֹשֶׁה שֶׁהוֹצִיא אוֹתָנוּ מִמִּצְרַיִם. בְּאֵר - שָׁבוּעוֹת, שֶׁבּוֹ קִבַּלְנוּ אֶת הַתּוֹרָה שֶׁנִּמְשְׁלָה לְמַיִם, וּבִזְכוּת מִרְיָם שֶׁהָיָה בָּהּ אֶת מִדַּת הַנְּתִינָה (מַתַּן-תּוֹרָה). עָנָן - סֻוכּוֹת, שֶׁעוֹשִׂים כְּנֶגֶד עַנְנֵי הַכָּבוֹד שֶׁהוֹשִׁיב אוֹתָנוּ הקב\"ה, וּבִזְכוּת אַהֲרֹן שֶׁמִּדָּתוֹ הִיא הַשָּׁלוֹם (סֻוכּוֹת - חַג הָאַחְדוּת).",
  "es": "Estos tres dones corresponden a las tres fiestas de peregrinación: el maná — Pésaj, en la que se come matzá en correspondencia con el «pan de pobreza», y por mérito de Moshé, que nos sacó de Egipto. El pozo — Shavuot, en la que recibimos la Torá, que se compara al agua, y por mérito de Miriam, que tenía en ella el atributo de dar (la entrega de la Torá). La nube — Sucot, que se hace en correspondencia con las Nubes de Gloria en las que nos hizo habitar el Santo, bendito sea, y por mérito de Aharón, cuyo atributo es la paz (Sucot, la fiesta de la unidad)."})

BLOQUES.append({"t": "sub", "he": "שְׁלוֹשֶׁת הַכְּתָרִים", "es": "Las tres coronas"})

BLOQUES.append({"t": "par",
  "he": "הַמִּשְׁנָה בְּאָבוֹת פֶּרֶק ד מִשְׁנָה יג: \"רַבִּי שִׁמְעוֹן אוֹמֵר, שְׁלֹשָׁה כְתָרִים הֵם: כֶּתֶר תּוֹרָה, וְכֶתֶר כְּהוּנָּה, וְכֶתֶר מַלְכוּת, וְכֶתֶר שֵׁם טוֹב עוֹלֶה עַל גַּבֵּיהֶן\". שְׁלוֹשֶׁת הַכְּתָרִים: כְּהוּנָּה, תּוֹרָה וּמַלְכוּת הֵם בְּחִינַת שְׁלוֹשֶׁת הָרְגָלִים. \"כֶּתֶר שֵׁם טוֹב עוֹמֵד עַל גַּבֵּיהֶם\", וְהוּא בְּחִינַת הַשַּׁבָּת, שֶׁהִיא מוֹפִיעָה אֶת שְׁמוֹ שֶׁל הקב\"ה \"שָׁלוֹם\", מִלְּשׁוֹן שְׁלֵמוּת. כֶּתֶר מְסַמֵּל אֶת עֻבְדַּת הֱיוֹת הַתְּכוּנָה שֶׁהוּא נוֹשֵׂא בָּאָדָם הַנּוֹשֵׂא אוֹתוֹ (לְמָשָׁל: אָנוּ אוֹמְרִים שֶׁאָדָם מוּכְתָּר בְּנִמּוּסִים, כְּלוֹמַר הַמַּעֲלָה הַזּוֹ נִמְצֵאת בּוֹ, הוּא מְסֻמָּן בְּמַעֲלוֹת אֵלּוּ. אוֹ לְמָשָׁל: הִכְתִּירוּ אָדָם לְתַפְקִיד מְסֻיָּם - יֵשׁ לוֹ הַמַּעֲלָה הַזּוֹ). מַהוּ אִם כֵּן \"כֶּתֶר שֵׁם טוֹב\"? בְּעֶצֶם, אָדָם מוּכְתָּר לֹא בְּמַעֲלָה פְּרָטִית מְסֻיֶּמֶת אֶלָּא בְּמִכְלוֹל הַפְּרָטִים שֶׁלּוֹ, בִּשְׁמוֹ. יֵשׁ לוֹ תְּכוּנָה כּוֹלֶלֶת שֶׁל מַעֲלָה. זוֹהִי הַשַּׁבָּת בְּיַחַס לַמּוֹעֲדִים.",
  "es": "La Mishná en Avot, capítulo 4, mishná 13: «Rabí Shimón dice: tres coronas hay: corona de Torá, corona de sacerdocio y corona de reinado, y la corona del buen nombre las supera a todas». Las tres coronas —sacerdocio, Torá y reinado— son el aspecto de las tres fiestas de peregrinación. «La corona del buen nombre está por encima de ellas», y es el aspecto del Shabat, que manifiesta el nombre del Santo, bendito sea, «Shalom», de la raíz de plenitud. La corona simboliza el hecho de que es una cualidad que lleva la persona que la porta (por ejemplo: decimos que alguien está «coronado» de buenos modales, es decir, esa virtud está en él, está marcado con esas virtudes; o, por ejemplo: coronaron a alguien para cierto cargo, y tiene esa virtud). ¿Qué es entonces la «corona del buen nombre»? En realidad, la persona coronada no lo está por una virtud particular concreta, sino por el conjunto de sus detalles, por su nombre: tiene una cualidad global de excelencia. Eso es el Shabat en relación con las fiestas."})

BLOQUES.append({"t": "par",
  "he": "הַשְּׂפַת אֱמֶת מוֹסִיף שֶׁשְּׁלֹשֶׁת הָרְגָלִים הֵם גַּם כְּנֶגֶד שְׁלוֹשֶׁת הָאָבוֹת, בְּחִינַת \"לְרֵיחַ שְׁמָנֶיךָ טוֹבִים\" - הַטּוֹבִים שֶׁבְּךָ, לְעוּמַּת הַשַּׁבָּת שֶׁהִיא שְׁמוֹ שֶׁל הקב\"ה \"שֶׁמֶן תּוּרַק שְׁמֶךָ\", וְהִיא מוֹפִיעָה מִלְּמַעְלָה לְמַטָּה (הרב חיים סמוטריץ). וְעַל פִּי הַגְּמָרָא בְּסוֹטָה יא: אֶפְשָׁר לְהוֹסִיף לִדְבָרָיו: (שמות א) \"וַיְהִי כִּי יָרְאוּ הַמְיַלְּדֹת אֶת הָאֱלֹהִים וַיַּעַשׂ לָהֶם בָּתִּים\" - רַב וּשְׁמוּאֵל, חַד אָמַר: בָּתֵּי כְּהוּנָּה וּלְוִיָּה, וְחַד אָמַר: בָּתֵּי מַלְכוּת. מַאן דְּאָמַר בָּתֵּי כְּהוּנָּה וּלְוִיָּה - אַהֲרֹן וּמֹשֶׁה; וּמַאן דְּאָמַר בָּתֵּי מַלְכוּת - דָּוִד נַמִי מִמִּרְיָם קָאָתֵי, דִּכְתִיב (דברי הימים א ב) וַתָּמָת עֲזוּבָה (אֵשֶׁת כָּלֵב) וַיִּקַּח לוֹ כָלֵב אֶת אֶפְרָת וַתֵּלֶד לוֹ אֶת חוּר, וּכְתִיב (שמואל א יז) וְדָוִד בֶּן אִישׁ אֶפְרָתִי וְגוֹ'.",
  "es": "El Sfat Emet añade que las tres fiestas de peregrinación corresponden también a los tres Patriarcas, en el aspecto de «por el aroma de tus buenos aceites» —lo bueno que hay en ti—, frente al Shabat, que es el nombre del Santo, bendito sea, «aceite derramado es tu nombre», y que se manifiesta de arriba hacia abajo (Rab Jaím Smotrich). Y según la Guemará en Sotá 11b se puede añadir a sus palabras: (Shemot 1) «y sucedió que, como las parteras temieron a Dios, Él les hizo casas» —Rav y Shmuel, uno dijo: casas de sacerdocio y levitas; y el otro dijo: casas de reinado. Quien dijo casas de sacerdocio y levitas [se refiere a] Aharón y Moshé; y quien dijo casas de reinado [se refiere a que] David también desciende de Miriam, pues está escrito (Divré HaIamim I, 2): «y murió Azuvá [esposa de Caleb], y tomó Caleb para sí a Efrat, que le dio a luz a Jur», y está escrito (Shmuel I, 17): «y David, hijo de un hombre efrateo», etc."})

BLOQUES.append({"t": "par",
  "he": "לְוִיָּה: מֹשֶׁה (פֶּסַח) - מֹשֶׁה שָׁקוּל לְיִשְׂרָאֵל. כְּהוּנָּה: אַהֲרֹן, סֻוכּוֹת - מַמְלֶכֶת כֹּהֲנִים וְגוֹי קָדוֹשׁ. מַלְכוּת: מִרְיָם, שָׁבוּעוֹת (מַאן מַלְכֵי? רַבָּנַן). יְהִי רָצוֹן שֶׁנִּזְכֶּה בְּעֶזְרַת הַשֵּׁם לְבִנְיַן בֵּית הַמִּקְדָּשׁ, וּכְנֶגֶד הַמַּתָּנוֹת שֶׁקִּיבַּלְנוּ בַּמִּדְבָּר, \"אִישׁ כְּמַתְּנַת יָדוֹ יִתֵּן\" וְלֹא יֵרָאֶה פָנָיו רֵיקָם.",
  "es": "Leviatán [mérito levita]: Moshé (Pésaj) — Moshé equivale a todo Israel. Sacerdocio: Aharón, Sucot — «reino de sacerdotes y nación santa». Reinado: Miriam, Shavuot («¿quiénes son reyes? los sabios»). Que merezcamos, con la ayuda de Dios, la construcción del Templo; y en correspondencia con los dones que recibimos en el desierto, «cada uno dará según el don de su mano», y no se presentará ante Él con las manos vacías."})

# ============================================================ ARTÍCULO 4 — los días de juicio, condición para la alegría
BLOQUES.append({"t": "titulo",
  "he": "בִּשְׁבִיל לִשְׂמֹוחַ בְּסֻוכּוֹת צָרִיךְ אֶת יְמֵי הַדִּין",
  "es": "Para poder alegrarse en Sucot hacen falta los días de juicio"})

BLOQUES.append({"t": "par",
  "he": "חֹדֶשׁ תִּשְׁרֵי הוּא הַחֹדֶשׁ הָרִאשׁוֹן בְּחָדְשֵׁי הַשָּׁנָה הַיְּהוּדִית. עֶרְכּוֹ שֶׁל חֹדֶשׁ זֶה בְּחַיֵּי הָאָדָם הַיְּהוּדִי מִתְבַּטֵּא בְּכָךְ שֶׁרֹוב חַגֵּי יִשְׂרָאֵל שֶׁהַתּוֹרָה צִוְּתָה עֲלֵיהֶם חָלִים בּוֹ. הַתּוֹרָה צִוְּתָה עַל חֲמִישָּׁה חַגִּים, וְאֵלּוּ הֵם: פֶּסַח, שָׁבוּעוֹת, רֹאשׁ הַשָּׁנָה, יוהכ\"פ וְסֻוכּוֹת. שְׁאָר הַחַגִּים הֵם מִתַּקָּנַת חֲזַ\"ל. נִמְצָא, שֶׁשְּׁלוֹשָׁה חַגִּים מִתּוֹךְ חֲמִישָּׁה חָלִים בְּחֹודֶשׁ זֶה - רֹאשׁ הַשָּׁנָה, יוהכ\"פ (כְּפִי שֶׁמְּכַנִּים אוֹתָם \"הַיָּמִים הַנּוֹרָאִים\") וְחַג הַסֻּוכּוֹת, חַג הַשִּׂמְחָה. הָבָה נִתְבּוֹנֵן וּנְתָאֵר לְפָנֵינוּ כֵּיצַד יְהוּדִי מְקַבֵּל פְּנֵי שָׁנָה חֲדָשָׁה, וְכֵיצַד מְקַבְּלָהּ אָדָם מֵאֻומּוֹת הָעוֹלָם. בְּסִפְרוֹ \"יַעֲטֶה מוֹרֶה\" מְבָאֵר הרב יעקב טראב שֶׁיֵּשׁ הֶפְרֵשׁ גָּדוֹל בֵּין שְׁתֵּי קַבָּלוֹת אֵלּוּ:",
  "es": "El mes de Tishré es el primer mes de los meses del año judío. El valor de este mes en la vida del judío se expresa en que la mayoría de las fiestas de Israel que la Torá ordenó caen en él. La Torá ordenó cinco fiestas, y son estas: Pésaj, Shavuot, Rosh HaShaná, Yom Kipur y Sucot; las demás fiestas son instauración de nuestros sabios. Resulta que tres fiestas de las cinco caen en este mes: Rosh HaShaná, Yom Kipur (tal como se los llama, «los Días Terribles») y la fiesta de Sucot, la fiesta de la alegría. Observemos y describamos cómo recibe un judío el rostro de un año nuevo, y cómo lo recibe una persona de las naciones del mundo. En su libro «Yaaté Moré», explica el Rab Yaakov Trab que hay una gran diferencia entre estas dos formas de recibirlo:"})

BLOQUES.append({"t": "par",
  "he": "אֻומּוֹת הָעוֹלָם שְׂמֵחִים בְּרֹאשׁ הַשָּׁנָה שֶׁלָּהֶם, אוֹכְלִים וְשׁוֹתִים וְעוֹרְכִים נִשְׁפֵי \"סִילְבֶסְטֶר\" עַל כָּל מְעַרֻמֵּיהֶם. הַמִּשְׁטָרָה עַצְמָהּ מְאַשֶּׁרֶת כִּי בְּיוֹם זֶה עֲמֵלָה הִיא מְאֹוד לִשְׁמֹר עַל הַסֵּדֶר, פֹּה וָשָׁם נִפְרָצוֹת חֲנֻיּוֹת וְנַעֲשִׂים מַעֲשִׂים לֹא רְצוּיִים אֲחֵרִים, מִלְּבַד תְּאוּנוֹת הַדְּרָכִים הַקָּשׁוֹת הַמִּתְרַחֲשׁוֹת בְּאוֹתוֹ יוֹם. לְעוּמַּת זֹאת, כְּשֶׁהַיְּהוּדִי עוֹמֵד לְקַבֵּל אֶת פְּנֵי הַשָּׁנָה הַחֲדָשָׁה, מֵכִין אֶת לִבּוֹ בַּאֲמִירַת סְלִיחוֹת מִסְפַּר יָמִים לִפְנֵי בּוֹא יוֹם רֹאשׁ הַשָּׁנָה. קָם בְּאַשְׁמֹרֶת הַבֹּקֶר לוֹמַר סְלִיחוֹת בְּחֶבְרַת יְהוּדִים אֲחֵרִים, וּסְלִיחוֹת אֵלּוּ נִתְּקְנוּ לְעוֹרֵר וְלַעֲרֹךְ חֶשְׁבּוֹן נֶפֶשׁ, לְשַׁפֵּר אֶת הִתְנַהֲגוּתוֹ וְאוֹרַח חַיָּיו. כְּשֶׁמַּגִּיעַ יוֹם עֶרֶב רֹאשׁ הַשָּׁנָה, אַנְשֵׁי מַעֲשֶׂה מִתְעַנִּים בְּאוֹתוֹ יוֹם, וְכָל אֶחָד מִתְחָרֵט עַל מַעֲשָׂיו הָרָעִים וּמְקַבֵּל עַל עַצְמוֹ שֶׁלֹּא לָשׁוּב לַדֶּרֶךְ הָרָעָה עוֹד. אַחַר כָּךְ מְטַהֵר אֶת עַצְמוֹ בְּמִקְווֵה טָהֳרָה לִקְרַאת הֶחָג, וּבֶחָג עַצְמוֹ מַרְבִּים בִּתְפִלָּה, תּוֹקְעִים בְּשׁוֹפָר כְּדֵי לְהִתְעוֹרֵר מֵהַתַּרְדֵּמָה וּמֵהַשִּׁגְרָתִיּוּת שֶׁל הַשָּׁנָה שֶׁחָלְפָה, וְלִזְכֹּר שֶׁהַיּוֹם הוּא יוֹם הַדִּין וְעָלָיו לְתַקֵּן אֶת מַעֲשָׂיו, דִּבּוּרוֹ וּמַחְשְׁבוֹתָיו. וְלֹא דַי בְּכָל זֶה, אֶלָּא גַּם אַחֲרֵי רֹאשׁ הַשָּׁנָה, בְּמֶשֶׁךְ עֲשָׂרָה יָמִים רְצוּפִים עַד יוהכ\"פ, עוֹבֵד הָאָדָם עַל עַצְמוֹ לְהָסִיר כָּל שֶׁמֶץ שֶׁל פְּגָם וּפְסוּל הַמַּחְשִׁיכִים אֶת אוֹר נִשְׁמָתוֹ.",
  "es": "Las naciones del mundo se alegran en su año nuevo, comen, beben y organizan fiestas de «Nochevieja» en total desenfreno. La propia policía reconoce que ese día trabaja mucho para mantener el orden: aquí y allá se asaltan tiendas y se cometen otros hechos indeseables, sin contar los graves accidentes de tráfico que ocurren ese mismo día. En cambio, cuando el judío está a punto de recibir el rostro del año nuevo, prepara su corazón diciendo <i>selijot</i> varios días antes de que llegue el día de Rosh HaShaná. Se levanta en la vigilia de la madrugada para decir <i>selijot</i> en compañía de otros judíos, y estas <i>selijot</i> se instauraron para despertar y hacer un examen de conciencia, para mejorar su comportamiento y su modo de vida. Cuando llega la víspera de Rosh HaShaná, los hombres de acción ayunan ese mismo día, y cada uno se arrepiente de sus malas obras y se compromete a no volver más al mal camino. Después se purifica en la <i>mikvé</i> de cara a la fiesta, y en la fiesta misma se multiplica en oración, se toca el shofar para despertar del letargo y de la rutina del año que pasó, y para recordar que ese día es día de juicio y que debe corregir sus obras, su habla y sus pensamientos. Y no basta con todo esto, sino que también después de Rosh HaShaná, durante diez días seguidos hasta Yom Kipur, la persona trabaja sobre sí misma para quitar todo rastro de defecto e invalidez que oscurezca la luz de su alma."})

BLOQUES.append({"t": "par",
  "he": "הֲכָנוֹתָיו שֶׁל הַיְּהוּדִי לְיוהכ\"פ מַגִּיעוֹת לְשִׂיאָן, כְּשֶׁבְּעֶרֶב יוהכ\"פ שׁוֹחֲטִים אֶת הַ\"כַּפָּרוֹת\" כְּדֵי שֶׁיַּעֲלֶה עַל דַּעְתּוֹ עַד כַּמָּה פָּגַם בְּנַפְשׁוֹ, וְהָיָה רָאוּי לְהֵיעָשׂוֹת בּוֹ כָּל מַה שֶּׁאֲנַחְנוּ עוֹשִׂים לַתַּרְנְגוֹל, מֵעֵין אַרְבַּע מִיתוֹת בֵּית דִּין - סְקִילָה, שְׂרֵיפָה, הֶרֶג וָחֶנֶק - עַל עֲווֹנוֹתָיו וְחֲטָאָיו.",
  "es": "Los preparativos del judío para Yom Kipur llegan a su culmen cuando en la víspera de Yom Kipur se degüellan las «<i>Kaparot</i>», para que se le ocurra hasta qué punto ha dañado su alma, y que sería digno de que se le hiciera a él todo lo que hacemos al gallo, a semejanza de las cuatro penas de muerte del tribunal —lapidación, incineración, decapitación y estrangulamiento— por sus faltas y pecados."})

BLOQUES.append({"t": "par",
  "he": "הִנֵּה מַגִּיעַ יוהכ\"פ, יוֹם הָאַדִּיר שֶׁבִּימֵי הַשָּׁנָה. בְּיוֹם זֶה מִתְיַיצֵּב הָאָדָם לִפְנֵי בּוֹרְאוֹ וּמִתְפַּלֵּל לֹא רַק עַל עַצְמוֹ אֶלָּא עַל כָּל הָעוֹלָם כּוּלּוֹ וּבִכְלָלָם גַּם אֻומּוֹת הָעוֹלָם, בַּחֲמִישָּׁה עִינּוּיִים קָשִׁים, וְרַק בְּסוֹף הַיּוֹם, אַחֲרֵי צֵאת הַכּוֹכָבִים, מְבַשֶּׂרֶת תְּקִיעַת הַשּׁוֹפָר אֶת סִיּוּם הַיּוֹם הַקָּדוֹשׁ, וְאָז כָּל יִשְׂרָאֵל אוֹמְרִים אֶת הַפָּסוּק: \"לֵךְ אֱכֹל בְּשִׂמְחָה לַחְמֶךָ וּשְׁתֵה בְלֶב טוֹב יֵינֶךָ כִּי כְבָר רָצָה הָאֱלֹהִים אֶת מַעֲשֶׂיךָ\".",
  "es": "He aquí que llega Yom Kipur, el día más imponente del año. En este día la persona se presenta ante su Creador y reza no solo por sí misma, sino por el mundo entero y, entre ellos, también por las naciones del mundo, con cinco severas aflicciones; y solo al final del día, después de la salida de las estrellas, el toque del shofar anuncia el final del día santo, y entonces todo Israel dice el versículo: «Ve, come con alegría tu pan y bebe con buen corazón tu vino, pues ya ha aceptado Dios tus obras»."})

BLOQUES.append({"t": "par",
  "he": "מִכָּל הָאָמוּר אֲנַחְנוּ לוֹמְדִים, שֶׁרַק אַחֲרֵי עֲבוֹדָה מְאֻומֶּצֶת בְּמֶשֶׁךְ חָמֵשׁ - עֶשְׂרֵה יוֹם לְפָחוֹת בִּתְחִילַּת הַשָּׁנָה, הַיְּהוּדִי מַרְשֶׁה לְעַצְמוֹ לִשְׂמֹוחַ בְּחַג הַסֻּוכּוֹת, כְּדִבְרֵי הַפָּסוּק \"וְשָׂמַחְתָּ בְּחַגֶּךָ\". וְאוּלַי מִן הָרָאוּי שֶׁכָּל אָדָם יִבְדֹּוק אֶת עַצְמוֹ הַאִם בֶּאֱמֶת הוּא יָכוֹל לְהַגִּיעַ לְחַג הַסֻּוכּוֹת כְּדֵי שֶׁיִּתְקַיֵּם בּוֹ \"וְשָׂמַחְתָּ בְּחַגֶּךָ\", וְהַאִם הוּא בֶּאֱמֶת עָבַר אֶת כָּל הַשְּׁלָבִים הַמֻּקְדָּמִים לִפְנֵי הַגִּיעוֹ לְחַג הַסֻּוכּוֹת וְשִׂמְחַת תּוֹרָה כָּרָאוּי. רַק אָדָם שֶׁעָשָׂה אֶת הַהֲכָנָה הָרְאוּיָה וְעָמַד בְּדִרִישׁוֹתָיו שֶׁל הקב\"ה, הוּא זֶה הַיָּכוֹל עַתָּה בְּחַג הַסֻּוכּוֹת לְהַרְגִּישׁ שִׂמְחָה אֲמִיתִּית.",
  "es": "De todo lo dicho aprendemos que solo después de un trabajo intenso durante cinco a diez días como mínimo, al empezar el año, el judío se permite alegrarse en la fiesta de Sucot, conforme a las palabras del versículo «y te alegrarás en tu fiesta». Y quizás convendría que cada persona se examinara a sí misma: si de verdad puede llegar a la fiesta de Sucot para que se cumpla en él «y te alegrarás en tu fiesta», y si de verdad pasó por todas las etapas previas antes de llegar a la fiesta de Sucot y de Simjat Torá como es debido. Solo la persona que hizo la preparación adecuada y cumplió con las exigencias del Santo, bendito sea, es la que ahora, en la fiesta de Sucot, puede sentir una alegría verdadera."})

BLOQUES.append({"t": "par",
  "he": "עַל מְנָת לְהַמְחִישׁ אֶת הַדְּבָרִים בְּיֶתֶר שְׂאֵת, נוּכַל לְהִתְבּוֹנֵן בַּאֲנָשִׁים הַמַּגִּיעִים לְשִׂמְחַת תּוֹרָה וּמְנַשְּׁקִים אֶת סִפְרֵי הַתּוֹרָה, וְלִפְעָמִים אָנוּ רוֹאִים רִקּוּדִים בָּרְחוֹבוֹת עִם סֵפֶר תּוֹרָה, וְיֵשׁ אֲנָשִׁים הָעוֹצְרִים מְכוֹנִיּוֹתֵיהֶם וּמְנַשְּׁקִים אֶת סִפְרֵי הַתּוֹרָה. אָכֵן, זֶה טוֹב וְיָפֶה, אַךְ הַשְּׁאֵלָה הִיא: הַאִם גַּם הַתּוֹרָה שְׂמֵחָה בִּנְשִׁיקָה שֶׁל אוֹתוֹ יְהוּדִי שֶׁלֹּא רָאָה אוֹתָהּ כָּל הַשָּׁנָה... הֲרֵי בְּשִׂמְחַת תּוֹרָה זוֹ שִׂמְחָתָהּ שֶׁל הַתּוֹרָה שֶׁהִנֵּה זָכוּ לְסַיֵּים אוֹתָהּ בְּיוֹם זֶה, וְיֵשׁ כָּאֵלּוּ שֶׁלֹּא רַק שֶׁלֹּא זָכוּ לְסַיְּימָהּ אֶלָּא אֲפִילּוּ לֹא הִתְחִילוּ לִלְמֹוד בָּהּ. הַאִם חָתָן שֶׁנֶּעֱלַם לְכַלָּתוֹ בְּמֶשֶׁךְ שָׁנָה שְׁלֵמָה וּלְאַחַר שָׁנָה יָבוֹא, הַאִם יָעֵז לְהִיכָּנֵס לְבֵיתוֹ? לְצַעֲרֵנוּ, יֵשׁ אֲנָשִׁים שֶׁהֵם רוֹאִים אֶת סֵפֶר הַתּוֹרָה פַּעַם אוֹ פַּעֲמַיִים בַּשָּׁנָה וְתוּ לֹא. אִי אֶפְשָׁר לְהַגִּיעַ פִּתְאוֹם לְחַג שִׂמְחַת תּוֹרָה וְלִשְׂמֹוחַ בְּשִׂמְחָתָהּ שֶׁל הַתּוֹרָה, כָּל הַשִּׂמְחָה בֶּחָג צְרִיכָה לְהַגִּיעַ אַחַר עָמָל, יְגִיעָה, תְּפִילּוֹת, הִתְעַלֻּויּוֹת וְקַבָּלוֹת חֲדָשׁוֹת. כָּךְ יָאֶה לְהַגִּיעַ לְהקב\"ה וּלְקַיֵּים בּוֹ אֶת מִצְוַות שִׂמְחַת הֶחָג. מִכָּאן מִתְבַּקֶּשֶׁת הַמַּסְקָנָה, שֶׁשִּׂמְחָה אֲמִיתִּית דַּרְכָּהּ לָבוֹא אַחֲרֵי עֲבוֹדָה מְאֻומֶּצֶת שֶׁל רֹאשׁ הַשָּׁנָה, עֲשֶׂרֶת יְמֵי תְּשׁוּבָה, יוֹם הַכִּיפּוּרִים, וּלְבַסּוֹף, לְאַחַר שֶׁכָּל הַהֲכָנוֹת הוּשְׁלְמוּ, נִיתָּן לְקַיֵּים אֶת צִיוּוּי הקב\"ה \"וְשָׂמַחְתָּ בְּחַגֶּךָ\".",
  "es": "Para ilustrar más las cosas, podemos observar a las personas que llegan a Simjat Torá y besan los rollos de la Torá, y a veces vemos bailes por las calles con el Séfer Torá, y hay personas que detienen sus coches y besan los rollos de la Torá. Ciertamente eso es bueno y hermoso, pero la pregunta es: ¿también la Torá se alegra con el beso de ese judío que no la vio en todo el año...? Al fin y al cabo, en esta Simjat Torá está la alegría de la Torá porque hemos merecido terminarla en este día, y hay quienes no solo no merecieron terminarla, sino que ni siquiera empezaron a estudiarla. ¿Acaso un novio que desapareció de su novia durante un año entero y, al cabo del año, viene, se atrevería a entrar en su casa? Para nuestro pesar, hay personas que ven el Séfer Torá una o dos veces al año y nada más. No se puede llegar de repente a la fiesta de Simjat Torá y alegrarse con la alegría de la Torá: toda la alegría de la fiesta debe llegar después de esfuerzo, fatiga, plegarias, elevaciones y nuevos compromisos. Así conviene llegar ante el Santo, bendito sea, y cumplir en Él la mitzvá de la alegría de la fiesta. De aquí se desprende la conclusión de que la alegría verdadera tiene por costumbre venir después del trabajo intenso de Rosh HaShaná, los Diez Días de <i>Teshuvá</i> y Yom Kipur; y al final, después de que se completaron todos los preparativos, se puede cumplir el mandato del Santo, bendito sea, «y te alegrarás en tu fiesta»."})

BLOQUES.append({"t": "saludo",
  "he": "שַׁבָּת שָׁלוֹם וּמְבוֹרָךְ, קַיִיץ בָּרִיא וּגְאֻולָּה בְּרַחֲמִים אכיר\"ר.",
  "es": "Shabat shalom y bendecido, un verano saludable y redención con misericordia, <i>amén, ken yehí ratzón</i>."})
