# -*- coding: utf-8 -*-
"""Cierre del artículo de los Ushpizín + columna de halajot (siman 519) + pie de anuncios."""

BLOQUES = []

BLOQUES.append({"t": "par",
  "he": "אַבְרָהָם נוֹתֵן לָנוּ בַּיּוֹם הָרִאשׁוֹן מִמִּידַּת הַחֶסֶד, יִצְחָק אָבִינוּ נוֹתֵן לָנוּ מִמִּידַּת הַגְּבוּרָה שֶׁלּוֹ, הִתְגַּבְּרוּת עַל הַיֵּצֶר, יַעֲקֹב נוֹתֵן לָנוּ תּוֹרָה וְכֵן הָלְאָה... וְלָכֵן בְּיוֹם טוֹב רִאשׁוֹן הוּא \"רִאשׁוֹן לְחֶשְׁבּוֹן עֲווֹנוֹת\", שֶׁאָז יִשְׂרָאֵל מַתְחִילִים לִפְרֹועַ אֶת חֶשְׁבּוֹן עֲווֹנוֹת, כַּאֲשֶׁר בְּמֶשֶׁךְ יְמֵי הֶחָג מַגִּיעִים כָּל הָאֻושְׁפִּיזִין, נִתְקַבֵּץ לָנוּ מִזְּכֻויּוֹתֵיהֶם וּמִידּוֹתֵיהֶם הַטּוֹבוֹת סְכוּם הָגוּן דַּי וְהוֹתֵר לִפְרֹועַ כָּל חוֹבַת עֲווֹנוֹתֵינוּ, וְאָז אָנוּ עוֹשִׂים מֵרֹוב שִׂמְחָה: שִׂמְחַת תּוֹרָה!...",
  "es": "Avraham nos da el primer día de la cualidad de la bondad; Itzjak, nuestro padre, nos da de su cualidad del rigor, la victoria sobre el <i>iétzer</i>; Yaakov nos da Torá, y así sucesivamente... Y por eso el primer día de fiesta es «primero para la cuenta de los pecados», pues entonces Israel empieza a saldar la cuenta de los pecados, cuando durante los días de la fiesta llegan todos los <i>Ushpizín</i>, se nos reúne de sus méritos y de sus buenas cualidades una suma respetable, más que suficiente para saldar toda la deuda de nuestros pecados, y entonces hacemos, de tanta alegría, ¡Simjat Torá!..."})

BLOQUES.append({"t": "titulo",
  "he": "פִּנַּת הַהֲלָכָה - סִימָן תקי\"ט: דִּינֵי שִׂמְחָה בְּיוֹם טוֹב",
  "es": "El rincón de la halajá — Siman 519: las leyes de la alegría en Yom Tov"})

HALAJOT = [
 ("א", "מִצְוַות יוֹם טוֹב לְחַלְּקוֹ, חֶצְיוֹ לְבֵית הַכְּנֶסֶת וּלְבֵית הַמִּדְרָשׁ וְחֶצְיוֹ לַאֲכִילָה וּשְׁתִיָּה וְשִׂמְחָה.",
  "La mitzvá del Yom Tov es dividirlo: la mitad para la sinagoga y la casa de estudio, y la mitad para comer, beber y alegrarse."),
 ("ב", "כְּשֵׁם שֶׁמִּצְוָה לְכַבֵּד וּלְעַנֵּג אֶת הַשַּׁבָּת, שֶׁנֶּאֱמַר \"וְקָרָאתָ לַשַּׁבָּת עֹונֶג\", כָּךְ מִצְוָה לְכַבֵּד וּלְעַנֵּג יָמִים טוֹבִים, שֶׁנֶּאֱמַר \"לִקְדוֹשׁ ה' מְכֻבָּד\". וּבְכָל יָמִים טוֹבִים נֶאֱמַר בָּהֶם \"מִקְרָא קוֹדֶשׁ\", וְלָכֵן רָאוּי לָאָדָם שֶׁלֹּא יִסְעַד בְּעַרְבֵי יָמִים טוֹבִים מִן הַמִּנְחָה וּלְמַעְלָה, כְּמוֹ בְּעֶרֶב שַׁבָּת, שֶׁדָּבָר זֶה מִכְּלַל הַכָּבוֹד שֶׁל שַׁבָּת וְיוֹם טוֹב. וְאִם חָל עֶרֶב יוֹם טוֹב בְּשַׁבָּת, מֻותָּר לַעֲשׂוֹת סְעֻודָּה שְׁלִישִׁית אֲפִילּוּ אַחֲרֵי מִנְחָה קְטַנָּה, רַק שֶׁלֹּא יֹאכַל מִן הַפַּת אֶלָּא עַד כְּבֵיצָה, כְּדֵי שֶׁיִּהְיֶה תָּאֵב לֶאֱכֹול בַּלַּיְלָה לִכְבוֹד יוֹם טוֹב.",
  "Así como es mitzvá honrar y agasajar el Shabat, como está dicho «y llamarás al Shabat delicia», así es mitzvá honrar y agasajar los días de fiesta, como está dicho «al santo del Eterno, honrado». Y en todos los días de fiesta está dicho de ellos «convocación santa»; por eso conviene que la persona no coma en las vísperas de los días de fiesta desde <i>minjá</i> en adelante, igual que en víspera de Shabat, pues esto forma parte del honor del Shabat y del Yom Tov. Y si la víspera de Yom Tov cae en Shabat, está permitido hacer la tercera comida incluso después de <i>minjá ktaná</i>, solo que no coma pan más de la medida de un huevo, para que tenga apetito de comer por la noche en honor del Yom Tov."),
 ("ג", "אַל יְצַמְצֵם אָדָם בְּהוֹצָאוֹתָיו לִכְבוֹד יוֹם טוֹב, וּכְמוֹ שֶׁאָמַר הקב\"ה לְיִשְׂרָאֵל: \"בָּנַי! לְווּ עָלַי וְקַדְּשׁוּ קְדֻשַּׁת הַיּוֹם, וַאֲנִי פּוֹרֵעַ\" (ביצה טו:). וּכְשֵׁם שֶׁבְּשַׁבָּת יֵשׁ נְשָׁמָה יְתֵרָה לָאָדָם, כָּךְ בְּיוֹם טוֹב, וְלָכֵן תִּקְּנוּ חֲזַ\"ל לוֹמַר בִּתְפִלַּת שַׁחֲרִית שֶׁל יוֹם טוֹב \"נִשְׁמַת כָּל חַי\" כְּמוֹ שֶׁאוֹמְרִים בְּשַׁבָּת. וְצָרִיךְ לִלְבֹּושׁ בְּגָדִים נָאִים לִכְבוֹד יוֹם טוֹב, וּבִגְדֵי יוֹם טוֹב יִהְיוּ יוֹתֵר טוֹבִים מֵהַבְּגָדִים שֶׁל שַׁבָּת.",
  "Que la persona no se limite en sus gastos en honor del Yom Tov, como dijo el Santo, bendito sea, a Israel: «¡Hijos míos! Tomad prestado a cuenta mía y santificad la santidad del día, que Yo pagaré» (Beitzá 15b). Y así como en Shabat hay un alma extra para la persona, así en Yom Tov; por eso instituyeron nuestros sabios decir en la <i>Shajarit</i> de Yom Tov «<i>Nishmat Kol Jai</i>», igual que se dice en Shabat. Y hay que vestir ropas elegantes en honor del Yom Tov, y las ropas de Yom Tov serán mejores que las de Shabat."),
 ("ד", "כְּשֵׁם שֶׁבְּשַׁבָּת אָסוּר לִטְעֹום כְּלוּם קֹודֶם הַקִּידּוּשׁ, וַאֲפִילּוּ מַיִם, כָּךְ בְּיוֹם טוֹב אָסוּר לִטְעֹום כְּלוּם קֹודֶם הַקִּידּוּשׁ שֶׁל יוֹם טוֹב. וּכְשֵׁם שֶׁהַנָּשִׁים חַייָּבוֹת בְּקִידּוּשׁ שֶׁל שַׁבָּת בִּכְנִיסָתוֹ, כָּךְ חַייָּבוֹת בְּקִידּוּשׁ שֶׁל יוֹם טוֹב, וּמוֹצִיאוֹת אֶת הָאֲנָשִׁים יְדֵי חוֹבָתָם. וְגַם אֵין קִידּוּשׁ שֶׁל יוֹם טוֹב אֶלָּא בִּמְקוֹם סְעֻודָּה. וְהַקִּידּוּשׁ בְּיוֹם טוֹב, לְדַעַת רֹוב הַפּוֹסְקִים, הוּא מִצְוָה מִן הַתּוֹרָה.",
  "Así como en Shabat está prohibido probar algo antes del <i>kidush</i>, incluso agua, así en Yom Tov está prohibido probar algo antes del <i>kidush</i> de Yom Tov. Y así como las mujeres están obligadas en el <i>kidush</i> de Shabat a su entrada, así están obligadas en el <i>kidush</i> de Yom Tov, y eximen a los hombres de su obligación. Y tampoco hay <i>kidush</i> de Yom Tov sino en el lugar de la comida. Y el <i>kidush</i> en Yom Tov, según la mayoría de los <i>poskim</i>, es mitzvá de la Torá."),
 ("ה", "אִם לֹא קִדֵּשׁ בְּלֵיל יוֹם טוֹב עַל הַכּוֹס, בֵּין בְּשׁוֹגֵג בֵּין בְּמֵזִיד, יָכוֹל לְקַדֵּשׁ בְּשַׁחֲרִית אֶת הַקִּידּוּשׁ שֶׁל הַלַּיְלָה. וְכֵן אִם נֶאֱנַס וְלֹא סָעַד בַּלַּיְלָה הָרִאשׁוֹן שֶׁל הֶחָג, יֹאכַל עוֹד סְעֻודָּה בַּיּוֹם לְהַשְׁלִים מִצְוַות סְעֻודּוֹת יוֹם טוֹב.",
  "Si no hizo el <i>kidush</i> sobre la copa en la noche de Yom Tov, ya sea por error o intencionadamente, puede hacer en <i>Shajarit</i> el <i>kidush</i> de la noche. Y asimismo, si se vio impedido por fuerza mayor y no cenó la primera noche de la fiesta, comerá otra comida durante el día para completar la mitzvá de las comidas de Yom Tov."),
 ("ו", "חַיָּיב לִבְצֹועַ עַל שְׁתֵּי כִּכָּרוֹת בְּיוֹם טוֹב כְּמוֹ בְּשַׁבָּת, שֶׁצָּרִיךְ לֶחֶם מִשְׁנֶה גַּם בְּיוֹם טוֹב.",
  "Está obligado a partir el pan sobre dos panes en Yom Tov, igual que en Shabat, pues hace falta <i>léjem mishné</i> también en Yom Tov."),
 ("ז", "אֵין צָרִיךְ לַעֲשׂוֹת בְּיוֹם טוֹב שָׁלֹשׁ סְעֻודּוֹת, אֶלָּא דַּי בִּשְׁתַּיִם.",
  "No hace falta hacer en Yom Tov tres comidas, sino que basta con dos."),
 ("ח", "מֻותָּר לַעֲשׂוֹת סְעֻודַּת סִיּוּם מַסֶּכֶת בְּיוֹם טוֹב עִם הַסְּעֻודָּה שֶׁל הֶחָג, וְאֵין בָּזֶה מִשּׁוּם \"אֵין עוֹשִׂים מִצְות חֲבִילוֹת חֲבִילוֹת\", מִכֵּיוָן שֶׁבְּמַעֲשֶׂה אֶחָד פּוֹטֵר אֶת שְׁנֵיהֶם.",
  "Está permitido hacer la comida de <i>siyum masejet</i> en Yom Tov junto con la comida de la fiesta, y no hay en esto el problema de «no se hacen las mitzvot en fajos», ya que con un solo acto cumple con ambas."),
 ("ט", "חַיָּיב אָדָם לִהְיוֹת שָׂמֵחַ בְּיוֹם טוֹב, וְאֵין שִׂמְחָה לַאֲנָשִׁים אֶלָּא בְּבָשָׂר וְיַיִן, וְעִיקַּר הַחִיּוּב הוּא בִּבְשַׂר בְּהֵמָה, וּמִי שֶׁאֵינוֹ יָכוֹל לֶאֱכֹול בְּיוֹם טוֹב בְּשַׂר בְּהֵמָה מִטַּעֲמֵי בְּרִיאוּת אוֹ כַּשְׁרוּת, יְקַיֵּים מִצְות שִׂמְחָה שֶׁל יוֹם טוֹב בִּבְשַׂר עוֹף. וְאִם אֵין יָדוֹ מַשֶּׂגֶת לִקְנוֹת בָּשָׂר וְיַיִן אֶלָּא אֶחָד מֵהֶם, יֵשׁ לְהַעֲדִיף יַיִן, שֶׁבִּזְמַן הַזֶּה עִיקַּר הַשִּׂמְחָה בְּיַיִן. וְאַף הַנָּשִׁים חַייָּבוֹת בְּשִׂמְחַת יוֹם טוֹב, וְהַנָּשִׁים יֵשׁ לְשַׂמְּחָן בְּבָגָדִים יָפִים וְתַכְשִׁיטִין נָאִים. וְהַקְּטַנִּים מְשַׂמְּחָם בִּקְלָיוֹת וֶאֱגוֹזִים וּמַמְתַּקִּים. וְאַף עַל פִּי שֶׁהוּא שָׂמֵחַ בְּבָשָׂר וּבְיַיִן בְּיוֹם טוֹב, לֹא יִמָּשֵׁךְ יוֹתֵר מִדַּי אַחֲרֵיהֶם, וּבִשְׂחוֹק וְקַלּוּת רֹאשׁ, לְפִי שֶׁאֵין הַשְּׂחוֹק וְקַלּוּת רֹאשׁ שִׂמְחָה שֶׁל מִצְוָוה, אֶלָּא הוֹלֵלוּת וְסִכְלוּת, וְלֹא נִצְטַוֵּינוּ בַּתּוֹרָה אֶלָּא עַל שִׂמְחָה שֶׁיֵּשׁ בָּהּ עֲבוֹדַת הַשֵּׁם יִתְבָּרַךְ.",
  "La persona está obligada a estar alegre en Yom Tov, y no hay alegría para los hombres sino con carne y vino, y la obligación principal es con carne de res; y quien no pueda comer en Yom Tov carne de res por razones de salud o de <i>kashrut</i>, cumplirá la mitzvá de alegría de Yom Tov con carne de ave. Y si no le alcanza para comprar carne y vino sino solo uno de los dos, hay que preferir el vino, pues en nuestro tiempo la alegría principal está en el vino. Y también las mujeres están obligadas en la alegría de Yom Tov, y a las mujeres hay que alegrarlas con ropas bonitas y joyas elegantes. Y a los pequeños se los alegra con semillas tostadas, nueces y dulces. Y aunque se alegre con carne y vino en Yom Tov, no se deje arrastrar demasiado tras ellos, ni con risa y ligereza de cabeza, porque la risa y la ligereza de cabeza no son alegría de mitzvá, sino desenfreno y necedad, y no se nos ordenó en la Torá sino sobre la alegría que contiene en ella el servicio de Dios, bendito sea."),
 ("י", "הַחִיּוּב עַל הַנָּשִׁים עַצְמָן לִשְׂמֹוחַ בְּיוֹם טוֹב, וְלֹא עַל הַבְּעָלִים לְשַׂמְּחָן, אֶלָּא שֶׁאִם יֵשׁ בְּאֶפְשָׁרוּתָם צְרִיכִים לִקְנוֹת לָהֶם בְּגָדִים כְּדֵי לְשַׂמְּחָן.",
  "La obligación recae sobre las propias mujeres de alegrarse en Yom Tov, no sobre los maridos de alegrarlas; salvo que, si está en su posibilidad, deben comprarles ropa para alegrarlas."),
 ("יא", "חַיָּיב אָדָם לְשַׂמֵּחַ עִמּוֹ בָּרֶגֶל אֶת הָעֲנִיִּים וְהָאֶבְיוֹנִים וְאֶת הָאַלְמָנוֹת וְהַיְתוֹמִים, שֶׁכָּךְ נֶאֱמַר (דברים טז, יד): \"וְשָׂמַחְתָּ בְּחַגֶּךָ אַתָּה וּבִנְךָ וּבִתֶּךָ, וְהַלֵּוִי וְהַגֵּר וְהַיָּתוֹם וְהָאַלְמָנָה אֲשֶׁר בְּקִרְבֶּךָ\". וְלָכֵן יֵשׁ לִשְׁלֹוחַ לָהֶם דֶּרֶךְ כָּבוֹד מֵעֶרֶב יוֹם טוֹב דִּבְרֵי מַאֲכָל וּמַשְׁתֶּה בְּעַיִן יָפָה, דֵּי מַחְסוֹרָם אֲשֶׁר יֶחְסַר לָהֶם, כְּדֵי לְשַׂמְּחָם. אֲבָל מִי שֶׁנּוֹעֵל דַּלְתוֹת בֵּיתוֹ, וְאוֹכֵל וְשׁוֹתֶה עִם אִשְׁתּוֹ וּבָנָיו בִּלְבַד, וְאֵינוֹ מְשַׂמֵּחַ אֶת הָעֲנִיִּים וּמָרֵי נֶפֶשׁ, אֵין זוֹ שִׂמְחַת מִצְוָה שֶׁל הֶחָג, אֶלָּא שִׂמְחַת כְּרֵסוֹ, וְעַל הָעוֹשִׂים כֵּן נֶאֱמַר (הושע ט, ד): \"זִבְחֵיהֶם כְּלֶחֶם אוֹנִים לָהֶם, כָּל אֹוכְלָיו יִטַּמָּאוּ, כִּי לַחְמָם לְנַפְשָׁם\". וְשִׂמְחָה כָּזֹאת קָלוֹן הִיא לָהֶם, שֶׁנֶּאֱמַר (מלאכי ב, ג): \"וְזֵרִיתִי פֶרֶשׁ עַל פְּנֵיכֶם, פֶּרֶשׁ חַגֵּיכֶם\".",
  "La persona está obligada a alegrar junto con ella, en la fiesta, a los pobres y a los necesitados, y a las viudas y a los huérfanos, pues así está dicho (Devarim 16:14): «y te alegrarás en tu fiesta, tú, y tu hijo, y tu hija, y el levita, y el extranjero, y el huérfano y la viuda que están en tus puertas». Por eso hay que enviarles, con honor, desde la víspera de Yom Tov, alimentos y bebidas con buen ojo, lo que les falte de lo que necesiten, para alegrarlos. Pero quien cierra las puertas de su casa y come y bebe solo con su esposa y sus hijos, y no alegra a los pobres y a los de ánimo amargado, esa no es la alegría de mitzvá de la fiesta, sino la alegría de su vientre; y sobre los que hacen así está dicho (Hoshea 9:4): «sus sacrificios serán para ellos como pan de duelo, todos los que coman de él se contaminarán, porque su pan es solo para sí mismos». Y una alegría así es vergüenza para ellos, como está dicho (Malají 2:3): «esparciré excremento sobre vuestros rostros, el excremento de vuestras fiestas»."),
 ("יב", "בִּזְמַן שֶׁהָיָה בֵּית הַמִּקְדָּשׁ קַיָּם, הָיְתָה מִצְוָה עַל יִשְׂרָאֵל לְשַׂמֵּחַ אֶת הַכֹּהֲנִים הַלְוִיִּים שׁוֹמְרֵי מִשְׁמֶרֶת הַמִּקְדָּשׁ, וְעוֹבְדִים בְּכָל כֹּחָם בְּהַקְרָבַת הַקָּרְבָּנוֹת, וְגַם הָיוּ מוֹרִים הוֹרָאוֹת בְּיִשְׂרָאֵל, כְּמוֹ שֶׁנֶּאֱמַר (דברים לג, ח): \"וּלְלֵוִי אָמַר...\" וְגוֹ', \"יוֹרוּ מִשְׁפָּטֶיךָ לְיַעֲקֹב וְתוֹרָתְךָ לְיִשְׂרָאֵל\". וְכֵן נֶאֱמַר: \"וְהַכֹּהֲנִים הַלְוִיִּם בְּנֵי צָדוֹק...\" וְגוֹ' \"וְאֶת עַמִּי יוֹרוּ\". וְהֵם בִּכְלַל מַה שֶּׁנֶּאֱמַר \"וְשָׂמַחְתָּ בְּחַגֶּךָ אַתָּה... וְהַלֵּוִי\", וְכֵן נֶאֱמַר: \"הִשָּׁמֶר לְךָ פֶּן תַּעֲזֹב אֶת הַלֵּוִי כָּל יָמֶיךָ עַל אַדְמָתֶךָ\". וּבִזְמַן הַזֶּה, שֶׁבַּעֲווֹנוֹת הָרַבִּים בָּטְלָה עֲבוֹדַת הַמִּקְדָּשׁ, מִצְוָה לְשַׂמֵּחַ בָּרֶגֶל אֶת הָאַבְרֵכִים שֶׁלּוֹמְדִים תּוֹרָה יוֹמָם וָלַיְלָה, וּמוֹרִים הוֹרָאוֹת לְיִשְׂרָאֵל, שֶׁהֵם בִּמְקוֹם הַכֹּהֲנִים הַלְוִיִּים, כְּמוֹ שֶׁאָמְרוּ בִּמְנָחוֹת (קי.), תַּלְמִידֵי חֲכָמִים שֶׁעוֹסְקִים בַּתּוֹרָה מַעֲלֶה עֲלֵיהֶם הַכָּתוּב כְּאִילּוּ עוֹסְקִים בַּעֲבוֹדַת בֵּית הַמִּקְדָּשׁ.",
  "Cuando existía el Beit HaMikdash, había mitzvá sobre Israel de alegrar a los cohanim levitas, guardianes de la guardia del Templo, que trabajaban con todas sus fuerzas en ofrecer los sacrificios, y que además enseñaban las leyes a Israel, como está dicho (Devarim 33:8): «y a Leví dijo...», etc., «enseñarán Tus juicios a Yaakov y Tu Torá a Israel». Y asimismo está dicho: «y los cohanim levitas, hijos de Tzadok...», etc., «enseñarán a Mi pueblo». Y ellos están incluidos en lo que está dicho «y te alegrarás en tu fiesta, tú... y el levita», y asimismo está dicho: «cuídate de no abandonar al levita todos tus días sobre tu tierra». Y en nuestro tiempo, en que por los muchos pecados cesó el servicio del Templo, es mitzvá alegrar en la fiesta a los <i>avrejim</i> que estudian Torá de día y de noche, y enseñan las leyes a Israel, que están en lugar de los cohanim levitas, como dijeron en Menajot (110a): a los <i>talmidé jajamim</i> que se ocupan de la Torá, la Escritura los considera como si se ocuparan del servicio del Templo."),
 ("יג", "חַיָּיב אָדָם לְהַקְבִּיל פְּנֵי רַבּוֹ בָּרֶגֶל (ראש השנה טז:). וְיֵשׁ אוֹמְרִים שֶׁמִּצְוָה לְבַקֵּר אֶת רַבּוֹ בְּכָל רֶגֶל, וְיֵשׁ אוֹמְרִים שֶׁאֵין מִצְוָה זוֹ נוֹהֶגֶת בִּזְמַן הַזֶּה.",
  "La persona está obligada a recibir el rostro de su maestro en la fiesta (Rosh HaShaná 16b). Y hay quienes dicen que es mitzvá visitar al maestro en cada fiesta, y hay quienes dicen que esta mitzvá no rige en nuestro tiempo."),
 ("יד", "וּמִכָּל מָקוֹם לֹא נָכוֹן שֶׁיַּעֲזֹב אָדָם בָּרֶגֶל אֶת אִשְׁתּוֹ וּבָנָיו, וְיֵלֵךְ לְמַסָּעָיו אֶל רַבּוֹ הַחוֹנֶה בְּעִיר אַחֶרֶת, לִשְׁבֹּת שָׁם בְּיוֹם טוֹב, אוֹ בְּרֹאשׁ הַשָּׁנָה, כְּדֵי שֶׁיְּקַיֵּם מִצְוָה לְהַקְבִּיל פְּנֵי רַבּוֹ בָּרֶגֶל; שֶׁהֲרֵי מִצְוָה מִן הַתּוֹרָה לִשְׂמֹוחַ בְּיוֹם טוֹב יַחַד עִם אִשְׁתּוֹ וּבָנָיו, וּכְמוֹ שֶׁנֶּאֱמַר (דברים יד, כו): \"וְשָׂמַחְתָּ אַתָּה וּבֵיתֶךָ\". וְכֵן נֶאֱמַר (דברים טז, יד): \"וְשָׂמַחְתָּ בְּחַגֶּךָ אַתָּה וּבִנְךָ וּבִתֶּךָ\" וְגוֹ'. וּבִפְרָט אִם אִשְׁתּוֹ מַקְפִּידָה עַל זֶה, שֶׁבְּווַדַּאי שֶׁאֵין לוֹ לִנְסוֹעַ לְרַבּוֹ בְּנִגּוּד לִרְצוֹנָהּ, שֶׁהֲרֵי גָּדוֹל הַשָּׁלוֹם. וְכָל שֶׁכֵּן שֶׁאֵין לַעֲשׂוֹת כֵּן בַּשָּׁנָה הָרִאשׁוֹנָה לְנִשּׂוּאָיו עִם אִשְׁתּוֹ, וּכְמוֹ שֶׁכָּתוּב (דברים כד, ה): \"נָקִי יִהְיֶה לְבֵיתוֹ שָׁנָה אֶחָת וְשִׂמַּח אֶת אִשְׁתּוֹ אֲשֶׁר לָקָח\". וְאֵין הַמִּצְוָה לְהַקְבִּיל פְּנֵי רַבּוֹ בָּרֶגֶל אֶלָּא כְּשֶׁרַבּוֹ חוֹנֶה בְּעִירוֹ וְשַׁעַר מְקוֹמוֹ, בְּאֹפֶן שֶׁיָּכוֹל לָלֶכֶת לְבַקֵּר אֶת רַבּוֹ וְאַחַר כָּךְ חוֹזֵר לְבֵיתוֹ בּוֹ בַּיּוֹם. וַאֲפִילּוּ אִם רוֹאֶה שֶׁאִשְׁתּוֹ מוֹחֶלֶת וּמַסְכִּימָה שֶׁיִּסַּע לְרַבּוֹ, אֵין רָאוּי לַעֲשׂוֹת כֵּן. אֲבָל אִם הִיא מְמָרֶצֶת אוֹתוֹ וּמְעוֹדֶדֶת אוֹתוֹ שֶׁיִּסַּע לְרַבּוֹ, יָכוֹל לִנְסוֹעַ לְרַבּוֹ, וּבִלְבַד שֶׁיְּקַיֵּם מִצְות שִׂמְחָה לְאִשְׁתּוֹ עַל יְדֵי קְנִיַּת בְּגָדִים נָאִים וְתַכְשִׁיטִים יָפִים לְאִשְׁתּוֹ וּלְבֵיתוֹ.",
  "Y en cualquier caso no es correcto que la persona abandone en la fiesta a su esposa y a sus hijos, y se vaya de viaje a su maestro, que reside en otra ciudad, para pasar allí el Yom Tov o el Rosh HaShaná, con el fin de cumplir la mitzvá de recibir el rostro de su maestro en la fiesta; pues es mitzvá de la Torá alegrarse en Yom Tov junto con su esposa y sus hijos, como está dicho (Devarim 14:26): «y te alegrarás, tú y tu casa». Y asimismo está dicho (Devarim 16:14): «y te alegrarás en tu fiesta, tú, y tu hijo, y tu hija», etc. Y en particular si su esposa se molesta por ello, pues ciertamente no debe viajar a su maestro en contra de su voluntad, ya que grande es la paz. Y con mayor razón no debe hacerlo así en el primer año de su matrimonio con su esposa, como está escrito (Devarim 24:5): «libre estará para su casa un año, y alegrará a su esposa que tomó». Y la mitzvá de recibir el rostro del maestro en la fiesta no rige sino cuando el maestro reside en su misma ciudad, de modo que pueda ir a visitar a su maestro y después volver a su casa ese mismo día. E incluso si ve que su esposa lo permite y está de acuerdo en que viaje a su maestro, no conviene hacerlo así; pero si ella lo anima y lo alienta a que viaje a su maestro, puede viajar a su maestro, siempre que cumpla la mitzvá de alegría para con su esposa comprándole ropas elegantes y joyas bonitas a su esposa y a su casa."),
 ("טו", "חַיָּיב אָדָם לְטַהֵר אֶת עַצְמוֹ בָּרֶגֶל, וְלָכֵן צָרִיךְ לִטְבֹּל בְּמִקְווֵה טָהֳרָה בְּעֶרֶב יוֹם טוֹב. אֶלָּא שֶׁבִּזְמַן הַזֶּה שֶׁהַכֹּל טְמֵאֵי מֵתִים, אֵין תּוֹעֶלֶת בָּזֶה כָּל כָּךְ לְהִטַּהֵר בְּעֶרֶב יוֹם טוֹב, וְלָכֵן אֵין בָּזֶה חִיּוּב מִן הַדִּין, אֶלָּא מִמִּידַּת חֲסִידוּת בִּלְבַד לְמִי שֶׁאֶפְשָׁר לוֹ, וְשֶׁאֵין בַּדָּבָר בִּטּוּל תּוֹרָה גָּדוֹל.",
  "La persona está obligada a purificarse en la fiesta, y por eso hace falta sumergirse en la <i>mikvé</i> de pureza en la víspera de Yom Tov. Solo que en nuestro tiempo, en que todos somos impuros por contacto con muertos, no hay tanta utilidad en purificarse en víspera de Yom Tov; por eso no hay en esto obligación de la ley, sino solo un grado de piedad para quien le sea posible, y siempre que no suponga una gran interrupción del estudio de la Torá."),
 ("טז", "חַיָּיבִים בֵּית דִּין בְּכָל אֲתַר וַאֲתַר (בִּזְמַן שֶׁהַשִּׁלְטוֹן בְּיַד גְּדוֹלֵי יִשְׂרָאֵל) לְהַעֲמִיד שׁוֹטְרִים בִּימֵי הָרְגָלִים, שֶׁיִּהְיוּ מְשׁוֹטְטִים בַּגַּנּוֹת וּבַפַּרְדֵּסִים, וְעַל שְׂפַת הַיָּם, וְיַשְׁגִּיחוּ שֶׁלֹּא יִתְקַבְּצוּ שָׁם אֲנָשִׁים וְנָשִׁים יַחְדָּיו לֶאֱכֹול וְלִשְׁתּוֹת וְלִשְׂמֹוחַ בִּשְׂחוֹק וְקַלּוּת רֹאשׁ, פֶּן יָבֹאוּ לִידֵי עֲבֵירָה. וּכְמוֹ שֶׁשָּׁנִינוּ (אבות פ\"ג מי\"ג): שְׂחוֹק וְקַלּוּת רֹאשׁ מְבִיאִים לִידֵי הֶרְגֵּל עֲבֵירָה. וְעַל חַכְמֵי יִשְׂרָאֵל לְהַזְהִיר אֶת כָּל הָעָם שֶׁלֹּא יִתְעָרְבוּ יַחְדָּיו אֲנָשִׁים וְנָשִׁים בְּבָתֵּיהֶם לִשְׂמֹוחַ בְּמַאֲכָל וּבְמִשְׁתֶּה, וְלֹא יִמָּשְׁכוּ אַחַר הַיַּיִן, כְּדֵי שֶׁלֹּא יָבוֹאוּ לִידֵי עֲבֵירָה, \"וְהָיָה מַחֲנֵינוּ קָדוֹשׁ\" (הרמב\"ם פ\"ו מהל' יום טוב הל' כא). וּבִמְקוֹם גִּילָה שָׁם תְּהֵא רְעָדָה (ברכות ל:).",
  "Está obligado el tribunal, en cada lugar (en el tiempo en que el gobierno está en manos de los grandes de Israel), a poner guardias en los días de las fiestas de peregrinación, que patrullen los jardines y los huertos, y a orillas del mar, y vigilen que no se junten allí hombres y mujeres juntos para comer, beber y alegrarse con risa y ligereza de cabeza, no sea que lleguen a transgredir. Y como aprendimos (Avot 3:13): la risa y la ligereza de cabeza llevan al hábito de transgredir. Y los sabios de Israel deben advertir a todo el pueblo que no se mezclen juntos hombres y mujeres en sus casas para alegrarse con comida y bebida, y que no se dejen arrastrar por el vino, para que no lleguen a transgredir, «y que nuestro campamento sea santo» (Rambam, cap. 6 de Hiljot Yom Tov, halajá 21). Y donde hay alegría, que haya también temblor (Berajot 30b)."),
 ("יז", "גַּם בִּזְמַן הַזֶּה מִצְוָה מִן הַתּוֹרָה לְקַיֵּים מִצְות \"וְשָׂמַחְתָּ בְּחַגֶּךָ\" בַּאֲכִילַת בָּשָׂר וּשְׁתִיַּת יַיִן, וּכְמְבֹאָר לְעֵיל סָעִיף ט.",
  "También en nuestro tiempo hay mitzvá de la Torá de cumplir el precepto de «y te alegrarás en tu fiesta» comiendo carne y bebiendo vino, como se explicó arriba en el apartado 9."),
 ("יח", "אָסוּר לְטַפֵּחַ וְלִרְקֹד בְּיוֹם טוֹב, שֶׁדִּין יוֹם טוֹב כְּדִין שַׁבָּת גַּם לְעִנְיָן זֶה, זוּלַת בְּשִׂמְחַת תּוֹרָה שֶׁהִתִּירוּ לִכְבוֹד הַתּוֹרָה.",
  "Está prohibido aplaudir y bailar en Yom Tov, pues la ley del Yom Tov es como la ley del Shabat también en este aspecto, salvo en Simjat Torá, que lo permitieron en honor de la Torá."),
]

for letra, he, es in HALAJOT:
  BLOQUES.append({"t": "halaja", "letra": letra, "he": he, "es": es})

# ============================================================ PIE DE PÁGINA — anuncios y memoriales
BLOQUES.append({"t": "par",
  "he": "\"הַשָּׁם גְּבוּלֵךְ שָׁלוֹם, חֵלֶב חִיטִּים יַשְׂבִּיעֵךְ\". אֵימָתַי גְּבוּלֵךְ שָׁלוֹם? כַּאֲשֶׁר חִיטִּים יַשְׂבִּיעֵךְ",
  "es": "«El que pone en tu término la paz, de lo mejor del trigo te sacia» (Tehilim 147:14). ¿Cuándo está en paz tu término? Cuando el trigo te sacia."})

BLOQUES.append({"t": "pie",
  "he": "לְעִלּוּי נִשְׁמַת: חנניה בר איז'ה, מרים בת שמחה-סוליקה בת עליה. לְעִלּוּי נִשְׁמַת: משה בן רג'ינה ז\"ל, בן בתיה כהן שאמו זצוק\"ל. יוסף בן רחל. לְזִיוּוּג הָגוּן: שרה שירה בת אילנה חיה, יעל בת זוהרה/רוזט, אשרת בת יונה, פנחס בן יונה. לְהַצְלָחַת: אסף ומשה נחשון בן שמחה, אלעד יאיר בן שמחה, רן בן הרה\"ג דוד צדוק שליט\"א.",
  "es": "En memoria de: Jananiá bar Izja, Miriam bat Simjá - Sulika bat Aliyá. En memoria de: Moshé ben Reyina, z”l, ben Bitiá Cohen —que su madre en paz descanse—. Yosef ben Rajel. Para un buen enlace: Sara Shira bat Ilana Jaya, Yael bat Zohara/Rozet, Osheret bat Yoná, Pinjás ben Yoná. Para el éxito de: Asaf y Moshé Najshón ben Simjá, Elad Yaír ben Simjá, Ran ben el Rab Gaón David Tzadok, shlitá."})

BLOQUES.append({"t": "pie",
  "he": "כְּמוֹ כֵן נִפְתַּחַת מַגְמָה לְתוֹשָׁבֵי הַמֶּרְכָּז וְהַצָּפוֹן לְלִמּוּדֵי שְׁחִיטָה, סת\"ם, נִקּוּר וּמִילָה, עִיּוּנִי וּמַעֲשִׂי, בְּשִׁתּוּף וְהַדְרָכָה שֶׁל \"מכון ברית אליהו\" בְּרֹאשׁוּת הרה\"ג נתנאל ספטי שליט\"א. לַבּוֹגְרִים תִּינָּתֵן תְּעוּדַת הַסְמָכָה מֻכֶּרֶת עַל יְדֵי הָרַבָּנוּת הָרָאשִׁית. הָרִשּׁוּם בְּוָצְאָפּ 054-6455-403 אוֹ בְּמַייל. וְלַמְפֻורְסָמוֹת אֵין צָרִיךְ רְאָיָה...",
  "es": "Asimismo se abre, con la ayuda de Dios, una especialidad para los residentes del centro y del norte para estudios de <i>shejitá</i> [matanza ritual], STaM [escritura sagrada], <i>nikur</i> [desvenado] y <i>milá</i> [circuncisión], teórica y práctica, en colaboración y con la guía del «Instituto Brit Eliyahu», presidido por el Rab Gaón Netanel Sapeti, shlitá. Los graduados recibirán un título de acreditación reconocido por el Gran Rabinato. La inscripción por WhatsApp al 054-6455-403 o por correo. Y lo notorio no necesita prueba..."})
