# -*- coding: utf-8 -*-
CAP = 4
TITULO = "Las medidas de la sucá y sus paredes"
ES = [
"La medida de la sucá: su altura, no menos de diez <i>tefajim</i> ni más de veinte <i>amot</i>; y su anchura, no menos de siete <i>tefajim</i> por siete <i>tefajim</i>. Y puede añadir en su anchura incluso varias <i>milin</i>. Si era de menos de diez, o de menos de siete por siete, o más alta de veinte <i>amot</i> en cualquier medida, es inválida.",
"Una sucá que no tiene tres paredes es inválida. Si tenía dos paredes completas, una junto a otra, en forma de ángulo (como la letra <i>gam</i>), hace una pared de más de un <i>téfaj</i> de ancho y la coloca a menos de tres [<i>tefajim</i>] junto a una de las dos paredes, y con eso basta; y hay que hacerle una «forma de puerta» (<i>tzurat hapétaj</i>), porque no tiene tres paredes completas. Y ya explicamos en las leyes de Shabat que la «forma de puerta» de la que se habla en todo lugar es incluso una caña de aquí, una caña de allá y una caña encima de ellas, aunque no las toque.",
"Si tenía dos paredes una frente a otra y entre ellas quedaba abierto de lado a lado, hace una pared de cuatro <i>tefajim</i> y algo de ancho y la coloca a menos de tres junto a una de las dos paredes, y es válida; y hay que hacerle una «forma de puerta». Cañas que salen del <i>sejaj</i> de la sucá hacia delante de la sucá, y una de las paredes se prolonga con ellas: son como la sucá.",
"Paredes pegadas al techo de la sucá que no llegaban al suelo: si estaban a tres <i>tefajim</i> del suelo, es inválida; menos que eso, válida. Si las paredes estaban pegadas al suelo y no llegaban al <i>sejaj</i>: si tienen diez <i>tefajim</i> de alto, aunque estén a varias <i>amot</i> del techo, es válida, siempre que las paredes queden alineadas bajo el borde del techo. Si alejó el techo de la pared tres <i>tefajim</i>, es inválida; menos que eso, válida. Si colgó una <i>mejitzá</i> de cuatro y algo de alto en el medio, a menos de tres del suelo y a menos de tres del techo, es válida.",
"Quien hace su sucá entre los árboles y los árboles son sus paredes: si eran fuertes, o los ató y los reforzó de modo que el viento normal no los mueva continuamente, y rellenó entre las copas con paja y rastrojo para que el viento no los mueva, y los ató, es válida. Porque toda <i>mejitzá</i> que no puede sostenerse ante el viento normal de tierra firme no es <i>mejitzá</i>.",
"Quien hace su sucá sobre un carro o sobre un barco: es válida, y se sube a ella en Yom Tov. Sobre la copa de un árbol o sobre un camello: es válida, pero no se sube a ella en Yom Tov, porque está prohibido subir en Yom Tov a un árbol o sobre un animal. Si parte de las paredes estaban hechas por mano del hombre y parte eran árboles, se considera: si al quitar los árboles puede sostenerse con las paredes hechas por el hombre, se sube a ella en Yom Tov.",
"Una sucá que no tiene techo es inválida. ¿Cómo? Por ejemplo, si los extremos de las paredes estaban pegados unos con otros, en punta como una choza; o si apoyó el extremo de la pared de la sucá contra el muro. Si tenía techo aunque fuera de un <i>téfaj</i>, o si levantó del suelo un <i>téfaj</i> la pared apoyada en el muro, es válida. Una sucá redonda: si su perímetro da para inscribir en ella siete <i>tefajim</i> por siete <i>tefajim</i>, aunque no tenga esquinas, es válida.",
"Si puso <i>sejaj</i> sobre un pórtico (<i>ajsadrá</i>) que tiene pilastras, tanto si se ven por dentro y no por fuera como si se ven por fuera y no por dentro, es válida.",
"Si no tenía pilastras, es inválida, porque es una sucá hecha como un callejón (<i>mavoi</i>): solo tiene los dos lados del pórtico, y el centro del pórtico no tiene muro, y lo que está enfrente no tiene pilastras.",
"Si puso <i>sejaj</i> sobre un callejón que tiene <i>lejí</i>, o sobre un pozo que tiene tablillas, es sucá válida solo para ese Shabat que cae dentro de la fiesta: puesto que ese <i>lejí</i> y esas tablillas son <i>mejitzot</i> para lo tocante a Shabat, las consideramos <i>mejitzot</i> también para lo tocante a la sucá.",
"Si clavó cuatro postes en las cuatro esquinas del tejado y puso <i>sejaj</i> sobre ellos: puesto que el <i>sejaj</i> está sobre el borde del tejado, es válido, y consideramos las paredes de abajo como si subieran hasta el borde del <i>sejaj</i>.",
"Una sucá que tiene muchas aberturas y en cuyas paredes hay muchas ventanas es válida, aunque lo abierto sea mayor que lo que queda en pie, siempre que no haya allí una abertura de más de diez [<i>amot</i>]. Pero si había allí una abertura de más de diez, aunque tenga «forma de puerta», hace falta que lo abierto no sea mayor que lo que queda en pie.",
"Una sucá cuyo espacio es más alto de veinte <i>amot</i> y la redujo con almohadas y colchas: no es reducción, ni siquiera si las dejó allí para siempre. Si la redujo con paja y la dejó allí, eso es reducción; y no hace falta decir con tierra que dejó allí. Pero con tierra sin más no es reducción. Si era más alta de veinte <i>amot</i> y había hojas de palma que bajaban dentro de las veinte: si su sombra era mayor que su sol, se consideran como un techo grueso y es válida.",
"Si construyó dentro una plataforma junto a la pared central, a todo lo largo: si la plataforma tiene la medida de la anchura de la sucá, es válida. Si construyó la plataforma junto a la pared central, por un lado: si desde el borde de la plataforma hasta el muro hay cuatro <i>amot</i>, es inválida; menos de cuatro <i>amot</i>, válida. Si construyó la plataforma en el centro: si desde el borde de la plataforma hasta el muro hay cuatro <i>amot</i> por cada lado, es inválida; menos de cuatro <i>amot</i>, válida, y es como si las <i>mejitzot</i> tocaran la plataforma, y desde la plataforma hasta el <i>sejaj</i> hay menos de veinte <i>amot</i>. Si construyó dentro una columna y en ella cabe la medida de una sucá, es inválida, porque esas no son paredes reconocibles, y resulta que sobre la columna hay <i>sejaj</i> válido sin paredes.",
"Si era de menos de diez y cavó en ella para completarla a diez: si desde el borde de lo cavado hasta el muro hay tres <i>tefajim</i>, es inválida; menos que eso, válida, porque todo lo que es menos de tres se considera pegado, como explicamos en las leyes de Shabat.",
"Las paredes de la sucá valen de cualquier material, porque no necesitamos más que una <i>mejitzá</i> de cualquier clase, incluso de seres vivos. Y una persona puede hacer de su compañero pared en Yom Tov, para comer, beber y dormir en una sucá válida cuya pared es su compañero; y eso, a condición de que lo haga sin que el que sirve de pared lo sepa. Pero si lo hizo con su conocimiento, está prohibido en Yom Tov y permitido en los demás días de la fiesta. Y también puede hacer con utensilios la cuarta pared en Yom Tov; pero la tercera pared no la hará con utensilios en Yom Tov, porque con ella habilita la sucá, y no se hace una tienda provisional en Yom Tov.",
]
