# -*- coding: utf-8 -*-
CAP = 6
TITULO = "Quién está obligado y cómo se habita en la sucá"
ES = [
"Las mujeres, los esclavos y los menores están exentos de la sucá. El <i>tumtum</i> y el <i>androguinos</i> están obligados por duda; y asimismo quien es mitad esclavo y mitad libre está obligado. Un menor que ya no necesita a su madre —es decir, [como de cinco] como de seis años— está obligado a la sucá por palabra de los escribas, para educarlo en las mitzvot.",
"Los enfermos y quienes los atienden están exentos de la sucá; y no solo el enfermo que corre peligro, sino incluso el que sufre de la cabeza o de los ojos. El que padece incomodidad (<i>mitztaer</i>) está exento de la sucá, él pero no quienes lo atienden. ¿Y quién es el <i>mitztaer</i>? El que no puede dormir en la sucá a causa del viento, o de las moscas y las pulgas y cosas semejantes, o a causa del olor.",
"El que está de duelo está obligado a la sucá. Y el novio, y todos los acompañantes, y todos los de la boda, están exentos de la sucá durante los siete días del banquete.",
"Los enviados a una mitzvá están exentos de la sucá, tanto de día como de noche. Los que van de camino de día están exentos de la sucá de día y obligados de noche; los que van de camino de noche están exentos de noche y obligados de día. Los guardas de la ciudad de día están exentos de día y obligados de noche; los guardas de noche están exentos de noche y obligados de día. Los guardas de huertos y vergeles están exentos tanto de día como de noche, porque si el guarda hiciera una sucá sabría el ladrón que tiene un sitio fijo, e iría a robar a otro sitio.",
"¿Cómo es la mitzvá de habitar en la sucá? Que coma, beba y viva en la sucá los siete días, tanto de día como de noche, igual que vive en su casa el resto del año. Los siete días la persona hace de su casa algo provisional y de su sucá algo fijo, como está dicho: «En cabañas habitaréis siete días». ¿Cómo? Los utensilios bonitos y la ropa de cama buena, en la sucá; los utensilios de beber, como jarras y vasos, en la sucá; pero los utensilios de comer, como ollas y platos, fuera de la sucá. El candelabro, en la sucá; y si la sucá era pequeña, lo pone fuera de la sucá.",
"Se come, se bebe y se duerme en la sucá los siete días, tanto de día como de noche. Y está prohibido comer una comida fuera de la sucá los siete días, salvo que coma un bocado ocasional, como un <i>kebeitzá</i> o menos, o un poco más. Y no se duerme fuera de la sucá ni siquiera un sueño breve. Está permitido beber agua y comer frutas fuera de la sucá; y quien sea estricto consigo mismo y no beba fuera de la sucá ni siquiera agua, es digno de alabanza.",
"Comer en la sucá la noche del primer día de fiesta es obligación: aunque haya comido un <i>kezait</i> de pan, cumplió su obligación. De ahí en adelante es voluntario: si quiere comer una comida, come en la sucá; y si quiere, no come en los siete días más que frutas o granos tostados fuera de la sucá, igual que la ley de comer matzá en Pésaj.",
"Quien tenía la cabeza y la mayor parte del cuerpo dentro de la sucá y su mesa dentro de su casa o fuera de la sucá, y come así: está prohibido, y es como si no hubiera comido en la sucá, hasta que su mesa esté dentro de la sucá. Es decreto, no sea que se deje llevar tras su mesa. E incluso en una sucá grande.",
"Los siete días lee dentro de la sucá; pero cuando quiera entender y precisar lo que lee, lo entenderá fuera de la sucá, para tener la mente tranquila. El que reza, si quiere reza en la sucá y si quiere fuera de la sucá.",
"Si cayó lluvia, entra dentro de la casa. ¿Desde cuándo está permitido salir? Desde que caen dentro de la sucá gotas tales que, si cayeran dentro del guiso, lo estropearían, aunque sea un guiso de habas. Si estaba comiendo en la sucá y cayó lluvia y entró en su casa, y cesó la lluvia, no se le obliga a volver a la sucá (toda esa noche) hasta que termine su comida. Si estaba durmiendo y cayó lluvia de noche y entró dentro de la casa, y cesó la lluvia, no se le molesta para volver a la sucá toda esa noche, sino que duerme en su casa hasta que salga el alba.",
"Si terminó de comer el séptimo día por la mañana, no desmonte su sucá; pero sí baja sus utensilios y los retira desde la hora de <i>minjá</i> en adelante. Si no tiene sitio donde ponerlos, abre en ella un hueco de cuatro por cuatro. Y si necesita comer el resto del día, tiene que comer en la sucá, porque su mitzvá son los siete días.",
"Siempre que entre a sentarse en la sucá durante los siete días, bendice antes de sentarse: «...que nos santificó con sus mitzvot y nos ordenó habitar en la sucá». Y la noche del primer día de fiesta bendice primero sobre la sucá y después el <i>shehejeyanu</i>, y ordena todas las bendiciones sobre la copa. Resulta, pues, que hace el <i>kidush</i> de pie, bendice «habitar en la sucá», se sienta y después bendice el <i>shehejeyanu</i>. Y así era la costumbre de mis maestros y de los rabinos de Sefarad: hacer el <i>kidush</i> de pie la primera noche de la fiesta de Sucot, como hemos explicado.",
"En nuestro tiempo, que hacemos dos días de fiesta, se habita en la sucá ocho días. Y el octavo día, que es el primer día de fiesta de Sheminí Atzéret, se habita en ella pero no se bendice «habitar en la sucá». Y asimismo el <i>tumtum</i> y el <i>androguinos</i> nunca bendicen «habitar en la sucá», porque están obligados por duda, y no se bendice por duda.",
"Si terminó de comer el octavo día, baja sus utensilios y la vacía. Si no tiene sitio donde bajar sus utensilios: si era pequeña, mete en ella el candelabro; y si era grande, mete en ella ollas y platos y cosas así, para recordar que es inválida y que su mitzvá ya se cumplió. Y como es Yom Tov, no puede abrir en ella un hueco para invalidarla.",
"Quien no hizo sucá, sea por descuido sea a propósito, hace una sucá en <i>jol hamoed</i>; incluso al final del séptimo día hace una sucá, porque su mitzvá son los siete días. Las maderas de la sucá están prohibidas los ocho días de la fiesta, tanto las de las paredes como las del <i>sejaj</i>: no se aprovecha de ellas para otra cosa los ocho días, porque todo el séptimo día la sucá es <i>muktzé</i> hasta el crepúsculo; y puesto que quedó apartada para el crepúsculo del octavo, quedó apartada para todo el día.",
"Y asimismo los alimentos y bebidas que se cuelgan en la sucá para adornarla: está prohibido servirse de ellos los ocho días. Y si puso condición sobre ellos en el momento de colgarlos y dijo: «no me abstengo de ellos durante todo el crepúsculo», puede servirse de ellos cuando quiera, porque no los apartó, ni recayó sobre ellos la santidad de la sucá, ni se consideraron como ella.",
]
