# -*- coding: utf-8 -*-
CAP = 8
TITULO = "Las cuatro especies inválidas · La alegría de la fiesta"
ES = [
"Estas cuatro especies —lulav, mirto, sauce y etrog— si una de ellas estaba seca, o robada, o hurtada, incluso después de que el dueño perdiera la esperanza de recuperarla, o si procedía de un árbol de culto adorado, aunque lo hubieran retirado de su culto, o si era de una ciudad descarriada, es inválida. Si una de ellas era de idolatría, no la tome <i>lejatjilá</i>, y si la tomó, cumplió. Si estaba mustia pero no acabó de secarse, es válida. Y en momento de apuro o de peligro, el lulav seco es válido, pero no las demás especies.",
"Un etrog de <i>orlá</i>, de <i>terumá</i> impura o de <i>tével</i>, es inválido. De <i>demay</i>, válido, porque es posible que declare sus bienes sin dueño y sea pobre, a quien le está permitido comer <i>demay</i>. Un etrog de <i>terumá</i> pura o de <i>maaser shení</i> en Jerusalén, no lo tome, no sea que lo haga susceptible de impureza; y si lo tomó, es válido.",
"Un lulav al que se le cortó la punta es inválido. Si se rajó: si sus dos partes se separaron una de otra hasta verse como dos, es inválido. Si estaba curvado hacia delante, de modo que su tronco queda como la espalda de un jorobado, es inválido. Si estaba curvado hacia atrás, es válido, porque así es su naturaleza. Si se torció hacia uno de sus lados, es inválido. Si sus hojas se separaron unas de otras pero no quedaron colgando como las hojas de las ramas de palmera, es válido. Si sus hojas se desgajaron —es decir, que cuelgan del tronco del lulav como las hojas de las ramas—, es inválido.",
"La naturaleza de las hojas del lulav es esta: cuando crecen, crecen de dos en dos y están pegadas por el dorso; y el dorso de cada par de hojas pegadas es lo que se llama <i>tiomet</i>. Si se partió la <i>tiomet</i>, es inválido. Si sus hojas eran de una en una desde el principio de su formación y no tenían <i>tiomet</i>, es inválido. Si sus hojas no estaban una sobre otra, como en todos los lulavim, sino una debajo de otra: si la punta de esta llega a la base de la que está por encima, de modo que todo el tronco del lulav queda cubierto de hojas, es válido; y si la punta de esta no llega al lado de la base de aquella, es inválido.",
"Un mirto al que se le cortó la punta es válido. Si se le cayeron la mayoría de las hojas: si quedaron tres hojas en un mismo nudo, es válido. Si sus bayas eran más que sus hojas: si son verdes, es válido; y si son rojas o negras, es inválido; y si las redujo, es válido. Y no se reducen en Yom Tov, porque es como arreglar un utensilio. Si transgredió y las quitó, o si las quitó de una en una para comerlas, es válido.",
"Un sauce al que se le cortó la punta es válido. Si sus hojas se desgajaron, es inválido.",
"Un etrog perforado con un agujero pasante, en cualquier medida, es inválido; y el que no es pasante, si era como un <i>isar</i> o más, es inválido. Si le falta cualquier cantidad, es inválido. Si se le quitó su <i>dad</i> —que es la punta pequeña en la que está su flor—, es inválido. Si se le quitó el tallo por el que cuelga del árbol, desde la base del etrog, y quedó en su lugar un hoyo, es inválido. Si le salió <i>jazazit</i> [costra]: si es en dos o tres sitios, es inválido; y si es en un solo sitio, si cubrió la mayor parte, es inválido; y si es en su <i>dad</i>, aunque sea en cualquier medida, es inválido. Si se le peló la membrana exterior, de manera que no le falta nada, sino que queda verde como es su naturaleza: si se peló entera, es inválido; y si quedó de ella cualquier cantidad, es válido.",
"Un etrog hinchado, podrido, encurtido, cocido, negro, blanco, moteado o verde como el puerro, es inválido. Si lo crió en un molde y lo hizo como otra criatura, es inválido; si lo hizo conforme a su forma natural, aunque lo haya hecho con gajos marcados, es válido. El etrog doble y el que aún no ha madurado, válido. En un lugar donde sus etroguim tienen algo de negrura ligera, son válidos; pero si eran muy negros, como un hombre etíope, es inválido en todo lugar.",
"Todos estos que hemos dicho que son inválidos por los defectos que hemos explicado, o por robo y hurto, lo son solo el primer día de fiesta; pero el segundo día de fiesta y el resto de los días, todo es válido. Y la invalidez que viene de la idolatría, o de que ese etrog esté prohibido para comer, es invalidez tanto el primer día como los demás días.",
"Nadie cumple el primer día de la fiesta con el lulav de su compañero que le pide prestado, hasta que se lo dé como regalo. Si se lo dio a condición de que se lo devuelva, cumple con él su obligación y se lo devuelve, porque un regalo a condición de devolverlo se llama regalo; y si no se lo devolvió, no cumplió, porque resulta como robado. Y no se le da a un menor, porque el menor adquiere pero no transmite a otros según la Torá, y resulta que, si se lo devuelve, no vuelve a ser del primero. Y lo mismo vale para el lulav que para cada una de las cuatro especies que van con él: si una de ellas era prestada, no se cumple con ella el primer día de fiesta.",
"Socios que compraron un lulav o un etrog en común: ninguno de ellos cumple con él su obligación el primer día hasta que el otro le dé su parte como regalo. Hermanos que compraron etroguim del fondo común de la casa, y uno de ellos tomó un etrog y cumplió con él: si puede comérselo y los hermanos no se molestan por ello, cumplió; y si se molestaban, no cumplió hasta que le den su parte como regalo. Y si este compró un etrog y aquel otra fruta, o si compraron juntos un etrog, una granada y otra fruta del fondo común de la casa, no cumple con el etrog hasta que le den su parte como regalo, aunque, si se lo comiera, no se molestarían por ello.",
"Aunque en todas las fiestas hay mitzvá de alegrarse, en la fiesta de Sucot había en el Templo una alegría especial, como está dicho: «Y os alegraréis delante del Eterno, vuestro Dios, siete días». ¿Y cómo lo hacían? La víspera del primer día de fiesta preparaban en el Templo un sitio para las mujeres arriba y para los hombres abajo, de modo que no se mezclaran unos con otros. Y empezaban a alegrarse a la salida del primer día de fiesta; y así cada uno de los días de <i>jol hamoed</i> empezaban, después de ofrecer el sacrificio continuo de la tarde, a alegrarse el resto del día y toda la noche.",
"¿Y cómo era esta alegría? Sonaba la flauta y tocaban con el arpa, con las liras y con los címbalos, cada uno con el instrumento que sabía tocar; y el que sabía con la voz, con la voz. Y bailaban, batían palmas, daban golpes, saltaban y danzaban, cada uno como sabía, y decían palabras de canto y de alabanza. Y esta alegría no desplaza ni el Shabat ni el Yom Tov.",
"Es mitzvá abundar en esta alegría. Y no la hacían los ignorantes ni cualquiera que quisiera, sino los grandes sabios de Israel, los cabezas de las academias, el Sanedrín, los piadosos, los ancianos y los hombres de acción: ellos eran los que bailaban, batían palmas, tocaban y alegraban en el Templo en los días de la fiesta de Sucot. Pero todo el pueblo, hombres y mujeres, todos venían a ver y a escuchar.",
"La alegría con que la persona se alegra al cumplir la mitzvá y en el amor de Dios, que las ordenó, es un gran servicio. Y todo el que se priva de esta alegría merece que se le pida cuentas, como está dicho: «Porque no serviste al Eterno, tu Dios, con alegría y con buen corazón». Y todo el que se engríe, se da honor a sí mismo y se tiene por importante en estos momentos, es pecador y necio; y sobre esto advirtió Shelomó cuando dijo: «No te des importancia delante del rey». Y todo el que se rebaja y no cuenta su propia dignidad en estos momentos, ese es el grande y el honrado, el que sirve por amor. Y así dijo David, rey de Israel: «Y me rebajaré aún más que esto, y seré humilde a mis ojos». Y no hay grandeza ni honor sino alegrarse delante del Eterno, como está dicho: «Y el rey David saltaba y danzaba delante del Eterno». Fin de las Leyes de Shofar, Sucá y Lulav.",
]
